import { pixelCheckoutEventsTestScenarios } from './pixelTestScenarios/CheckoutEventsTests';
import { pixelCheckoutStepsScenarios } from './pixelTestScenarios/CheckoutStepsTests';
import { pixelEventsTestScenarios } from './pixelTestScenarios/ProductEventsTests';
import { checkoutEventsTestScenarios } from './webhookTestScenarios/CheckoutEventsTests';
import { genericTrackTestScenarios } from './webhookTestScenarios/GenericTrackTests';
import { userTestScenarios } from './webhookMappingTests/userIdentifyTests';
import { newpixelCheckoutEventsTestScenarios } from './pixelMappingTests/CheckoutEventsTests';
import { newpixelCheckoutStepsScenarios } from './pixelMappingTests/CheckoutStepsTests';
import { newpixelEventsTestScenarios } from './pixelMappingTests/ProductEventsTests';
import { newWebhookcheckoutEventsTestScenarios } from './webhookMappingTests/CheckoutEventsTests';
import { newWebhookOrderEventsTestScenarios } from './webhookMappingTests/OrderEventsTests';
import { mockFns } from './mocks';

const serverSideEventsScenariosForLegacyApp = [
  {
    name: 'shopify',
    description: 'Track Call -> carts_create ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                id: 'shopify_test3',
                token: 'shopify_test3',
                line_items: [],
                note: null,
                updated_at: '2023-02-10T12:16:07.251Z',
                created_at: '2023-02-10T12:05:04.402Z',
              }),
              query_parameters: { topic: ['carts_create'] },
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [{ outputToSource: { body: 'T0s=', contentType: 'text/plain' }, statusCode: 200 }],
      },
    },
  },
  {
    name: 'shopify',
    description: 'No Query Parameters',
    module: 'source',
    version: 'v2',
    skipGo: 'not possible',
    input: {
      request: {
        body: [{ request: { body: JSON.stringify({}) }, source: {} }],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Query_parameters is missing',
            statTags: {
              destinationId: 'Non determinable',
              errorCategory: 'transformation',
              implementation: 'native',
              module: 'source',
              srcType: 'shopify',
              workspaceId: 'Non determinable',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Invalid topic',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({}),
              query_parameters: { signature: ['rudderstack'], writeKey: ['sample-write-key'] },
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Invalid topic in query_parameters',
            statTags: {
              destinationId: 'Non determinable',
              errorCategory: 'transformation',
              implementation: 'native',
              module: 'source',
              srcType: 'shopify',
              workspaceId: 'Non determinable',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Topic Not found',
    module: 'source',
    version: 'v2',
    skipGo: 'not possible',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({}),
              query_parameters: {
                topic: [],
                signature: ['rudderstack'],
                writeKey: ['sample-write-key'],
              },
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Topic not found',
            statTags: {
              destinationId: 'Non determinable',
              errorCategory: 'transformation',
              implementation: 'native',
              module: 'source',
              srcType: 'shopify',
              workspaceId: 'Non determinable',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Unsupported Event Type',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({}),
              query_parameters: {
                topic: ['random_event'],
                signature: ['rudderstack'],
                writeKey: ['sample-write-key'],
              },
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [{ outputToSource: { body: 'T0s=', contentType: 'text/plain' }, statusCode: 200 }],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Identify Call for customers create event',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              query_parameters: {
                topic: ['customers_create'],
                signature: ['rudderstack'],
                writeKey: ['sample-write-key'],
              },
              body: JSON.stringify({
                id: 5747017285820,
                email: 'anuraj@rudderstack.com',
                accepts_marketing: false,
                created_at: '2021-12-29T15:15:19+05:30',
                updated_at: '2021-12-29T15:15:20+05:30',
                first_name: 'Anuraj',
                last_name: 'Guha',
                orders_count: 0,
                state: 'disabled',
                total_spent: '0.00',
                last_order_id: null,
                note: '',
                verified_email: true,
                multipass_identifier: null,
                tax_exempt: false,
                phone: '+919876543210',
                tags: '',
                last_order_name: null,
                currency: 'INR',
                addresses: [
                  {
                    id: 6947581821116,
                    customer_id: 5747017285820,
                    first_name: 'Anuraj',
                    last_name: 'Guha',
                    company: 'Rudderstack',
                    address1: 'Home',
                    address2: 'Apartment',
                    city: 'Kolkata',
                    province: 'West Bengal',
                    country: 'India',
                    zip: '708091',
                    phone: '+919876543210',
                    name: 'Anuraj Guha',
                    province_code: 'WB',
                    country_code: 'IN',
                    country_name: 'India',
                    default: true,
                  },
                ],
                accepts_marketing_updated_at: '2021-12-29T15:15:20+05:30',
                marketing_opt_in_level: null,
                tax_exemptions: [],
                sms_marketing_consent: {
                  state: 'not_subscribed',
                  opt_in_level: 'single_opt_in',
                  consent_updated_at: null,
                  consent_collected_from: 'SHOPIFY',
                },
                admin_graphql_api_id: 'gid://shopify/Customer/5747017285820',
                default_address: {
                  id: 6947581821116,
                  customer_id: 5747017285820,
                  first_name: 'Anuraj',
                  last_name: 'Guha',
                  company: 'Rudderstack',
                  address1: 'Home',
                  address2: 'Apartment',
                  city: 'Kolkata',
                  province: 'West Bengal',
                  country: 'India',
                  zip: '708091',
                  phone: '+919876543210',
                  name: 'Anuraj Guha',
                  province_code: 'WB',
                  country_code: 'IN',
                  country_name: 'India',
                  default: true,
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'RudderStack Shopify Cloud', version: '1.0.0' },
                    integration: { name: 'SHOPIFY' },
                    topic: 'customers_create',
                  },
                  integrations: { SHOPIFY: true },
                  type: 'identify',
                  userId: '5747017285820',
                  traits: {
                    email: 'anuraj@rudderstack.com',
                    firstName: 'Anuraj',
                    lastName: 'Guha',
                    phone: '+919876543210',
                    addressList: [
                      {
                        id: 6947581821116,
                        customer_id: 5747017285820,
                        first_name: 'Anuraj',
                        last_name: 'Guha',
                        company: 'Rudderstack',
                        address1: 'Home',
                        address2: 'Apartment',
                        city: 'Kolkata',
                        province: 'West Bengal',
                        country: 'India',
                        zip: '708091',
                        phone: '+919876543210',
                        name: 'Anuraj Guha',
                        province_code: 'WB',
                        country_code: 'IN',
                        country_name: 'India',
                        default: true,
                      },
                    ],
                    address: {
                      id: 6947581821116,
                      customer_id: 5747017285820,
                      first_name: 'Anuraj',
                      last_name: 'Guha',
                      company: 'Rudderstack',
                      address1: 'Home',
                      address2: 'Apartment',
                      city: 'Kolkata',
                      province: 'West Bengal',
                      country: 'India',
                      zip: '708091',
                      phone: '+919876543210',
                      name: 'Anuraj Guha',
                      province_code: 'WB',
                      country_code: 'IN',
                      country_name: 'India',
                      default: true,
                    },
                    acceptsMarketing: false,
                    orderCount: 0,
                    state: 'disabled',
                    totalSpent: '0.00',
                    note: '',
                    verifiedEmail: true,
                    taxExempt: false,
                    tags: '',
                    currency: 'INR',
                    taxExemptions: [],
                    smsMarketingConsent: {
                      state: 'not_subscribed',
                      opt_in_level: 'single_opt_in',
                      consent_updated_at: null,
                      consent_collected_from: 'SHOPIFY',
                    },
                    adminGraphqlApiId: 'gid://shopify/Customer/5747017285820',
                    acceptsMarketingUpdatedAt: '2021-12-29T15:15:20+05:30',
                  },
                  timestamp: '2021-12-29T09:45:20.000Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Unsupported checkout event',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                admin_graphql_api_id: 'gid://shopify/Fulfillment/4124667937024',
                created_at: '2022-01-05T18:13:02+05:30',
                destination: null,
                id: 4124667937024,
                line_items: [],
                customer: {
                  email: 'test_person@email.com',
                  first_name: 'Test',
                  last_name: 'Person',
                },
                billing_address: { address1: '11 Rani Sankari Lane Patuapara Bhowanipore' },
                shipping_address: { address1: '11 Rani Sankari Lane Patuapara Bhowanipore' },
                location_id: 66855371008,
                name: '#1002.1',
                order_id: 4617255092480,
                origin_address: null,
                receipt: {},
                service: 'manual',
                shipment_status: null,
                status: 'success',
                tracking_company: 'Amazon Logistics UK',
                tracking_number: 'Sample001test',
                tracking_numbers: ['Sample001test'],
                tracking_url:
                  'https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201910530',
                tracking_urls: [
                  'https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201910530',
                ],
                updated_at: '2022-01-05T18:16:48+05:30',
              }),
              query_parameters: {
                topic: ['checkout_delete'],
                writeKey: ['sample-write-key'],
                signature: ['rudderstack'],
              },
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [{ outputToSource: { body: 'T0s=', contentType: 'text/plain' }, statusCode: 200 }],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Track Call -> Fullfillments updated event',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              query_parameters: {
                topic: ['fulfillments_update'],
                writeKey: ['sample-write-key'],
                signature: ['rudderstack'],
              },
              body: JSON.stringify({
                shipping_address: { address1: '11 Rani Sankari Lane Patuapara Bhowanipore' },
                billing_address: { address1: '11 Rani Sankari Lane Patuapara Bhowanipore' },
                admin_graphql_api_id: 'gid://shopify/Fulfillment/4124667937024',
                created_at: '2022-01-05T18:13:02+05:30',
                destination: null,
                email: 'test_person@email.com',
                id: 4124667937024,
                line_items: [
                  {
                    admin_graphql_api_id: 'gid://shopify/LineItem/11896203149568',
                    discount_allocations: [],
                    duties: [],
                    fulfillable_quantity: 0,
                    fulfillment_service: 'manual',
                    fulfillment_status: 'fulfilled',
                    gift_card: false,
                    grams: 0,
                    id: 11896203149568,
                    name: 'p1',
                    origin_location: {
                      address1: '74 CC/7, Anupama Housing Estate - II',
                      address2: '',
                      city: 'Kolkatta',
                      country_code: 'IN',
                      id: 3373642219776,
                      name: '74 CC/7, Anupama Housing Estate - II',
                      province_code: 'WB',
                      zip: '700052',
                    },
                    price: '5000.00',
                    price_set: {
                      presentment_money: { amount: '5000.00', currency_code: 'INR' },
                      shop_money: { amount: '5000.00', currency_code: 'INR' },
                    },
                    product_exists: true,
                    product_id: 7510929801472,
                    properties: [],
                    quantity: 1,
                    requires_shipping: true,
                    sku: '15',
                    tax_lines: [
                      {
                        channel_liable: false,
                        price: '900.00',
                        price_set: {
                          presentment_money: { amount: '900.00', currency_code: 'INR' },
                          shop_money: { amount: '900.00', currency_code: 'INR' },
                        },
                        rate: 0.18,
                        title: 'IGST',
                      },
                    ],
                    taxable: true,
                    title: 'p1',
                    total_discount: '0.00',
                    total_discount_set: {
                      presentment_money: { amount: '0.00', currency_code: 'INR' },
                      shop_money: { amount: '0.00', currency_code: 'INR' },
                    },
                    variant_id: 42211160228096,
                    variant_inventory_management: 'shopify',
                    variant_title: '',
                    vendor: 'rudderstack-store',
                  },
                ],
                location_id: 66855371008,
                name: '#1002.1',
                order_id: 4617255092480,
                origin_address: null,
                receipt: {},
                service: 'manual',
                shipment_status: null,
                status: 'success',
                tracking_company: 'Amazon Logistics UK',
                tracking_number: 'Sample001test',
                tracking_numbers: ['Sample001test'],
                tracking_url:
                  'https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201910530',
                tracking_urls: [
                  'https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201910530',
                ],
                updated_at: '2022-01-05T18:16:48+05:30',
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'RudderStack Shopify Cloud', version: '1.0.0' },
                    integration: { name: 'SHOPIFY' },
                    topic: 'fulfillments_update',
                  },
                  integrations: { SHOPIFY: true },
                  type: 'track',
                  userId: 'shopify-admin',
                  event: 'Fulfillments Update',
                  properties: {
                    admin_graphql_api_id: 'gid://shopify/Fulfillment/4124667937024',
                    created_at: '2022-01-05T18:13:02+05:30',
                    destination: null,
                    email: 'test_person@email.com',
                    id: 4124667937024,
                    location_id: 66855371008,
                    name: '#1002.1',
                    order_id: 4617255092480,
                    origin_address: null,
                    receipt: {},
                    service: 'manual',
                    shipment_status: null,
                    status: 'success',
                    tracking_company: 'Amazon Logistics UK',
                    tracking_number: 'Sample001test',
                    tracking_numbers: ['Sample001test'],
                    tracking_url:
                      'https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201910530',
                    tracking_urls: [
                      'https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=201910530',
                    ],
                    updated_at: '2022-01-05T18:16:48+05:30',
                    products: [
                      {
                        product_id: 7510929801472,
                        sku: '15',
                        title: 'p1',
                        price: '5000.00',
                        brand: 'rudderstack-store',
                        quantity: 1,
                        admin_graphql_api_id: 'gid://shopify/LineItem/11896203149568',
                        discount_allocations: [],
                        duties: [],
                        fulfillable_quantity: 0,
                        fulfillment_service: 'manual',
                        fulfillment_status: 'fulfilled',
                        gift_card: false,
                        grams: 0,
                        id: 11896203149568,
                        origin_location: {
                          address1: '74 CC/7, Anupama Housing Estate - II',
                          address2: '',
                          city: 'Kolkatta',
                          country_code: 'IN',
                          id: 3373642219776,
                          name: '74 CC/7, Anupama Housing Estate - II',
                          province_code: 'WB',
                          zip: '700052',
                        },
                        price_set: {
                          presentment_money: { amount: '5000.00', currency_code: 'INR' },
                          shop_money: { amount: '5000.00', currency_code: 'INR' },
                        },
                        product_exists: true,
                        properties: [],
                        requires_shipping: true,
                        tax_lines: [
                          {
                            channel_liable: false,
                            price: '900.00',
                            price_set: {
                              presentment_money: { amount: '900.00', currency_code: 'INR' },
                              shop_money: { amount: '900.00', currency_code: 'INR' },
                            },
                            rate: 0.18,
                            title: 'IGST',
                          },
                        ],
                        taxable: true,
                        total_discount: '0.00',
                        total_discount_set: {
                          presentment_money: { amount: '0.00', currency_code: 'INR' },
                          shop_money: { amount: '0.00', currency_code: 'INR' },
                        },
                        variant_inventory_management: 'shopify',
                        variant: '42211160228096  ',
                      },
                    ],
                  },
                  traits: {
                    shippingAddress: { address1: '11 Rani Sankari Lane Patuapara Bhowanipore' },
                    billingAddress: { address1: '11 Rani Sankari Lane Patuapara Bhowanipore' },
                    email: 'test_person@email.com',
                  },
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'shopify',
    description: 'Track Call -> Order Partially Fulfilled event',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              query_parameters: {
                topic: ['orders_partially_fulfilled'],
                writeKey: ['sample-write-key'],
                signature: ['rudderstack'],
              },
              body: JSON.stringify({
                id: 820982911946154508,
                admin_graphql_api_id: 'gid://shopify/Order/820982911946154508',
                app_id: null,
                browser_ip: null,
                buyer_accepts_marketing: true,
                cancel_reason: 'customer',
                cancelled_at: '2021-12-31T19:00:00-05:00',
                cart_token: null,
                checkout_id: null,
                checkout_token: null,
                client_details: null,
                closed_at: null,
                confirmation_number: null,
                confirmed: false,
                contact_email: 'jon@example.com',
                created_at: '2021-12-31T19:00:00-05:00',
                currency: 'USD',
                current_subtotal_price: '398.00',
                current_subtotal_price_set: {
                  shop_money: {
                    amount: '398.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '398.00',
                    currency_code: 'USD',
                  },
                },
                current_total_additional_fees_set: null,
                current_total_discounts: '0.00',
                current_total_discounts_set: {
                  shop_money: {
                    amount: '0.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '0.00',
                    currency_code: 'USD',
                  },
                },
                current_total_duties_set: null,
                current_total_price: '398.00',
                current_total_price_set: {
                  shop_money: {
                    amount: '398.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '398.00',
                    currency_code: 'USD',
                  },
                },
                current_total_tax: '0.00',
                current_total_tax_set: {
                  shop_money: {
                    amount: '0.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '0.00',
                    currency_code: 'USD',
                  },
                },
                customer_locale: 'en',
                device_id: null,
                discount_codes: [],
                email: 'jon@example.com',
                estimated_taxes: false,
                financial_status: 'voided',
                fulfillment_status: 'pending',
                landing_site: null,
                landing_site_ref: null,
                location_id: null,
                merchant_of_record_app_id: null,
                name: '#9999',
                note: null,
                note_attributes: [],
                number: 234,
                order_number: 1234,
                order_status_url:
                  'https://jsmith.myshopify.com/548380009/orders/123456abcd/authenticate?key=abcdefg',
                original_total_additional_fees_set: null,
                original_total_duties_set: null,
                payment_gateway_names: ['visa', 'bogus'],
                phone: null,
                po_number: null,
                presentment_currency: 'USD',
                processed_at: '2021-12-31T19:00:00-05:00',
                reference: null,
                referring_site: null,
                source_identifier: null,
                source_name: 'web',
                source_url: null,
                subtotal_price: '388.00',
                subtotal_price_set: {
                  shop_money: {
                    amount: '388.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '388.00',
                    currency_code: 'USD',
                  },
                },
                tags: 'tag1, tag2',
                tax_exempt: false,
                tax_lines: [],
                taxes_included: false,
                test: true,
                token: '123456abcd',
                total_discounts: '20.00',
                total_discounts_set: {
                  shop_money: {
                    amount: '20.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '20.00',
                    currency_code: 'USD',
                  },
                },
                total_line_items_price: '398.00',
                total_line_items_price_set: {
                  shop_money: {
                    amount: '398.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '398.00',
                    currency_code: 'USD',
                  },
                },
                total_outstanding: '398.00',
                total_price: '388.00',
                total_price_set: {
                  shop_money: {
                    amount: '388.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '388.00',
                    currency_code: 'USD',
                  },
                },
                total_shipping_price_set: {
                  shop_money: {
                    amount: '10.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '10.00',
                    currency_code: 'USD',
                  },
                },
                total_tax: '0.00',
                total_tax_set: {
                  shop_money: {
                    amount: '0.00',
                    currency_code: 'USD',
                  },
                  presentment_money: {
                    amount: '0.00',
                    currency_code: 'USD',
                  },
                },
                total_tip_received: '0.00',
                total_weight: 0,
                updated_at: '2021-12-31T19:00:00-05:00',
                user_id: null,
                billing_address: {
                  first_name: 'Steve',
                  address1: '123 Shipping Street',
                  phone: '555-555-SHIP',
                  city: 'Shippington',
                  zip: '40003',
                  province: 'Kentucky',
                  country: 'United States',
                  last_name: 'Shipper',
                  address2: null,
                  company: 'Shipping Company',
                  latitude: null,
                  longitude: null,
                  name: 'Steve Shipper',
                  country_code: 'US',
                  province_code: 'KY',
                },
                customer: {
                  id: 115310627314723954,
                  email: 'john@example.com',
                  created_at: null,
                  updated_at: null,
                  first_name: 'John',
                  last_name: 'Smith',
                  state: 'disabled',
                  note: null,
                  verified_email: true,
                  multipass_identifier: null,
                  tax_exempt: false,
                  phone: null,
                  email_marketing_consent: {
                    state: 'not_subscribed',
                    opt_in_level: null,
                    consent_updated_at: null,
                  },
                  sms_marketing_consent: null,
                  tags: '',
                  currency: 'USD',
                  tax_exemptions: [],
                  admin_graphql_api_id: 'gid://shopify/Customer/115310627314723954',
                  default_address: {
                    id: 715243470612851245,
                    customer_id: 115310627314723954,
                    first_name: null,
                    last_name: null,
                    company: null,
                    address1: '123 Elm St.',
                    address2: null,
                    city: 'Ottawa',
                    province: 'Ontario',
                    country: 'Canada',
                    zip: 'K2H7A8',
                    phone: '123-123-1234',
                    name: '',
                    province_code: 'ON',
                    country_code: 'CA',
                    country_name: 'Canada',
                    default: true,
                  },
                },
                discount_applications: [],
                fulfillments: [],
                line_items: [
                  {
                    id: 866550311766439020,
                    admin_graphql_api_id: 'gid://shopify/LineItem/866550311766439020',
                    attributed_staffs: [
                      {
                        id: 'gid://shopify/StaffMember/902541635',
                        quantity: 1,
                      },
                    ],
                    current_quantity: 1,
                    fulfillable_quantity: 1,
                    fulfillment_service: 'manual',
                    fulfillment_status: null,
                    gift_card: false,
                    grams: 567,
                    name: 'IPod Nano - 8GB',
                    price: '199.00',
                    price_set: {
                      shop_money: {
                        amount: '199.00',
                        currency_code: 'USD',
                      },
                      presentment_money: {
                        amount: '199.00',
                        currency_code: 'USD',
                      },
                    },
                    product_exists: true,
                    product_id: 632910392,
                    properties: [],
                    quantity: 1,
                    requires_shipping: true,
                    sku: 'IPOD2008PINK',
                    taxable: true,
                    title: 'IPod Nano - 8GB',
                    total_discount: '0.00',
                    total_discount_set: {
                      shop_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                      presentment_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                    },
                    variant_id: 808950810,
                    variant_inventory_management: 'shopify',
                    variant_title: null,
                    vendor: null,
                    tax_lines: [],
                    duties: [],
                    discount_allocations: [],
                  },
                  {
                    id: 141249953214522974,
                    admin_graphql_api_id: 'gid://shopify/LineItem/141249953214522974',
                    attributed_staffs: [],
                    current_quantity: 1,
                    fulfillable_quantity: 1,
                    fulfillment_service: 'manual',
                    fulfillment_status: null,
                    gift_card: false,
                    grams: 567,
                    name: 'IPod Nano - 8GB',
                    price: '199.00',
                    price_set: {
                      shop_money: {
                        amount: '199.00',
                        currency_code: 'USD',
                      },
                      presentment_money: {
                        amount: '199.00',
                        currency_code: 'USD',
                      },
                    },
                    product_exists: true,
                    product_id: 632910392,
                    properties: [],
                    quantity: 1,
                    requires_shipping: true,
                    sku: 'IPOD2008PINK',
                    taxable: true,
                    title: 'IPod Nano - 8GB',
                    total_discount: '0.00',
                    total_discount_set: {
                      shop_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                      presentment_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                    },
                    variant_id: 808950810,
                    variant_inventory_management: 'shopify',
                    variant_title: null,
                    vendor: null,
                    tax_lines: [],
                    duties: [],
                    discount_allocations: [],
                  },
                ],
                payment_terms: null,
                refunds: [],
                shipping_address: {
                  first_name: 'Steve',
                  address1: '123 Shipping Street',
                  phone: '555-555-SHIP',
                  city: 'Shippington',
                  zip: '40003',
                  province: 'Kentucky',
                  country: 'United States',
                  last_name: 'Shipper',
                  address2: null,
                  company: 'Shipping Company',
                  latitude: null,
                  longitude: null,
                  name: 'Steve Shipper',
                  country_code: 'US',
                  province_code: 'KY',
                },
                shipping_lines: [
                  {
                    id: 271878346596884015,
                    carrier_identifier: null,
                    code: null,
                    discounted_price: '10.00',
                    discounted_price_set: {
                      shop_money: {
                        amount: '10.00',
                        currency_code: 'USD',
                      },
                      presentment_money: {
                        amount: '10.00',
                        currency_code: 'USD',
                      },
                    },
                    is_removed: false,
                    phone: null,
                    price: '10.00',
                    price_set: {
                      shop_money: {
                        amount: '10.00',
                        currency_code: 'USD',
                      },
                      presentment_money: {
                        amount: '10.00',
                        currency_code: 'USD',
                      },
                    },
                    requested_fulfillment_service_id: null,
                    source: 'shopify',
                    title: 'Generic Shipping',
                    tax_lines: [],
                    discount_allocations: [],
                  },
                ],
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    cart_token: null,
                    checkout_token: null,
                    integration: {
                      name: 'SHOPIFY',
                    },
                    library: {
                      name: 'RudderStack Shopify Cloud',
                      version: '1.0.0',
                    },
                    topic: 'orders_partially_fulfilled',
                  },
                  event: 'Order Partially Fulfilled',
                  integrations: {
                    SHOPIFY: true,
                  },
                  properties: {
                    admin_graphql_api_id: 'gid://shopify/Order/820982911946154508',
                    app_id: null,
                    browser_ip: null,
                    buyer_accepts_marketing: true,
                    cancel_reason: 'customer',
                    cancelled_at: '2021-12-31T19:00:00-05:00',
                    cart_token: null,
                    checkout_id: null,
                    checkout_token: null,
                    client_details: null,
                    closed_at: null,
                    confirmation_number: null,
                    confirmed: false,
                    contact_email: 'jon@example.com',
                    created_at: '2021-12-31T19:00:00-05:00',
                    currency: 'USD',
                    current_subtotal_price: '398.00',
                    current_subtotal_price_set: {
                      presentment_money: {
                        amount: '398.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '398.00',
                        currency_code: 'USD',
                      },
                    },
                    current_total_additional_fees_set: null,
                    current_total_discounts: '0.00',
                    current_total_discounts_set: {
                      presentment_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                    },
                    current_total_duties_set: null,
                    current_total_price: '398.00',
                    current_total_price_set: {
                      presentment_money: {
                        amount: '398.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '398.00',
                        currency_code: 'USD',
                      },
                    },
                    current_total_tax: '0.00',
                    current_total_tax_set: {
                      presentment_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                    },
                    customer_locale: 'en',
                    device_id: null,
                    discount_applications: [],
                    discount_codes: [],
                    email: 'jon@example.com',
                    estimated_taxes: false,
                    financial_status: 'voided',
                    fulfillment_status: 'pending',
                    fulfillments: [],
                    id: 820982911946154500,
                    landing_site: null,
                    landing_site_ref: null,
                    location_id: null,
                    merchant_of_record_app_id: null,
                    name: '#9999',
                    note: null,
                    note_attributes: [],
                    number: 234,
                    order_number: 1234,
                    order_status_url:
                      'https://jsmith.myshopify.com/548380009/orders/123456abcd/authenticate?key=abcdefg',
                    original_total_additional_fees_set: null,
                    original_total_duties_set: null,
                    payment_gateway_names: ['visa', 'bogus'],
                    payment_terms: null,
                    phone: null,
                    po_number: null,
                    presentment_currency: 'USD',
                    processed_at: '2021-12-31T19:00:00-05:00',
                    products: [
                      {
                        admin_graphql_api_id: 'gid://shopify/LineItem/866550311766439020',
                        attributed_staffs: [
                          {
                            id: 'gid://shopify/StaffMember/902541635',
                            quantity: 1,
                          },
                        ],
                        current_quantity: 1,
                        discount_allocations: [],
                        duties: [],
                        fulfillable_quantity: 1,
                        fulfillment_service: 'manual',
                        fulfillment_status: null,
                        gift_card: false,
                        grams: 567,
                        id: 866550311766439000,
                        price: '199.00',
                        price_set: {
                          presentment_money: {
                            amount: '199.00',
                            currency_code: 'USD',
                          },
                          shop_money: {
                            amount: '199.00',
                            currency_code: 'USD',
                          },
                        },
                        product_exists: true,
                        product_id: 632910392,
                        properties: [],
                        quantity: 1,
                        requires_shipping: true,
                        sku: 'IPOD2008PINK',
                        tax_lines: [],
                        taxable: true,
                        title: 'IPod Nano - 8GB',
                        total_discount: '0.00',
                        total_discount_set: {
                          presentment_money: {
                            amount: '0.00',
                            currency_code: 'USD',
                          },
                          shop_money: {
                            amount: '0.00',
                            currency_code: 'USD',
                          },
                        },
                        variant: '808950810  ',
                        variant_inventory_management: 'shopify',
                      },
                      {
                        admin_graphql_api_id: 'gid://shopify/LineItem/141249953214522974',
                        attributed_staffs: [],
                        current_quantity: 1,
                        discount_allocations: [],
                        duties: [],
                        fulfillable_quantity: 1,
                        fulfillment_service: 'manual',
                        fulfillment_status: null,
                        gift_card: false,
                        grams: 567,
                        id: 141249953214522980,
                        price: '199.00',
                        price_set: {
                          presentment_money: {
                            amount: '199.00',
                            currency_code: 'USD',
                          },
                          shop_money: {
                            amount: '199.00',
                            currency_code: 'USD',
                          },
                        },
                        product_exists: true,
                        product_id: 632910392,
                        properties: [],
                        quantity: 1,
                        requires_shipping: true,
                        sku: 'IPOD2008PINK',
                        tax_lines: [],
                        taxable: true,
                        title: 'IPod Nano - 8GB',
                        total_discount: '0.00',
                        total_discount_set: {
                          presentment_money: {
                            amount: '0.00',
                            currency_code: 'USD',
                          },
                          shop_money: {
                            amount: '0.00',
                            currency_code: 'USD',
                          },
                        },
                        variant: '808950810  ',
                        variant_inventory_management: 'shopify',
                      },
                    ],
                    reference: null,
                    referring_site: null,
                    refunds: [],
                    shipping_lines: [
                      {
                        carrier_identifier: null,
                        code: null,
                        discount_allocations: [],
                        discounted_price: '10.00',
                        discounted_price_set: {
                          presentment_money: {
                            amount: '10.00',
                            currency_code: 'USD',
                          },
                          shop_money: {
                            amount: '10.00',
                            currency_code: 'USD',
                          },
                        },
                        id: 271878346596884000,
                        is_removed: false,
                        phone: null,
                        price: '10.00',
                        price_set: {
                          presentment_money: {
                            amount: '10.00',
                            currency_code: 'USD',
                          },
                          shop_money: {
                            amount: '10.00',
                            currency_code: 'USD',
                          },
                        },
                        requested_fulfillment_service_id: null,
                        source: 'shopify',
                        tax_lines: [],
                        title: 'Generic Shipping',
                      },
                    ],
                    source_identifier: null,
                    source_name: 'web',
                    source_url: null,
                    subtotal_price: '388.00',
                    subtotal_price_set: {
                      presentment_money: {
                        amount: '388.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '388.00',
                        currency_code: 'USD',
                      },
                    },
                    tags: 'tag1, tag2',
                    tax_exempt: false,
                    tax_lines: [],
                    taxes_included: false,
                    test: true,
                    token: '123456abcd',
                    total_discounts: '20.00',
                    total_discounts_set: {
                      presentment_money: {
                        amount: '20.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '20.00',
                        currency_code: 'USD',
                      },
                    },
                    total_line_items_price: '398.00',
                    total_line_items_price_set: {
                      presentment_money: {
                        amount: '398.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '398.00',
                        currency_code: 'USD',
                      },
                    },
                    total_outstanding: '398.00',
                    total_price: '388.00',
                    total_price_set: {
                      presentment_money: {
                        amount: '388.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '388.00',
                        currency_code: 'USD',
                      },
                    },
                    total_shipping_price_set: {
                      presentment_money: {
                        amount: '10.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '10.00',
                        currency_code: 'USD',
                      },
                    },
                    total_tax: '0.00',
                    total_tax_set: {
                      presentment_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                      shop_money: {
                        amount: '0.00',
                        currency_code: 'USD',
                      },
                    },
                    total_tip_received: '0.00',
                    total_weight: 0,
                    updated_at: '2021-12-31T19:00:00-05:00',
                    user_id: null,
                  },
                  traits: {
                    address: {
                      address1: '123 Elm St.',
                      address2: null,
                      city: 'Ottawa',
                      company: null,
                      country: 'Canada',
                      country_code: 'CA',
                      country_name: 'Canada',
                      customer_id: 115310627314723950,
                      default: true,
                      first_name: null,
                      id: 715243470612851200,
                      last_name: null,
                      name: '',
                      phone: '123-123-1234',
                      province: 'Ontario',
                      province_code: 'ON',
                      zip: 'K2H7A8',
                    },
                    adminGraphqlApiId: 'gid://shopify/Customer/115310627314723954',
                    billingAddress: {
                      address1: '123 Shipping Street',
                      address2: null,
                      city: 'Shippington',
                      company: 'Shipping Company',
                      country: 'United States',
                      country_code: 'US',
                      first_name: 'Steve',
                      last_name: 'Shipper',
                      latitude: null,
                      longitude: null,
                      name: 'Steve Shipper',
                      phone: '555-555-SHIP',
                      province: 'Kentucky',
                      province_code: 'KY',
                      zip: '40003',
                    },
                    currency: 'USD',
                    email: 'john@example.com',
                    firstName: 'John',
                    lastName: 'Smith',
                    shippingAddress: {
                      address1: '123 Shipping Street',
                      address2: null,
                      city: 'Shippington',
                      company: 'Shipping Company',
                      country: 'United States',
                      country_code: 'US',
                      first_name: 'Steve',
                      last_name: 'Shipper',
                      latitude: null,
                      longitude: null,
                      name: 'Steve Shipper',
                      phone: '555-555-SHIP',
                      province: 'Kentucky',
                      province_code: 'KY',
                      zip: '40003',
                    },
                    state: 'disabled',
                    tags: '',
                    taxExempt: false,
                    taxExemptions: [],
                    verifiedEmail: true,
                  },
                  type: 'track',
                  anonymousId: '5d3e2cb6-4011-5c9c-b7ee-11bc1e905097',
                  userId: '115310627314723950',
                },
              ],
            },
          },
        ],
      },
    },
    mockFns,
  },
];

export const data = [
  ...serverSideEventsScenariosForLegacyApp,
  // ...checkoutEventsTestScenarios,
  // ...genericTrackTestScenarios,
  // ...pixelCheckoutEventsTestScenarios,
  // ...pixelCheckoutStepsScenarios,
  // ...pixelEventsTestScenarios,
  ...userTestScenarios,
  ...newpixelCheckoutEventsTestScenarios,
  ...newpixelCheckoutStepsScenarios,
  ...newpixelEventsTestScenarios,
  ...newWebhookcheckoutEventsTestScenarios,
  ...newWebhookOrderEventsTestScenarios,
];
