message:
  supportedMessageTypes:
    - screen
    - track
  default:
    transformation:
      mapperPath: ./mappings/default.yaml
      postMapper:
        name: processExtraPayloadParams
      response:
        endpoint: https://control.kochava.com/track/json
        userId: '{{ message.anonymousId }}'
        format: JSON
        method: POST
        headers: {}
