import { FEATURES, MODULES } from '../../../../../src/v0/util/tags';

export const data = [
  {
    name: 'pardot',
    description: 'Test 0',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: {
          input: [
            {
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
              metadata: {
                jobId: 1,
                secret: {
                  access_token: 'myToken',
                  refresh_token: 'myRefreshToken',
                },
              },
              message: {
                type: 'identify',
                event: 'navigated user',
                sentAt: '2021-09-08T11:10:45.466Z',
                userId: 'user12345',
                channel: 'web',
                context: {
                  os: {
                    name: '',
                    version: '',
                  },
                  app: {
                    name: 'RudderLabs JavaScript SDK',
                    build: '1.0.0',
                    version: '1.1.18',
                    namespace: 'com.rudderlabs.javascript',
                  },
                  page: {
                    url: 'http://127.0.0.1:5500/index.html',
                    path: '/index.html',
                    title: 'Document',
                    search: '',
                    tab_url: 'http://127.0.0.1:5500/index.html',
                    referrer: '$direct',
                    initial_referrer: '$direct',
                    referring_domain: '',
                    initial_referring_domain: '',
                  },
                  locale: 'en-GB',
                  screen: {
                    width: 1536,
                    height: 960,
                    density: 2,
                    innerWidth: 1536,
                    innerHeight: 776,
                  },
                  traits: {},
                  library: {
                    name: 'RudderLabs JavaScript SDK',
                    version: '1.1.18',
                  },
                  campaign: {},
                  userAgent:
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36',
                  externalId: [
                    {
                      type: 'pardotId',
                      id: 123435,
                    },
                  ],
                },
                rudderId: 'fa2994a5-2a81-45fd-9919-fcf5596ad380',
                messageId: 'e2d1a383-d9a2-4e03-a9dc-131d153c4d95',
                timestamp: '2021-11-15T14:06:42.497+05:30',
                properties: {},
                receivedAt: '2021-11-15T14:06:42.497+05:30',
                request_ip: '[::1]',
                anonymousId: 'd8b2ed61-7fa5-4ef8-bd92-6a506157c0cf',
                integrations: {
                  All: true,
                },
                originalTimestamp: '2021-09-08T11:10:45.466Z',
                traits: {
                  email: 'Roger12@waltair.io',
                  active_seats: 4,
                  firstName: 'Roger12',
                  lastName: 'Federer12',
                  website: 'https://rudderstack.com',
                  score: 14,
                },
              },
            },
            {
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
              metadata: {
                jobId: 2,
                secret: {
                  access_token: 'myToken',
                  refresh_token: 'myRefreshToken',
                },
              },
              message: {
                type: 'identify',
                event: 'insert product',
                sentAt: '2021-09-08T11:10:45.466Z',
                userId: 'user12345',
                channel: 'web',
                context: {
                  os: {
                    name: '',
                    version: '',
                  },
                  app: {
                    name: 'RudderLabs JavaScript SDK',
                    build: '1.0.0',
                    version: '1.1.18',
                    namespace: 'com.rudderlabs.javascript',
                  },
                  page: {
                    url: 'http://127.0.0.1:5500/index.html',
                    path: '/index.html',
                    title: 'Document',
                    search: '',
                    tab_url: 'http://127.0.0.1:5500/index.html',
                    referrer: '$direct',
                    initial_referrer: '$direct',
                    referring_domain: '',
                    initial_referring_domain: '',
                  },
                  locale: 'en-GB',
                  screen: {
                    width: 1536,
                    height: 960,
                    density: 2,
                    innerWidth: 1536,
                    innerHeight: 776,
                  },
                  traits: {},
                  library: {
                    name: 'RudderLabs JavaScript SDK',
                    version: '1.1.18',
                  },
                  campaign: {},
                  userAgent:
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36',
                },
                rudderId: 'fa2994a5-2a81-45fd-9919-fcf5596ad380',
                messageId: 'e2d1a383-d9a2-4e03-a9dc-131d153c4d95',
                timestamp: '2021-11-15T14:06:42.497+05:30',
                properties: {},
                receivedAt: '2021-11-15T14:06:42.497+05:30',
                request_ip: '[::1]',
                anonymousId: 'd8b2ed61-7fa5-4ef8-bd92-6a506157c0cf',
                integrations: {
                  All: true,
                },
                originalTimestamp: '2021-09-08T11:10:45.466Z',
                traits: {
                  email: 'Roger_12@waltair.io',
                  active_seats: 4,
                  firstName: 'Roger_12',
                  lastName: 'Federer_12',
                  website: 'https://rudderstack.com',
                  score: 14,
                },
              },
            },
            {
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
              metadata: {
                jobId: 3,
                secret: {
                  access_token: 'myToken',
                  refresh_token: 'myRefreshToken',
                },
              },
              message: {
                type: 'identify',
                event: 'insert product',
                sentAt: '2021-09-08T11:10:45.466Z',
                userId: 'user12345',
                channel: 'web',
                context: {
                  os: {
                    name: '',
                    version: '',
                  },
                  app: {
                    name: 'RudderLabs JavaScript SDK',
                    build: '1.0.0',
                    version: '1.1.18',
                    namespace: 'com.rudderlabs.javascript',
                  },
                  page: {
                    url: 'http://127.0.0.1:5500/index.html',
                    path: '/index.html',
                    title: 'Document',
                    search: '',
                    tab_url: 'http://127.0.0.1:5500/index.html',
                    referrer: '$direct',
                    initial_referrer: '$direct',
                    referring_domain: '',
                    initial_referring_domain: '',
                  },
                  locale: 'en-GB',
                  screen: {
                    width: 1536,
                    height: 960,
                    density: 2,
                    innerWidth: 1536,
                    innerHeight: 776,
                  },
                  traits: {},
                  library: {
                    name: 'RudderLabs JavaScript SDK',
                    version: '1.1.18',
                  },
                  campaign: {},
                  userAgent:
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36',
                  externalId: [
                    {
                      type: 'crmfid',
                      id: '00Q6r000002LKhTPVR',
                    },
                  ],
                },
                rudderId: 'fa2994a5-2a81-45fd-9919-fcf5596ad380',
                messageId: 'e2d1a383-d9a2-4e03-a9dc-131d153c4d95',
                timestamp: '2021-11-15T14:06:42.497+05:30',
                properties: {},
                receivedAt: '2021-11-15T14:06:42.497+05:30',
                request_ip: '[::1]',
                anonymousId: 'd8b2ed61-7fa5-4ef8-bd92-6a506157c0cf',
                integrations: {
                  All: true,
                },
                originalTimestamp: '2021-09-08T11:10:45.466Z',
                traits: {
                  email: 'nick_kyrgios@waltair.io',
                  active_seats: 4,
                  firstName: 'Nick',
                  lastName: 'Kyrgios',
                  website: 'https://rudderstack.com',
                  score: 12,
                },
              },
            },
            {
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
              metadata: {
                jobId: 4,
                secret: {
                  access_token: 'myExpiredToken',
                  refresh_token: 'myRefreshToken',
                },
              },
              message: {
                type: 'identify',
                event: 'navigated user',
                sentAt: '2021-09-08T11:10:45.466Z',
                userId: 'user12345',
                channel: 'web',
                context: {
                  os: {
                    name: '',
                    version: '',
                  },
                  app: {
                    name: 'RudderLabs JavaScript SDK',
                    build: '1.0.0',
                    version: '1.1.18',
                    namespace: 'com.rudderlabs.javascript',
                  },
                  page: {
                    url: 'http://127.0.0.1:5500/index.html',
                    path: '/index.html',
                    title: 'Document',
                    search: '',
                    tab_url: 'http://127.0.0.1:5500/index.html',
                    referrer: '$direct',
                    initial_referrer: '$direct',
                    referring_domain: '',
                    initial_referring_domain: '',
                  },
                  locale: 'en-GB',
                  screen: {
                    width: 1536,
                    height: 960,
                    density: 2,
                    innerWidth: 1536,
                    innerHeight: 776,
                  },
                  traits: {},
                  library: {
                    name: 'RudderLabs JavaScript SDK',
                    version: '1.1.18',
                  },
                  campaign: {},
                  userAgent:
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36',
                },
                rudderId: 'fa2994a5-2a81-45fd-9919-fcf5596ad380',
                messageId: 'e2d1a383-d9a2-4e03-a9dc-131d153c4d95',
                timestamp: '2021-11-15T14:06:42.497+05:30',
                properties: {},
                receivedAt: '2021-11-15T14:06:42.497+05:30',
                request_ip: '[::1]',
                anonymousId: 'd8b2ed61-7fa5-4ef8-bd92-6a506157c0cf',
                integrations: {
                  All: true,
                },
                originalTimestamp: '2021-09-08T11:10:45.466Z',
                traits: {
                  email: 'rolex_waltair@mywebsite.io',
                  active_seats: 4,
                  firstName: 'Rolex',
                  lastName: 'Waltair',
                  website: 'https://rudderstack.com',
                  score: 15,
                },
              },
            },
            {
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
              metadata: {
                jobId: 5,
                secret: null,
              },
              message: {
                type: 'identify',
                event: 'navigated user',
                sentAt: '2021-09-08T11:10:45.466Z',
                userId: 'user12345',
                channel: 'web',
                context: {
                  os: {
                    name: '',
                    version: '',
                  },
                  app: {
                    name: 'RudderLabs JavaScript SDK',
                    build: '1.0.0',
                    version: '1.1.18',
                    namespace: 'com.rudderlabs.javascript',
                  },
                  page: {
                    url: 'http://127.0.0.1:5500/index.html',
                    path: '/index.html',
                    title: 'Document',
                    search: '',
                    tab_url: 'http://127.0.0.1:5500/index.html',
                    referrer: '$direct',
                    initial_referrer: '$direct',
                    referring_domain: '',
                    initial_referring_domain: '',
                  },
                  locale: 'en-GB',
                  screen: {
                    width: 1536,
                    height: 960,
                    density: 2,
                    innerWidth: 1536,
                    innerHeight: 776,
                  },
                  traits: {},
                  library: {
                    name: 'RudderLabs JavaScript SDK',
                    version: '1.1.18',
                  },
                  campaign: {},
                  userAgent:
                    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36',
                },
                rudderId: 'fa2994a5-2a81-45fd-9919-fcf5596ad380',
                messageId: 'e2d1a383-d9a2-4e03-a9dc-131d153c4d95',
                timestamp: '2021-11-15T14:06:42.497+05:30',
                properties: {},
                receivedAt: '2021-11-15T14:06:42.497+05:30',
                request_ip: '[::1]',
                anonymousId: 'd8b2ed61-7fa5-4ef8-bd92-6a506157c0cf',
                integrations: {
                  All: true,
                },
                originalTimestamp: '2021-09-08T11:10:45.466Z',
                traits: {
                  email: 'rolex_waltair@mywebsite.io',
                  active_seats: 4,
                  firstName: 'Rolex',
                  lastName: 'Waltair',
                  website: 'https://rudderstack.com',
                  score: 15,
                },
              },
            },
          ],
          destType: 'pardot',
        },
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: {
                version: '1',
                type: 'REST',
                method: 'POST',
                endpoint: 'https://pi.pardot.com/api/prospect/version/4/do/upsert/id/123435',
                headers: {
                  Authorization: 'Bearer myToken',
                  'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
                },
                params: {},
                body: {
                  JSON: {},
                  JSON_ARRAY: {},
                  XML: {},
                  FORM: {
                    first_name: 'Roger12',
                    last_name: 'Federer12',
                    website: 'https://rudderstack.com',
                    score: 14,
                    campaign_id: 42213,
                  },
                },
                files: {},
              },
              metadata: [
                {
                  jobId: 1,
                  secret: {
                    access_token: 'myToken',
                    refresh_token: 'myRefreshToken',
                  },
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
            },
            {
              batchedRequest: {
                version: '1',
                type: 'REST',
                method: 'POST',
                endpoint:
                  'https://pi.pardot.com/api/prospect/version/4/do/upsert/email/Roger_12@waltair.io',
                headers: {
                  Authorization: 'Bearer myToken',
                  'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
                },
                params: {},
                body: {
                  JSON: {},
                  JSON_ARRAY: {},
                  XML: {},
                  FORM: {
                    first_name: 'Roger_12',
                    last_name: 'Federer_12',
                    website: 'https://rudderstack.com',
                    score: 14,
                    campaign_id: 42213,
                  },
                },
                files: {},
              },
              metadata: [
                {
                  jobId: 2,
                  secret: {
                    access_token: 'myToken',
                    refresh_token: 'myRefreshToken',
                  },
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
            },
            {
              batchedRequest: {
                version: '1',
                type: 'REST',
                method: 'POST',
                endpoint:
                  'https://pi.pardot.com/api/prospect/version/4/do/upsert/fid/00Q6r000002LKhTPVR',
                headers: {
                  Authorization: 'Bearer myToken',
                  'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
                },
                params: {},
                body: {
                  JSON: {},
                  JSON_ARRAY: {},
                  XML: {},
                  FORM: {
                    first_name: 'Nick',
                    last_name: 'Kyrgios',
                    website: 'https://rudderstack.com',
                    score: 12,
                    campaign_id: 42213,
                  },
                },
                files: {},
              },
              metadata: [
                {
                  jobId: 3,
                  secret: {
                    access_token: 'myToken',
                    refresh_token: 'myRefreshToken',
                  },
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
            },
            {
              batchedRequest: {
                version: '1',
                type: 'REST',
                method: 'POST',
                endpoint:
                  'https://pi.pardot.com/api/prospect/version/4/do/upsert/email/rolex_waltair@mywebsite.io',
                headers: {
                  Authorization: 'Bearer myExpiredToken',
                  'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
                },
                params: {},
                body: {
                  JSON: {},
                  JSON_ARRAY: {},
                  XML: {},
                  FORM: {
                    first_name: 'Rolex',
                    last_name: 'Waltair',
                    website: 'https://rudderstack.com',
                    score: 15,
                    campaign_id: 42213,
                  },
                },
                files: {},
              },
              metadata: [
                {
                  jobId: 4,
                  secret: {
                    access_token: 'myExpiredToken',
                    refresh_token: 'myRefreshToken',
                  },
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
            },
            {
              destination: {
                Config: {
                  rudderAccountId: '1z8LpaSAuFR9TPWL6fECZfjmRa-',
                  businessUnitId: '0Uv2v000000k9tHCAQ',
                  campaignId: 42213,
                  authStatus: 'active',
                  eventDelivery: true,
                  eventDeliveryTS: 1636965406397,
                },
                DestinationDefinition: {
                  name: 'PARDOT',
                  displayName: 'Pardot',
                  config: {
                    auth: {
                      type: 'OAuth',
                    },
                    transformAt: 'router',
                    transformAtV1: 'router',
                    saveDestinationResponse: true,
                    includeKeys: [],
                    excludeKeys: [],
                    supportedSourceTypes: [
                      'android',
                      'ios',
                      'web',
                      'unity',
                      'amp',
                      'cloud',
                      'warehouse',
                      'reactnative',
                      'flutter',
                      'cordova',
                    ],
                    destConfig: {
                      defaultConfig: ['rudderAccountId', 'businessUnitId', 'campaignId'],
                    },
                    secretKeys: ['businessUnitId'],
                  },
                },
                Enabled: true,
                ID: '1WXjIHpu7ETXgjfiGPW3kCUgZFR',
                Name: 'test destination',
                Transformations: [],
              },
              metadata: [
                {
                  jobId: 5,
                  secret: null,
                },
              ],
              batched: false,
              statusCode: 500,
              error: 'OAuth - access token not found',
              statTags: {
                destType: 'PARDOT',
                feature: 'router',
                implementation: 'native',
                errorCategory: 'platform',
                module: 'destination',
                errorType: 'oAuthSecret',
              },
            },
          ],
        },
      },
    },
  },
  {
    name: 'pardot',
    description: 'Test proxy - 0',
    feature: FEATURES.DATA_DELIVERY,
    module: MODULES.DESTINATION,
    version: 'v0',
    input: {
      request: {
        body: {
          version: '1',
          type: 'REST',
          method: 'POST',
          endpoint: 'https://pi.pardot.com/api/prospect/version/4/do/upsert/id/123435',
          headers: {
            Authorization: 'Bearer myToken',
            'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
          },
          body: {
            JSON: {},
            JSON_ARRAY: {},
            XML: {},
            FORM: {
              first_name: 'Roger12',
              last_name: 'Federer12',
              website: 'https://rudderstack.com',
              score: 14,
              campaign_id: 42213,
            },
          },
          files: {},
          params: {
            destination: 'pardot',
          },
        },
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: {
            message: 'Request Processed Successfully',
            status: 200,
            destinationResponse: {
              response: {
                '@attributes': {
                  stat: 'ok',
                  version: 1,
                },
                prospect: {
                  id: 123435,
                  campaign_id: 42213,
                  salutation: null,
                  first_name: 'Roger12',
                  last_name: 'Federer12',
                  email: 'Roger12@waltair.io',
                  password: null,
                  company: null,
                  website: 'https://rudderstack.com',
                  job_title: null,
                  department: null,
                  country: 'AU',
                  address_one: null,
                  address_two: null,
                  city: null,
                  state: null,
                  territory: null,
                  zip: null,
                  phone: null,
                  fax: null,
                  source: null,
                  annual_revenue: null,
                  employees: null,
                  industry: null,
                  years_in_business: null,
                  comments: null,
                  notes: null,
                  score: 14,
                  grade: null,
                  last_activity_at: null,
                  recent_interaction: 'Never active.',
                  crm_lead_fid: null,
                  crm_contact_fid: null,
                  crm_owner_fid: '00G2v000004WYXaEAO',
                  crm_account_fid: null,
                  salesforce_fid: null,
                  crm_last_sync: null,
                  crm_url: null,
                  is_do_not_email: null,
                  is_do_not_call: null,
                  opted_out: null,
                  is_reviewed: 1,
                  is_starred: null,
                  created_at: '2022-01-21 18:21:46',
                  updated_at: '2022-01-21 18:48:41',
                  campaign: {
                    id: 42113,
                    name: 'Test',
                    crm_fid: '7012y000000MNOCLL4',
                  },
                  assigned_to: {
                    user: {
                      id: 38443703,
                      email: 'test_rudderstack@testcompany.com',
                      first_name: 'Rudderstack',
                      last_name: 'User',
                      job_title: null,
                      role: 'Administrator',
                      account: 489853,
                      created_at: '2021-02-26 06:25:17',
                      updated_at: '2021-02-26 06:25:17',
                    },
                  },
                  Are_you_shipping_large_fragile_or_bulky_items: false,
                  Calendly: false,
                  Country_Code: 'AU',
                  Currency: 'AUD',
                  Inventory_or_Warehouse_Management_System: false,
                  Lead_Status: 'New',
                  Marketing_Stage: 'SAL',
                  Record_Type_ID: 'TestCompany Lead',
                  profile: {
                    id: 304,
                    name: 'Default',
                    profile_criteria: [
                      {
                        id: 1500,
                        name: 'Shipping Volume',
                        matches: 'Unknown',
                      },
                      {
                        id: 1502,
                        name: 'Industry',
                        matches: 'Unknown',
                      },
                      {
                        id: 1506,
                        name: 'Job Title',
                        matches: 'Unknown',
                      },
                      {
                        id: 1508,
                        name: 'Department',
                        matches: 'Unknown',
                      },
                    ],
                  },
                  visitors: null,
                  visitor_activities: null,
                  lists: null,
                },
              },
              status: 200,
            },
          },
        },
      },
    },
  },
  {
    name: 'pardot',
    description: 'Test proxy - 1',
    feature: FEATURES.DATA_DELIVERY,
    module: MODULES.DESTINATION,
    version: 'v0',
    input: {
      request: {
        body: {
          version: '1',
          type: 'REST',
          method: 'POST',
          endpoint:
            'https://pi.pardot.com/api/prospect/version/4/do/upsert/email/Roger_12@waltair.io',
          headers: {
            Authorization: 'Bearer myToken',
            'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
          },
          body: {
            JSON: {},
            JSON_ARRAY: {},
            XML: {},
            FORM: {
              first_name: 'Roger_12',
              last_name: 'Federer_12',
              website: 'https://rudderstack.com',
              score: 14,
              campaign_id: 42213,
            },
          },
          files: {},
          params: {
            destination: 'pardot',
          },
        },
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: {
            message: 'Request Processed Successfully',
            status: 201,
            destinationResponse: {
              response: {
                '@attributes': {
                  stat: 'ok',
                  version: 1,
                },
                prospect: {
                  id: 123435,
                  campaign_id: 42213,
                  salutation: null,
                  first_name: 'Roger_12',
                  last_name: 'Federer_12',
                  email: 'Roger_12@waltair.io',
                  password: null,
                  company: null,
                  website: 'https://rudderstack.com',
                  job_title: null,
                  department: null,
                  country: 'AU',
                  address_one: null,
                  address_two: null,
                  city: null,
                  state: null,
                  territory: null,
                  zip: null,
                  phone: null,
                  fax: null,
                  source: null,
                  annual_revenue: null,
                  employees: null,
                  industry: null,
                  years_in_business: null,
                  comments: null,
                  notes: null,
                  score: 14,
                  grade: null,
                  last_activity_at: null,
                  recent_interaction: 'Never active.',
                  crm_lead_fid: null,
                  crm_contact_fid: null,
                  crm_owner_fid: '00G2v000004WYXaEAO',
                  crm_account_fid: null,
                  salesforce_fid: null,
                  crm_last_sync: null,
                  crm_url: null,
                  is_do_not_email: null,
                  is_do_not_call: null,
                  opted_out: null,
                  is_reviewed: 1,
                  is_starred: null,
                  created_at: '2022-01-21 18:21:46',
                  updated_at: '2022-01-21 18:48:41',
                  campaign: {
                    id: 42113,
                    name: 'Test',
                    crm_fid: '7012y000000MNOCLL4',
                  },
                  assigned_to: {
                    user: {
                      id: 38443703,
                      email: 'test_rudderstack@testcompany.com',
                      first_name: 'Rudderstack',
                      last_name: 'User',
                      job_title: null,
                      role: 'Administrator',
                      account: 489853,
                      created_at: '2021-02-26 06:25:17',
                      updated_at: '2021-02-26 06:25:17',
                    },
                  },
                  Are_you_shipping_large_fragile_or_bulky_items: false,
                  Calendly: false,
                  Country_Code: 'AU',
                  Currency: 'AUD',
                  Inventory_or_Warehouse_Management_System: false,
                  Lead_Status: 'New',
                  Marketing_Stage: 'SAL',
                  Record_Type_ID: 'TestCompany Lead',
                  profile: {
                    id: 304,
                    name: 'Default',
                    profile_criteria: [
                      {
                        id: 1500,
                        name: 'Shipping Volume',
                        matches: 'Unknown',
                      },
                      {
                        id: 1502,
                        name: 'Industry',
                        matches: 'Unknown',
                      },
                      {
                        id: 1506,
                        name: 'Job Title',
                        matches: 'Unknown',
                      },
                      {
                        id: 1508,
                        name: 'Department',
                        matches: 'Unknown',
                      },
                    ],
                  },
                  visitors: null,
                  visitor_activities: null,
                  lists: null,
                },
              },
              status: 201,
            },
          },
        },
      },
    },
  },
  {
    name: 'pardot',
    description: 'Test proxy - 2',
    feature: FEATURES.DATA_DELIVERY,
    module: MODULES.DESTINATION,
    version: 'v0',
    input: {
      request: {
        body: {
          version: '1',
          type: 'REST',
          method: 'POST',
          endpoint: 'https://pi.pardot.com/api/prospect/version/4/do/upsert/fid/00Q6r000002LKhTPVR',
          headers: {
            Authorization: 'Bearer myToken',
            'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
          },
          body: {
            JSON: {},
            JSON_ARRAY: {},
            XML: {},
            FORM: {
              first_name: 'Nick',
              last_name: 'Kyrgios',
              website: 'https://rudderstack.com',
              score: 12,
              campaign_id: 42213,
            },
          },
          files: {},
          params: {
            destination: 'pardot',
          },
        },
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: {
            message: 'Request Processed Successfully',
            status: 200,
            destinationResponse: {
              response: {
                '@attributes': {
                  stat: 'ok',
                  version: 1,
                },
                prospect: {
                  id: 123435,
                  campaign_id: 42213,
                  salutation: null,
                  first_name: 'Roger_12',
                  last_name: 'Federer_12',
                  email: 'Roger_12@federer.io',
                  password: null,
                  company: null,
                  website: 'https://rudderstack.com',
                  job_title: null,
                  department: null,
                  country: 'AU',
                  address_one: null,
                  address_two: null,
                  city: null,
                  state: null,
                  territory: null,
                  zip: null,
                  phone: null,
                  fax: null,
                  source: null,
                  annual_revenue: null,
                  employees: null,
                  industry: null,
                  years_in_business: null,
                  comments: null,
                  notes: null,
                  score: 14,
                  grade: null,
                  last_activity_at: null,
                  recent_interaction: 'Never active.',
                  crm_lead_fid: '00Q6r000002LKhTPVR',
                  crm_contact_fid: null,
                  crm_owner_fid: '00G2v000004WYXaEAO',
                  crm_account_fid: null,
                  salesforce_fid: '00Q6r000002LKhTPVR',
                  crm_last_sync: '2022-01-21 18:47:37',
                  crm_url: 'https://testcompany.my.salesforce.com/00Q6r000002LKhTPVR',
                  is_do_not_email: null,
                  is_do_not_call: null,
                  opted_out: null,
                  is_reviewed: 1,
                  is_starred: null,
                  created_at: '2022-01-21 18:21:46',
                  updated_at: '2022-01-21 18:48:41',
                  campaign: {
                    id: 42113,
                    name: 'Test',
                    crm_fid: '7012y000000MNOCLL4',
                  },
                  assigned_to: {
                    user: {
                      id: 38443703,
                      email: 'test_rudderstack@testcompany.com',
                      first_name: 'Rudderstack',
                      last_name: 'User',
                      job_title: null,
                      role: 'Administrator',
                      account: 489853,
                      created_at: '2021-02-26 06:25:17',
                      updated_at: '2021-02-26 06:25:17',
                    },
                  },
                  Are_you_shipping_large_fragile_or_bulky_items: false,
                  Calendly: false,
                  Country_Code: 'AU',
                  Currency: 'AUD',
                  Inventory_or_Warehouse_Management_System: false,
                  Lead_Status: 'New',
                  Marketing_Stage: 'SAL',
                  Record_Type_ID: 'TestCompany Lead',
                  profile: {
                    id: 304,
                    name: 'Default',
                    profile_criteria: [
                      {
                        id: 1500,
                        name: 'Shipping Volume',
                        matches: 'Unknown',
                      },
                      {
                        id: 1502,
                        name: 'Industry',
                        matches: 'Unknown',
                      },
                      {
                        id: 1506,
                        name: 'Job Title',
                        matches: 'Unknown',
                      },
                      {
                        id: 1508,
                        name: 'Department',
                        matches: 'Unknown',
                      },
                    ],
                  },
                  visitors: null,
                  visitor_activities: null,
                  lists: null,
                },
              },
              status: 200,
            },
          },
        },
      },
    },
  },
  {
    name: 'pardot',
    description: 'Test proxy - 3',
    feature: FEATURES.DATA_DELIVERY,
    module: MODULES.DESTINATION,
    version: 'v0',
    input: {
      request: {
        body: {
          version: '1',
          type: 'REST',
          method: 'POST',
          endpoint:
            'https://pi.pardot.com/api/prospect/version/4/do/upsert/email/rolex_waltair@mywebsite.io',
          headers: {
            Authorization: 'Bearer myExpiredToken',
            'Pardot-Business-Unit-Id': '0Uv2v000000k9tHCAQ',
          },
          body: {
            JSON: {},
            JSON_ARRAY: {},
            XML: {},
            FORM: {
              first_name: 'Rolex',
              last_name: 'Waltair',
              website: 'https://rudderstack.com',
              score: 15,
              campaign_id: 42213,
            },
          },
          files: {},
          params: {
            destination: 'pardot',
          },
        },
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 500,
        body: {
          output: {
            message:
              'access_token is invalid, unknown, or malformed: Inactive token during Pardot response transformation',
            status: 500,
            authErrorCategory: 'REFRESH_TOKEN',
            destinationResponse: {
              '@attributes': {
                stat: 'fail',
                version: 1,
                err_code: 184,
              },
              err: 'access_token is invalid, unknown, or malformed: Inactive token',
            },
            statTags: {
              destType: 'PARDOT',
              errorCategory: 'network',
              destinationId: 'Non-determininable',
              workspaceId: 'Non-determininable',
              errorType: 'retryable',
              feature: 'dataDelivery',
              implementation: 'native',
              module: 'destination',
            },
          },
        },
      },
    },
  },
];
