version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - docker login --username rudderlabs --password ${{ secrets.DOCKERHUB_PROD_TOKEN }}
  build:
    commands:
      - VERSION=$(head -1 .version)
      - ls
      - echo build Docker image on `date`
      - >
        docker build 
        --build-arg version=${VERSION} 
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        -t rudderlabs/rudder-transformer:$VERSION 
        -f Dockerfile .
      - docker run rudderlabs/rudder-transformer:$VERSION npm run test
      - echo $?
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to docker hub...
      - docker push rudderlabs/rudder-transformer:$VERSION
artifacts:
  files:
    - '**/*'
