version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - 'echo "${DOCKERHUB_PASSWORD}" | docker login --username rudderlabs --password-stdin'
      - wget https://github.com/docker/buildx/releases/download/v0.10.2/buildx-v0.10.2.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.10.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
      - docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
  pre_build:
    commands:
      - docker login --username rudderlabs --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - VERSION=saas-dev
      - ls
      - echo build Docker image on `date`
      - >
        docker build 
        --build-arg version=${VERSION} 
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        -t rudderlabs/develop-rudder-transformer:$VERSION 
        -t rudderstack/develop-rudder-transformer:$VERSION 
        -f Dockerfile .
      - docker run rudderstack/develop-rudder-transformer:$VERSION npm run test
      - echo $?
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to docker hub...

      # creates a docker builder instance to build multi-platform docker images
      - docker buildx create --use

      # builds and pushes multi-platform docker images to docker registry
      - >
        docker buildx build 
        --build-arg version=${VERSION}
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        --platform=linux/amd64,linux/arm64 
        -t rudderlabs/develop-rudder-transformer:$VERSION 
        -t rudderstack/develop-rudder-transformer:$VERSION 
        -f Dockerfile 
        --push .
artifacts:
  files:
    - '**/*'
