version: 0.2

env:
  parameter-store:
    dockerhub_passwd: '/prod/codebuild/dockerhub-password'

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - docker login --username rudderlabs --password $dockerhub_passwd
  build:
    commands:
      - VERSION=saas-dev
      - ls
      - echo build Docker image on `date`
      - >
        docker build 
        --build-arg version=${VERSION} 
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        -t rudderlabs/develop-rudder-transformer:$VERSION 
        -t rudderstack/develop-rudder-transformer:$VERSION 
        -f Dockerfile .
      - docker run rudderstack/develop-rudder-transformer:$VERSION npm run test
      - echo $?
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to docker hub...

      # creates a docker builder instance to build multi-platform docker images
      - docker buildx create --use

      # builds and pushes multi-platform docker images to docker registry
      - >
        docker buildx build 
        --build-arg version=${VERSION}
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        --platform=linux/amd64,linux/arm64 
        -t rudderlabs/develop-rudder-transformer:$VERSION 
        -t rudderstack/develop-rudder-transformer:$VERSION 
        -f Dockerfile 
        --push .
artifacts:
  files:
    - '**/*'
