version: 0.2
env:
  parameter-store:
    dockerhub_passwd: '/prod/codebuild/dockerhub-password'
    GITHUB_TOKEN: 'build-deploy-pkey'
    MAIL: 'mail-id'
    USER_NAME: 'user-name'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update
      - apt install -y hub
      - 'echo "${DOCKERHUB_PASSWORD}" | docker login --username rudderlabs --password-stdin'
      - wget https://github.com/docker/buildx/releases/download/v0.10.2/buildx-v0.10.2.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.10.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
      - docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
  pre_build:
    commands:
      - docker login --username rudderlabs --password $dockerhub_passwd
  build:
    commands:
      - VERSION="$(date '+%d%m%Y.%H%M%S')"
      - ls
      - >
        docker build 
        --build-arg version=${VERSION} 
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        -t rudderlabs/rudder-transformer:$VERSION 
        -t rudderstack/rudder-transformer:$VERSION 
        -f Dockerfile .
      - docker run rudderstack/rudder-transformer:$VERSION npm run test
      - echo $?
  post_build:
    commands:
      - VERSION="$(date '+%d%m%Y.%H%M%S')"

      # creates a docker builder instance to build multi-platform docker images
      - docker buildx create --use

      # builds and pushes multi-platform docker images to docker registry
      - >
        docker buildx build 
        --build-arg version=${VERSION}
        --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION 
        --platform=linux/amd64,linux/arm64 
        -t rudderlabs/rudder-transformer:latest 
        -t rudderlabs/rudder-transformer:$VERSION 
        -t rudderstack/rudder-transformer:latest 
        -t rudderstack/rudder-transformer:$VERSION 
        -f Dockerfile 
        --push .

      # raise a pull request to update default transformer version
      - git clone https://$GITHUB_TOKEN@github.com/rudderlabs/rudder-devops.git
      - git config --global user.email \"$MAIL\"
      - git config --global user.name \"$USER_NAME\"
      - cd rudder-devops/helm-charts/shared-services/per-az
      - git checkout -b shared-transformer-$VERSION
      - yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
      - yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
      - yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.prod.yaml
      - yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.prod.yaml
      - git add values.blue-release.yaml values.prod.yaml
      - cd ../../config-be-rudder-transformer
      - yq eval -i ".config-be-rudder-transformer.image.tag=\"$VERSION\"" values.prod.yaml
      - yq eval -i ".config-be-user-transformer.image.tag=\"$VERSION\"" values.prod.yaml
      - git add values.prod.yaml
      - git commit -m "changing version for shared transformer"
      - git push -u origin shared-transformer-$VERSION
      - hub pull-request -m "rudder-transformer version change-$VERSION"
artifacts:
  files:
    - '**/*'
