version: 0.2
env:
  parameter-store:
    dockerhub_passwd: "/prod/codebuild/dockerhub-password"
    GITHUB_TOKEN: "build-deploy-pkey"
    MAIL: "mail-id"
    USER_NAME: "user-name"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - apt-get update
      - apt install -y hub
  pre_build:
    commands:
      - docker login --username rudderlabs --password $dockerhub_passwd
  build:
    commands:
      - VERSION="$(date '+%d%m%Y.%H%M%S')"
      - ls
      - docker build --build-arg version=${VERSION} -t rudderlabs/rudder-transformer:$VERSION -f Dockerfile .
      - docker run rudderlabs/rudder-transformer:$VERSION npm run testDestinations
      - docker run rudderlabs/rudder-transformer:$VERSION npm run testVersionedRouter
      - echo $?
  post_build:
    commands:
      - VERSION="$(date '+%d%m%Y.%H%M%S')"

      # creates a docker builder instance to build multi-platform docker images
      - docker buildx create --use

      # builds and pushes multi-platform docker images to docker registry
      - docker buildx build --build-arg version=${VERSION} --platform=linux/amd64,linux/arm64 -t rudderlabs/rudder-transformer:latest -t rudderlabs/rudderstack-transformer:$VERSION -f Dockerfile --push .

      # raise a pull request to update default transformer version
      - git clone https://$GITHUB_TOKEN@github.com/rudderlabs/rudder-devops.git
      - git config --global user.email \"$MAIL\"
      - git config --global user.name \"$USER_NAME\"
      - cd rudder-devops/helm-charts/shared-services/per-az
      - git checkout -b shared-transformer-\"$VERSION\"
      - yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
      - git add values.blue-release.yaml
      - git commit -m "changing version for shared transformer"
      - git push -u origin shared-transformer-\"$VERSION\"
      - hub pull-request -m "rudder-transformer version change-\"$VERSION\" "
artifacts:
  files:
    - "**/*"
