version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - docker login --username rudderlabs --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - VERSION=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | sed 's/refs\/heads\///g' | tr "/" .)
      - ls
      - echo build Docker image on `date`
      - docker build --build-arg version=${VERSION} -t rudderlabs/develop-rudder-transformer:$VERSION -f Dockerfile .
      - docker run rudderlabs/develop-rudder-transformer:$VERSION npm run testDestinations
      - docker run rudderlabs/develop-rudder-transformer:$VERSION npm run testVersionedRouter
      - echo $?
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to docker hub...
      - docker push rudderlabs/develop-rudder-transformer:$VERSION
artifacts:
  files:
    - "**/*"
