# syntax=docker/dockerfile:1.4
FROM node:14.20-alpine3.15

RUN apk update
RUN apk upgrade

RUN apk add --no-cache tini python2

# installing specific make version based on your previous configuration
RUN apk add make=4.2.1-r2 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/main

# installing specific gcc version based on your previous configuration
RUN apk add g++=9.3.0-r0 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/main

# Create app directory
WORKDIR /app

COPY package*.json ./
COPY build.js ./

RUN npm install --unsafe-perm=true

COPY . .

HEALTHCHECK --interval=1s --timeout=30s --retries=30 \
    CMD  wget --no-verbose --tries=5 --spider http://localhost:9090/health || exit 1

ENTRYPOINT ["/sbin/tini", "--"]
CMD [ "npm", "start" ]
