export const networkCallsData = [
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=9830311521',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'T',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
            ],
            color: '#607d8b',
            custom_field_data: null,
            display_name: 'Haz matsumi phone 2 (+98 30311521)',
            email: null,
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 30311521',
            full_name: 'Thalmor Bretz',
            id: 90002431001,
            identifier: '+98 30311521',
            is_phone: true,
            is_private: false,
            name: 'Thalmor Bretz',
            phone: '+98 30311521',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=j@d.com',
    },
    httpRes: {
      data: {
        data: [],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=j@d.com',
    },
    httpRes: {
      data: {
        data: [],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=null',
    },
    httpRes: { data: { error: 'Request failed', status: 404 }, status: 200 },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=12345678910',
    },
    httpRes: {
      data: {
        data: [],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=99999666661',
    },
    httpRes: { data: { error: 'Request failed', status: 404 }, status: 200 },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=98765432100',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'T',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
            ],
            color: '#607d8b',
            custom_field_data: null,
            display_name: 'Michael Scott (+98 30311521)',
            email: null,
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 765432100',
            full_name: 'Michael Scott',
            id: 90002431001,
            identifier: '+98 765432100',
            is_phone: true,
            is_private: false,
            name: 'Michael Scott',
            phone: '+98 765432100',
            pivot: null,
            profile: [],
            profile_image: null,
          },
          {
            abbr: 'T',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
            ],
            color: '#607d8b',
            custom_field_data: null,
            display_name: 'Michael G Scott (+98 30311521)',
            email: null,
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 765432100',
            full_name: 'Michael G Scott',
            id: 90002431003,
            identifier: '+98 765432100',
            is_phone: true,
            is_private: false,
            name: 'Michael G Scott',
            phone: '+98 765432100',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=test@outlook.com',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'U',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'email • 5xcyI53Nf7@trengomail.com',
                emailChannel: {
                  add_conversation_to_reply: 1,
                  auto_reply_body:
                    '<p>Dear [name],<br /><br />This is a confirmation that we received your email and registered it as ticket #[ticket_number]. You can always reply to this email if you want to add additional information.<br /><br />Kinds regards,<br /><br />Team Rudder</p>',
                  auto_reply_enabled: 1,
                  auto_reply_subject: null,
                  branding: 1,
                  branding_service_name: 'Rudder',
                  channel_id: 405980,
                  created_at: '2021-05-13 08:47:56',
                  email_theme_id: null,
                  embed_attachments: 1,
                  font_family: null,
                  meta: {
                    selectedFolders: [],
                    syncFolders: [],
                    syncStatus: null,
                    zapier_consent: null,
                  },
                  prepend_ticket_number_to_subject: 0,
                  sender_email: null,
                  sender_email_id: null,
                  sender_name: 'Rudder',
                  sender_name_personal: '[agent.first_name] | Rudder',
                  signature:
                    '<p>Kind regards,<br /><br />[agent.first_name] [agent.last_name]<br />Rudder</p>',
                  spam_setting: 1,
                  split_by_sender: 0,
                  split_by_subject: 1,
                  type: 'TRENGO',
                  updated_at: '2021-05-13 08:47:56',
                },
                id: 405980,
                is_private: false,
                name: 'Email',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'email • 5xcyI53Nf7@trengomail.com',
                title: 'email',
                type: 'EMAIL',
                username: '5xcyI53Nf7',
                users: [],
              },
            ],
            color: '#00bcd4',
            custom_field_data: null,
            display_name: 'test Phone tct (test@outlook.com)',
            email: 'test@outlook.com',
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 303115423',
            full_name: 'test Email',
            id: 97694755,
            identifier: 'test@outlook.com',
            is_phone: true,
            is_private: false,
            name: 'test Email',
            phone: '98303115423',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=test@outlook.com',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'U',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'email • 5xcyI53Nf7@trengomail.com',
                emailChannel: {
                  add_conversation_to_reply: 1,
                  auto_reply_body:
                    '<p>Dear [name],<br /><br />This is a confirmation that we received your email and registered it as ticket #[ticket_number]. You can always reply to this email if you want to add additional information.<br /><br />Kinds regards,<br /><br />Team Rudder</p>',
                  auto_reply_enabled: 1,
                  auto_reply_subject: null,
                  branding: 1,
                  branding_service_name: 'Rudder',
                  channel_id: 405980,
                  created_at: '2021-05-13 08:47:56',
                  email_theme_id: null,
                  embed_attachments: 1,
                  font_family: null,
                  meta: {
                    selectedFolders: [],
                    syncFolders: [],
                    syncStatus: null,
                    zapier_consent: null,
                  },
                  prepend_ticket_number_to_subject: 0,
                  sender_email: null,
                  sender_email_id: null,
                  sender_name: 'Rudder',
                  sender_name_personal: '[agent.first_name] | Rudder',
                  signature:
                    '<p>Kind regards,<br /><br />[agent.first_name] [agent.last_name]<br />Rudder</p>',
                  spam_setting: 1,
                  split_by_sender: 0,
                  split_by_subject: 1,
                  type: 'TRENGO',
                  updated_at: '2021-05-13 08:47:56',
                },
                id: 405980,
                is_private: false,
                name: 'Email',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'email • 5xcyI53Nf7@trengomail.com',
                title: 'email',
                type: 'EMAIL',
                username: '5xcyI53Nf7',
                users: [],
              },
            ],
            color: '#00bcd4',
            custom_field_data: null,
            display_name: 'test Phone tct (test@outlook.com)',
            email: 'test@outlook.com',
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 303115423',
            full_name: 'test Email',
            id: 97694755,
            identifier: 'test@outlook.com',
            is_phone: true,
            is_private: false,
            name: 'test Email',
            phone: '98303115423',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=98765432100',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'T',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
            ],
            color: '#607d8b',
            custom_field_data: null,
            display_name: 'Michael Scott (+98 30311521)',
            email: null,
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 765432100',
            full_name: 'Michael Scott',
            id: 90002431001,
            identifier: '+98 765432100',
            is_phone: true,
            is_private: false,
            name: 'Michael Scott',
            phone: '+98 765432100',
            pivot: null,
            profile: [],
            profile_image: null,
          },
          {
            abbr: 'T',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
            ],
            color: '#607d8b',
            custom_field_data: null,
            display_name: 'Michael G Scott (+98 30311521)',
            email: null,
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 765432100',
            full_name: 'Michael G Scott',
            id: 90002431003,
            identifier: '+98 765432100',
            is_phone: true,
            is_private: false,
            name: 'Michael G Scott',
            phone: '+98 765432100',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=test@outlook.com',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'U',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'email • 5xcyI53Nf7@trengomail.com',
                emailChannel: {
                  add_conversation_to_reply: 1,
                  auto_reply_body:
                    '<p>Dear [name],<br /><br />This is a confirmation that we received your email and registered it as ticket #[ticket_number]. You can always reply to this email if you want to add additional information.<br /><br />Kinds regards,<br /><br />Team Rudder</p>',
                  auto_reply_enabled: 1,
                  auto_reply_subject: null,
                  branding: 1,
                  branding_service_name: 'Rudder',
                  channel_id: 405980,
                  created_at: '2021-05-13 08:47:56',
                  email_theme_id: null,
                  embed_attachments: 1,
                  font_family: null,
                  meta: {
                    selectedFolders: [],
                    syncFolders: [],
                    syncStatus: null,
                    zapier_consent: null,
                  },
                  prepend_ticket_number_to_subject: 0,
                  sender_email: null,
                  sender_email_id: null,
                  sender_name: 'Rudder',
                  sender_name_personal: '[agent.first_name] | Rudder',
                  signature:
                    '<p>Kind regards,<br /><br />[agent.first_name] [agent.last_name]<br />Rudder</p>',
                  spam_setting: 1,
                  split_by_sender: 0,
                  split_by_subject: 1,
                  type: 'TRENGO',
                  updated_at: '2021-05-13 08:47:56',
                },
                id: 405980,
                is_private: false,
                name: 'Email',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'email • 5xcyI53Nf7@trengomail.com',
                title: 'email',
                type: 'EMAIL',
                username: '5xcyI53Nf7',
                users: [],
              },
            ],
            color: '#00bcd4',
            custom_field_data: null,
            display_name: 'test Phone tct (test@outlook.com)',
            email: 'test@outlook.com',
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 303115423',
            full_name: 'test Email',
            id: 97694755,
            identifier: 'test@outlook.com',
            is_phone: true,
            is_private: false,
            name: 'test Email',
            phone: '98303115423',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=test@outlook.com',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'U',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'email • 5xcyI53Nf7@trengomail.com',
                emailChannel: {
                  add_conversation_to_reply: 1,
                  auto_reply_body:
                    '<p>Dear [name],<br /><br />This is a confirmation that we received your email and registered it as ticket #[ticket_number]. You can always reply to this email if you want to add additional information.<br /><br />Kinds regards,<br /><br />Team Rudder</p>',
                  auto_reply_enabled: 1,
                  auto_reply_subject: null,
                  branding: 1,
                  branding_service_name: 'Rudder',
                  channel_id: 405980,
                  created_at: '2021-05-13 08:47:56',
                  email_theme_id: null,
                  embed_attachments: 1,
                  font_family: null,
                  meta: {
                    selectedFolders: [],
                    syncFolders: [],
                    syncStatus: null,
                    zapier_consent: null,
                  },
                  prepend_ticket_number_to_subject: 0,
                  sender_email: null,
                  sender_email_id: null,
                  sender_name: 'Rudder',
                  sender_name_personal: '[agent.first_name] | Rudder',
                  signature:
                    '<p>Kind regards,<br /><br />[agent.first_name] [agent.last_name]<br />Rudder</p>',
                  spam_setting: 1,
                  split_by_sender: 0,
                  split_by_subject: 1,
                  type: 'TRENGO',
                  updated_at: '2021-05-13 08:47:56',
                },
                id: 405980,
                is_private: false,
                name: 'Email',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'email • 5xcyI53Nf7@trengomail.com',
                title: 'email',
                type: 'EMAIL',
                username: '5xcyI53Nf7',
                users: [],
              },
            ],
            color: '#00bcd4',
            custom_field_data: null,
            display_name: 'test Phone tct (test@outlook.com)',
            email: 'test@outlook.com',
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 303115423',
            full_name: 'test Email',
            id: 97694755,
            identifier: 'test@outlook.com',
            is_phone: true,
            is_private: false,
            name: 'test Email',
            phone: '98303115423',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=test@outlook.com',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'U',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'email • 5xcyI53Nf7@trengomail.com',
                emailChannel: {
                  add_conversation_to_reply: 1,
                  auto_reply_body:
                    '<p>Dear [name],<br /><br />This is a confirmation that we received your email and registered it as ticket #[ticket_number]. You can always reply to this email if you want to add additional information.<br /><br />Kinds regards,<br /><br />Team Rudder</p>',
                  auto_reply_enabled: 1,
                  auto_reply_subject: null,
                  branding: 1,
                  branding_service_name: 'Rudder',
                  channel_id: 405980,
                  created_at: '2021-05-13 08:47:56',
                  email_theme_id: null,
                  embed_attachments: 1,
                  font_family: null,
                  meta: {
                    selectedFolders: [],
                    syncFolders: [],
                    syncStatus: null,
                    zapier_consent: null,
                  },
                  prepend_ticket_number_to_subject: 0,
                  sender_email: null,
                  sender_email_id: null,
                  sender_name: 'Rudder',
                  sender_name_personal: '[agent.first_name] | Rudder',
                  signature:
                    '<p>Kind regards,<br /><br />[agent.first_name] [agent.last_name]<br />Rudder</p>',
                  spam_setting: 1,
                  split_by_sender: 0,
                  split_by_subject: 1,
                  type: 'TRENGO',
                  updated_at: '2021-05-13 08:47:56',
                },
                id: 405980,
                is_private: false,
                name: 'Email',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'email • 5xcyI53Nf7@trengomail.com',
                title: 'email',
                type: 'EMAIL',
                username: '5xcyI53Nf7',
                users: [],
              },
            ],
            color: '#00bcd4',
            custom_field_data: null,
            display_name: 'test Phone tct (test@outlook.com)',
            email: 'test@outlook.com',
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 303115423',
            full_name: 'test Email',
            id: 97694755,
            identifier: 'test@outlook.com',
            is_phone: true,
            is_private: false,
            name: 'test Email',
            phone: '98303115423',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=test@outlook.com',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'U',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'email • 5xcyI53Nf7@trengomail.com',
                emailChannel: {
                  add_conversation_to_reply: 1,
                  auto_reply_body:
                    '<p>Dear [name],<br /><br />This is a confirmation that we received your email and registered it as ticket #[ticket_number]. You can always reply to this email if you want to add additional information.<br /><br />Kinds regards,<br /><br />Team Rudder</p>',
                  auto_reply_enabled: 1,
                  auto_reply_subject: null,
                  branding: 1,
                  branding_service_name: 'Rudder',
                  channel_id: 405980,
                  created_at: '2021-05-13 08:47:56',
                  email_theme_id: null,
                  embed_attachments: 1,
                  font_family: null,
                  meta: {
                    selectedFolders: [],
                    syncFolders: [],
                    syncStatus: null,
                    zapier_consent: null,
                  },
                  prepend_ticket_number_to_subject: 0,
                  sender_email: null,
                  sender_email_id: null,
                  sender_name: 'Rudder',
                  sender_name_personal: '[agent.first_name] | Rudder',
                  signature:
                    '<p>Kind regards,<br /><br />[agent.first_name] [agent.last_name]<br />Rudder</p>',
                  spam_setting: 1,
                  split_by_sender: 0,
                  split_by_subject: 1,
                  type: 'TRENGO',
                  updated_at: '2021-05-13 08:47:56',
                },
                id: 405980,
                is_private: false,
                name: 'Email',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'email • 5xcyI53Nf7@trengomail.com',
                title: 'email',
                type: 'EMAIL',
                username: '5xcyI53Nf7',
                users: [],
              },
            ],
            color: '#00bcd4',
            custom_field_data: null,
            display_name: 'test Phone tct (test@outlook.com)',
            email: 'test@outlook.com',
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 303115423',
            full_name: 'test Email',
            id: 97694755,
            identifier: 'test@outlook.com',
            is_phone: true,
            is_private: false,
            name: 'test Email',
            phone: '98303115423',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Bearer trengo_integration_test_api_token',
      },

      method: 'GET',

      url: 'https://app.trengo.com/api/v2/contacts?page=1&term=9830311521',
    },
    httpRes: {
      data: {
        data: [
          {
            abbr: 'T',
            avatar: 'https://app.trengo.com/img/defaultpic.png',
            channels: [
              {
                auto_reply: 'ENABLED',
                business_hour_id: 125020,
                color: null,
                display_name: 'sms • SMS',
                emailChannel: null,
                id: 406005,
                is_private: false,
                name: 'Sms',
                notification_email: null,
                notification_sound: 'chat.mp3',
                password_is_null: false,
                phone: '',
                reassign_reopened_ticket: false,
                reopen_closed_ticket: 1,
                reopen_closed_ticket_time_window_days: '30',
                show_contact_fields: 1,
                show_ticket_fields: 1,
                status: 'ACTIVE',
                text: 'sms • SMS',
                title: 'sms',
                type: 'SMS',
                username: null,
                users: [],
              },
            ],
            color: '#607d8b',
            custom_field_data: null,
            display_name: 'Haz matsumi phone 2 (+98 30311521)',
            email: null,
            formatted_custom_field_data: { 'Customer number': null, Policy: null },
            formatted_phone: '+98 30311521',
            full_name: 'Thalmor Bretz',
            id: 90002431001,
            identifier: '+98 30311521',
            is_phone: true,
            is_private: false,
            name: 'Thalmor Bretz',
            phone: '+98 30311521',
            pivot: null,
            profile: [],
            profile_image: null,
          },
        ],
        links: {
          first: 'https://app.trengo.com/api/v2/contacts?page=1',
          last: null,
          next: null,
          prev: null,
        },
        meta: {
          current_page: 1,
          from: 1,
          path: 'https://app.trengo.com/api/v2/contacts',
          per_page: 25,
          to: 1,
        },
      },
      status: 200,
    },
  },
];
