// This file contains the test scenarios for the pixel checkout events
import { dummySourceConfig, note_attributes } from '../constants';
import { mockFns } from '../mocks';

export const userTestScenarios = [
  {
    id: 'userTest1',
    name: 'shopify',
    skip: true,
    description:
      'Should multiplex checkout update event into track and identify calls with enriched customer data',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              query_parameters: {
                topic: ['checkouts_update'],
                writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
                version: ['pixel'],
              },
              id: 35374569160817,
              token: 'e89d4437003b6b8480f8bc7f8036a659',
              cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2',
              email: 'testuser101@gmail.com',
              created_at: '2024-09-16T03:50:1500:00',
              updated_at: '2024-09-17T03:29:02-04:00',
              note: '',
              note_attributes,
              shipping_address: {
                first_name: 'testuser',
                address1: 'oakwood bridge',
                phone: null,
                city: 'KLF',
                zip: '85003',
                province: 'Arizona',
                country: 'United States',
                last_name: 'dummy',
                address2: 'Hedgetown',
                company: null,
                latitude: null,
                longitude: null,
                name: 'testuser dummy',
                country_code: 'US',
                province_code: 'AZ',
              },
              total_weight: 0,
              currency: 'USD',
              customer_locale: 'en-US',
              line_items: [
                {
                  key: '41327143059569',
                  fulfillment_service: 'manual',
                  gift_card: false,
                  grams: 0,
                  presentment_title: 'The Multi-location Snowboard',
                  presentment_variant_title: '',
                  product_id: 7234590638193,
                  quantity: 1,
                  requires_shipping: true,
                  sku: '',
                  tax_lines: [],
                  taxable: true,
                  title: 'The Multi-location Snowboard',
                  variant_id: 41327143059569,
                  variant_title: '',
                  variant_price: '729.95',
                  vendor: 'pixel-testing-rs',
                  unit_price_measurement: {
                    measured_type: null,
                    quantity_value: null,
                    quantity_unit: null,
                    reference_value: null,
                    reference_unit: null,
                  },
                  compare_at_price: null,
                  line_price: '729.95',
                  price: '729.95',
                  applied_discounts: [],
                  destination_location_id: null,
                  user_id: null,
                  rank: null,
                  origin_location_id: null,
                  properties: {},
                },
              ],
              name: '#35374569160817',
              abandoned_checkout_url:
                'https://pixel-testing-rs.myshopify.com/59026964593/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2/recover?key=8195f56ee0de230b3a0469cc692f3436',
              presentment_currency: 'USD',
              total_tax: '0.00',
              total_discounts: '0.00',
              subtotal_price: '729.95',
              total_price: '736.85',
              total_duties: '0.00',
              customer: {
                id: 7188389789809,
                email: 'testuser101@gmail.com',
                accepts_marketing: false,
                created_at: null,
                updated_at: null,
                first_name: 'testuser',
                last_name: 'dummy',
                orders_count: 0,
                state: 'disabled',
                total_spent: '0.00',
                last_order_id: null,
                note: null,
                verified_email: true,
                multipass_identifier: null,
                tax_exempt: false,
                phone: '9901109922',
                tags: '',
                currency: 'USD',
                accepts_marketing_updated_at: null,
                admin_graphql_api_id: 'gid://shopify/Customer/7188389789809',
                default_address: {
                  id: null,
                  customer_id: 7188389789809,
                  first_name: 'testuser',
                  last_name: 'dummy',
                  company: null,
                  address1: 'oakwood bridge',
                  address2: 'Hedgetown',
                  city: 'KLF',
                  province: 'Arizona',
                  country: 'United States',
                  zip: '85003',
                  phone: null,
                  name: 'testuser dummy',
                  province_code: 'AZ',
                  country_code: 'US',
                  country_name: 'United States',
                  default: true,
                },
                last_order_name: null,
                marketing_opt_in_level: null,
              },
            },
            source: dummySourceConfig,
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  anonymousId: '50ead33e-d763-4854-b0ab-765859ef05cb',
                  context: {
                    cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2',
                    integration: {
                      name: 'SHOPIFY',
                    },
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    shopifyDetails: {
                      id: 35374569160817,
                      token: 'e89d4437003b6b8480f8bc7f8036a659',
                      cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2',
                      email: 'testuser101@gmail.com',
                      created_at: '2024-09-16T03:50:1500:00',
                      updated_at: '2024-09-17T03:29:02-04:00',
                      note: '',
                      note_attributes,
                      shipping_address: {
                        first_name: 'testuser',
                        address1: 'oakwood bridge',
                        phone: null,
                        city: 'KLF',
                        zip: '85003',
                        province: 'Arizona',
                        country: 'United States',
                        last_name: 'dummy',
                        address2: 'Hedgetown',
                        company: null,
                        latitude: null,
                        longitude: null,
                        name: 'testuser dummy',
                        country_code: 'US',
                        province_code: 'AZ',
                      },
                      total_weight: 0,
                      currency: 'USD',
                      customer_locale: 'en-US',
                      line_items: [
                        {
                          key: '41327143059569',
                          fulfillment_service: 'manual',
                          gift_card: false,
                          grams: 0,
                          presentment_title: 'The Multi-location Snowboard',
                          presentment_variant_title: '',
                          product_id: 7234590638193,
                          quantity: 1,
                          requires_shipping: true,
                          sku: '',
                          tax_lines: [],
                          taxable: true,
                          title: 'The Multi-location Snowboard',
                          variant_id: 41327143059569,
                          variant_title: '',
                          variant_price: '729.95',
                          vendor: 'pixel-testing-rs',
                          unit_price_measurement: {
                            measured_type: null,
                            quantity_value: null,
                            quantity_unit: null,
                            reference_value: null,
                            reference_unit: null,
                          },
                          compare_at_price: null,
                          line_price: '729.95',
                          price: '729.95',
                          applied_discounts: [],
                          destination_location_id: null,
                          user_id: null,
                          rank: null,
                          origin_location_id: null,
                          properties: {},
                        },
                      ],
                      name: '#35374569160817',
                      abandoned_checkout_url:
                        'https://pixel-testing-rs.myshopify.com/59026964593/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2/recover?key=8195f56ee0de230b3a0469cc692f3436',
                      presentment_currency: 'USD',
                      total_tax: '0.00',
                      total_discounts: '0.00',
                      subtotal_price: '729.95',
                      total_price: '736.85',
                      total_duties: '0.00',
                      customer: {
                        id: 7188389789809,
                        email: 'testuser101@gmail.com',
                        accepts_marketing: false,
                        created_at: null,
                        updated_at: null,
                        first_name: 'testuser',
                        last_name: 'dummy',
                        orders_count: 0,
                        state: 'disabled',
                        total_spent: '0.00',
                        last_order_id: null,
                        note: null,
                        verified_email: true,
                        multipass_identifier: null,
                        tax_exempt: false,
                        phone: null,
                        tags: '',
                        currency: 'USD',
                        accepts_marketing_updated_at: null,
                        admin_graphql_api_id: 'gid://shopify/Customer/7188389789809',
                        default_address: {
                          id: null,
                          customer_id: 7188389789809,
                          first_name: 'testuser',
                          last_name: 'dummy',
                          company: null,
                          address1: 'oakwood bridge',
                          address2: 'Hedgetown',
                          city: 'KLF',
                          province: 'Arizona',
                          country: 'United States',
                          zip: '85003',
                          phone: null,
                          name: 'testuser dummy',
                          province_code: 'AZ',
                          country_code: 'US',
                          country_name: 'United States',
                          default: true,
                        },
                        last_order_name: null,
                        marketing_opt_in_level: null,
                      },
                    },
                    traits: {
                      address: {
                        street: 'oakwood bridge',
                        city: 'KLF',
                        country: 'United States',
                        postalCode: '85003',
                      },
                      company: {
                        name: 'Tech Corp',
                      },
                      cart_token_hash: '9e189f39-da46-58df-81b4-5e507d9ef64e',
                      email: 'testuser101@gmail.com',
                      firstName: 'testuser',
                      lastName: 'dummy',
                      name: 'testuser dummy',
                    },
                    topic: 'checkouts_update',
                  },
                  event: 'Checkout Updated',
                  integrations: {
                    SHOPIFY: true,
                    DATA_WAREHOUSE: {
                      options: {
                        jsonPaths: ['track.context.shopifyDetails'],
                      },
                    },
                  },
                  properties: {
                    currency: 'USD',
                    order_id: '35374569160817',
                    products: [
                      {
                        brand: 'pixel-testing-rs',
                        price: 729.95,
                        product_id: '7234590638193',
                        quantity: 1,
                      },
                    ],
                    tax: 0,
                  },
                  timestamp: '2024-09-17T07:29:02.000Z',
                  type: 'track',
                  userId: '7188389789809',
                },
                {
                  anonymousId: '50ead33e-d763-4854-b0ab-765859ef05cb',
                  context: {
                    integration: {
                      name: 'SHOPIFY',
                    },
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    traits: {
                      address: {
                        street: 'oakwood bridge',
                        city: 'KLF',
                        country: 'United States',
                        postalCode: '85003',
                      },
                      company: {
                        name: 'Tech Corp',
                      },
                      createdAt: '2024-09-16T03:50:1500:00',
                      id: 7358220173425,
                      cart_token_hash: '9e189f39-da46-58df-81b4-5e507d9ef64e',
                      email: 'testuser101@gmail.com',
                      phone: '9901109922',
                      firstName: 'testuser',
                      lastName: 'dummy',
                      name: 'testuser dummy',
                    },
                  },
                  integrations: {
                    SHOPIFY: true,
                  },
                  type: 'identify',
                  userId: '7188389789809',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    id: 'userTest2',
    name: 'shopify',
    skip: true,
    description:
      'Fire an identify call post checkout is completed, from the customer update event webhook',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              id: 7358220173425,
              email: 'henry@wfls.com',
              created_at: '2024-10-23T16:03:11-04:00',
              updated_at: '2024-11-05T21:54:49-05:00',
              first_name: 'yodi',
              last_name: 'waffles',
              orders_count: 0,
              state: 'disabled',
              total_spent: '0.00',
              last_order_id: null,
              note: null,
              verified_email: true,
              multipass_identifier: null,
              tax_exempt: false,
              tags: '',
              last_order_name: null,
              currency: 'USD',
              phone: null,
              addresses: [
                {
                  id: 8715246895217,
                  customer_id: 7358220173425,
                  first_name: 'yodi',
                  last_name: 'waffles',
                  company: null,
                  address1: 'Yuma Proving Ground',
                  address2: 'suite 001',
                  city: 'Yuma Proving Ground',
                  province: 'Arizona',
                  country: 'United States',
                  zip: '85365',
                  phone: null,
                  name: 'yodi waffles',
                  province_code: 'AZ',
                  country_code: 'US',
                  country_name: 'United States',
                  default: false,
                },
              ],
              tax_exemptions: [],
              email_marketing_consent: {
                state: 'not_subscribed',
                opt_in_level: 'single_opt_in',
                consent_updated_at: null,
              },
              sms_marketing_consent: null,
              admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
              default_address: {
                id: 8715246862449,
                customer_id: 7358220173425,
                first_name: 'henry',
                last_name: 'waffles',
                company: null,
                address1: 'Yuimaru Kitchen',
                address2: '6',
                city: 'Johnson City',
                province: 'Tennessee',
                country: 'United States',
                zip: '37604',
                phone: null,
                name: 'henry waffles',
                province_code: 'TN',
                country_code: 'US',
                country_name: 'United States',
                default: true,
              },
              query_parameters: {
                topic: ['customers_update'],
                version: ['pixel'],
                writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              },
            },
            source: dummySourceConfig,
            query_parameters: {
              topic: ['carts_update'],
              writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              version: ['pixel'],
            },
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    integration: {
                      name: 'SHOPIFY',
                    },
                    topic: 'customers_update',
                    shopifyDetails: {
                      id: 7358220173425,
                      email: 'henry@wfls.com',
                      created_at: '2024-10-23T16:03:11-04:00',
                      updated_at: '2024-11-05T21:54:49-05:00',
                      first_name: 'yodi',
                      last_name: 'waffles',
                      orders_count: 0,
                      state: 'disabled',
                      total_spent: '0.00',
                      last_order_id: null,
                      note: null,
                      verified_email: true,
                      multipass_identifier: null,
                      tax_exempt: false,
                      tags: '',
                      last_order_name: null,
                      currency: 'USD',
                      phone: null,
                      addresses: [
                        {
                          id: 8715246895217,
                          customer_id: 7358220173425,
                          first_name: 'yodi',
                          last_name: 'waffles',
                          company: null,
                          address1: 'Yuma Proving Ground',
                          address2: 'suite 001',
                          city: 'Yuma Proving Ground',
                          province: 'Arizona',
                          country: 'United States',
                          zip: '85365',
                          phone: null,
                          name: 'yodi waffles',
                          province_code: 'AZ',
                          country_code: 'US',
                          country_name: 'United States',
                          default: false,
                        },
                      ],
                      tax_exemptions: [],
                      email_marketing_consent: {
                        state: 'not_subscribed',
                        opt_in_level: 'single_opt_in',
                        consent_updated_at: null,
                      },
                      sms_marketing_consent: null,
                      admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
                      default_address: {
                        id: 8715246862449,
                        customer_id: 7358220173425,
                        first_name: 'henry',
                        last_name: 'waffles',
                        company: null,
                        address1: 'Yuimaru Kitchen',
                        address2: '6',
                        city: 'Johnson City',
                        province: 'Tennessee',
                        country: 'United States',
                        zip: '37604',
                        phone: '9112345678',
                        name: 'henry waffles',
                        province_code: 'TN',
                        country_code: 'US',
                        country_name: 'United States',
                        default: true,
                      },
                    },
                    traits: {
                      id: 7358220173425,
                      email: 'henry@wfls.com',
                      phone: '9112345678',
                      firstName: 'yodi',
                      lastName: 'waffles',
                      name: 'yodi waffles',
                      address: {
                        street: 'Yuimaru Kitchen',
                        city: 'Johnson City',
                        country: 'United States',
                        postalCode: '37604',
                      },
                      company: {
                        name: 'Tech Corp',
                      },
                    },
                  },
                  integrations: {
                    SHOPIFY: true,
                    DATA_WAREHOUSE: {
                      options: {
                        jsonPaths: ['identify.context.shopifyDetails'],
                      },
                    },
                  },
                  created_at: '2024-10-23T16:03:11-04:00',
                  type: 'identify',
                  userId: '7358220173425',
                  timestamp: '2024-11-06T02:54:49.000Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    id: 'userTest2',
    name: 'shopify',
    skip: true,
    description:
      'Fire an identify call post checkout is completed, from the customer create event webhook',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              id: 7358220173425,
              email: 'henry@wfls.com',
              created_at: '2024-10-23T16:03:11-04:00',
              first_name: 'yodi',
              last_name: 'waffles',
              state: 'disabled',
              total_spent: '0.00',
              last_order_id: null,
              note: null,
              verified_email: true,
              multipass_identifier: null,
              tax_exempt: false,
              tags: '',
              last_order_name: null,
              currency: 'USD',
              phone: null,
              addresses: [
                {
                  id: 8715246895217,
                  customer_id: 7358220173425,
                  first_name: 'yodi',
                  last_name: 'waffles',
                  company: null,
                  address1: 'Yuma Proving Ground',
                  address2: 'suite 001',
                  city: 'Yuma Proving Ground',
                  province: 'Arizona',
                  country: 'United States',
                  zip: '85365',
                  phone: null,
                  name: 'yodi waffles',
                  province_code: 'AZ',
                  country_code: 'US',
                  country_name: 'United States',
                  default: false,
                },
              ],
              tax_exemptions: [],
              email_marketing_consent: {
                state: 'not_subscribed',
                opt_in_level: 'single_opt_in',
                consent_updated_at: null,
              },
              sms_marketing_consent: null,
              admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
              default_address: {
                id: 8715246862449,
                customer_id: 7358220173425,
                first_name: 'henry',
                last_name: 'waffles',
                company: null,
                address1: 'Yuimaru Kitchen',
                address2: '6',
                city: 'Johnson City',
                province: 'Tennessee',
                country: 'United States',
                zip: '37604',
                phone: null,
                name: 'henry waffles',
                province_code: 'TN',
                country_code: 'US',
                country_name: 'United States',
                default: true,
              },
              query_parameters: {
                topic: ['customers_create'],
                version: ['pixel'],
                writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              },
            },
            source: dummySourceConfig,
            query_parameters: {
              topic: ['carts_update'],
              writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              version: ['pixel'],
            },
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    integration: {
                      name: 'SHOPIFY',
                    },
                    topic: 'customers_create',
                    shopifyDetails: {
                      id: 7358220173425,
                      email: 'henry@wfls.com',
                      created_at: '2024-10-23T16:03:11-04:00',
                      updated_at: '2024-11-05T21:54:49-05:00',
                      first_name: 'yodi',
                      last_name: 'waffles',
                      orders_count: 0,
                      state: 'disabled',
                      total_spent: '0.00',
                      last_order_id: null,
                      note: null,
                      verified_email: true,
                      multipass_identifier: null,
                      tax_exempt: false,
                      tags: '',
                      last_order_name: null,
                      currency: 'USD',
                      phone: null,
                      addresses: [
                        {
                          id: 8715246895217,
                          customer_id: 7358220173425,
                          first_name: 'yodi',
                          last_name: 'waffles',
                          company: null,
                          address1: 'Yuma Proving Ground',
                          address2: 'suite 001',
                          city: 'Yuma Proving Ground',
                          province: 'Arizona',
                          country: 'United States',
                          zip: '85365',
                          phone: null,
                          name: 'yodi waffles',
                          province_code: 'AZ',
                          country_code: 'US',
                          country_name: 'United States',
                          default: false,
                        },
                      ],
                      tax_exemptions: [],
                      email_marketing_consent: {
                        state: 'not_subscribed',
                        opt_in_level: 'single_opt_in',
                        consent_updated_at: null,
                      },
                      sms_marketing_consent: null,
                      admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
                      default_address: {
                        id: 8715246862449,
                        customer_id: 7358220173425,
                        first_name: 'henry',
                        last_name: 'waffles',
                        company: null,
                        address1: 'Yuimaru Kitchen',
                        address2: '6',
                        city: 'Johnson City',
                        province: 'Tennessee',
                        country: 'United States',
                        zip: '37604',
                        phone: '9112345678',
                        name: 'henry waffles',
                        province_code: 'TN',
                        country_code: 'US',
                        country_name: 'United States',
                        default: true,
                      },
                    },
                    traits: {
                      id: 7358220173425,
                      email: 'henry@wfls.com',
                      phone: '9112345678',
                      firstName: 'yodi',
                      lastName: 'waffles',
                      name: 'yodi waffles',
                      address: {
                        street: 'Yuimaru Kitchen',
                        city: 'Johnson City',
                        country: 'United States',
                        postalCode: '37604',
                      },
                      company: {
                        name: 'Tech Corp',
                      },
                    },
                  },
                  integrations: {
                    SHOPIFY: true,
                    DATA_WAREHOUSE: {
                      options: {
                        jsonPaths: ['identify.context.shopifyDetails'],
                      },
                    },
                  },
                  created_at: '2024-10-23T16:03:11-04:00',
                  type: 'identify',
                  userId: '7358220173425',
                  timestamp: '2024-11-06T02:54:49.000Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
].map((u1) => ({ ...u1, mockFns }));
