const KEY_CHECK_LIST = ['ITEM_ID', 'EVENT_VALUE', 'IMPRESSION', 'RECOMMENDATION_ID'];

const MANDATORY_PROPERTIES = ['USER_ID', 'EVENT_TYPE', 'TIMESTAMP'];

module.exports = {
  KEY_CHECK_LIST,
  MANDATORY_PROPERTIES,
};
