export const data = [
  {
    name: 'kochava',
    description: 'Test 0',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            message: {
              anonymousId: 'sampath',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                ip: '1.1.1.1',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                locale: 'en-US',
                os: { name: 'macOS', version: '15.9' },
                screen: { density: 2 },
                traits: { anonymousId: 'sampath', email: 'sampath@gmail.com' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
              },
              event: 'product added',
              integrations: { All: true },
              messageId: 'ea5cfab2-3961-4d8a-8187-3d1858c90a9f',
              originalTimestamp: '2020-01-17T04:53:51.185Z',
              properties: { name: 'sampath' },
              receivedAt: '2020-01-17T10:23:52.688+05:30',
              request_ip: '0.0.0.0',
              sentAt: '2020-01-17T04:53:52.667Z',
              timestamp: '2020-01-17T10:23:51.206+05:30',
              type: 'track',
              userId: 'sampath',
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: 'sampath',
                  data: {
                    app_tracking_transparency: { att: false },
                    currency: 'USD',
                    device_ids: { idfa: '', idfv: '', adid: '', android_id: '' },
                    device_ver: '',
                    usertime: 1579236831206,
                    origination_ip: '1.1.1.1',
                    device_ua:
                      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
                    app_name: 'RudderLabs JavaScript SDK',
                    app_version: '1.0.0',
                    app_short_string: '1.0.0',
                    os_version: '15.9',
                    screen_dpi: 2,
                    locale: 'en-US',
                    event_name: 'Add to Cart',
                    event_data: { name: 'sampath' },
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: 'sampath',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 1',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: '', version: '' },
                screen: { density: 2 },
              },
              type: 'identify',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error:
              'message type identify is not supported: Workflow: procWorkflow, Step: validateInput, ChildStep: undefined, OriginalError: message type identify is not supported',
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            statTags: {
              destType: 'KOCHAVA',
              errorCategory: 'dataValidation',
              destinationId: 'destId',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'cdkV2',
              module: 'destination',
              workspaceId: 'wspId',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 2',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: '', version: '' },
                screen: { density: 2 },
              },
              type: 'screen',
              name: 'Home Screen',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '00000000000000000000000000',
                  data: {
                    app_tracking_transparency: { att: false },
                    currency: 'USD',
                    device_ids: { idfa: '', idfv: '', adid: '', android_id: '' },
                    device_ver: '',
                    os_version: '',
                    usertime: 1571043797562,
                    device_ua:
                      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                    app_name: 'RudderLabs JavaScript SDK',
                    app_version: '1.0.0',
                    app_short_string: '1.0.0',
                    screen_dpi: 2,
                    locale: 'en-US',
                    event_name: 'screen view',
                    event_data: {},
                    origination_ip: '1.1.1.1',
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 3',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: '', version: '' },
                screen: { density: 2 },
              },
              type: 'screen',
              properties: { name: 'Home Screen' },
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '00000000000000000000000000',
                  data: {
                    app_tracking_transparency: { att: false },
                    currency: 'USD',
                    device_ids: { idfa: '', idfv: '', adid: '', android_id: '' },
                    device_ver: '',
                    os_version: '',
                    usertime: 1571043797562,
                    device_ua:
                      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                    app_name: 'RudderLabs JavaScript SDK',
                    app_version: '1.0.0',
                    app_short_string: '1.0.0',
                    screen_dpi: 2,
                    locale: 'en-US',
                    event_name: 'screen view Home Screen',
                    event_data: { name: 'Home Screen' },
                    origination_ip: '1.1.1.1',
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 4',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  adTrackingEnabled: true,
                  advertisingId: 'some_adid',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '5094f5704b9cf2b3',
                  data: {
                    app_tracking_transparency: { att: false },
                    usertime: 1584003903421,
                    app_version: '1',
                    device_ver: 'Android SDK built for x86-Android-8.1.0',
                    device_ids: {
                      idfa: '',
                      idfv: '',
                      adid: 'some_adid',
                      android_id: '5094f5704b9cf2b3',
                    },
                    device_ua:
                      'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
                    event_name: 'screen view MainActivity',
                    currency: 'USD',
                    event_data: { name: 'MainActivity', automatic: true },
                    app_name: 'LeanPlumIntegrationAndroid',
                    app_short_string: '1.0',
                    locale: 'en-US',
                    os_version: '8.1.0',
                    screen_dpi: 420,
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 5',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  adTrackingEnabled: true,
                  advertisingId: 'some_adid',
                  attTrackingStatus: 3,
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'iOS', version: '14.5' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '5094f5704b9cf2b3',
                  data: {
                    app_tracking_transparency: { att: true },
                    usertime: 1584003903421,
                    app_version: '1',
                    device_ver: 'Android SDK built for x86-iOS-14.5',
                    device_ids: {
                      idfa: 'some_adid',
                      idfv: '5094f5704b9cf2b3',
                      adid: '',
                      android_id: '',
                    },
                    device_ua:
                      'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
                    event_name: 'screen view MainActivity',
                    currency: 'USD',
                    event_data: { name: 'MainActivity', automatic: true },
                    app_name: 'LeanPlumIntegrationAndroid',
                    app_short_string: '1.0',
                    locale: 'en-US',
                    os_version: '14.5',
                    screen_dpi: 420,
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 6',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'ipados',
                  adTrackingEnabled: true,
                  advertisingId: 'some_adid',
                  attTrackingStatus: 3,
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'ipados' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '5094f5704b9cf2b3',
                  data: {
                    app_tracking_transparency: { att: true },
                    usertime: 1584003903421,
                    app_version: '1',
                    device_ver: '',
                    device_ids: {
                      idfa: 'some_adid',
                      idfv: '5094f5704b9cf2b3',
                      adid: '',
                      android_id: '',
                    },
                    device_ua:
                      'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
                    event_name: 'screen view MainActivity',
                    currency: 'USD',
                    event_data: { name: 'MainActivity', automatic: true },
                    app_name: 'LeanPlumIntegrationAndroid',
                    app_short_string: '1.0',
                    locale: 'en-US',
                    screen_dpi: 420,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 7',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  adTrackingEnabled: true,
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '5094f5704b9cf2b3',
                  data: {
                    app_tracking_transparency: { att: false },
                    usertime: 1584003903421,
                    app_version: '1',
                    device_ver: 'Android SDK built for x86-Android-8.1.0',
                    device_ids: { idfa: '', idfv: '', adid: '', android_id: '5094f5704b9cf2b3' },
                    device_ua:
                      'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
                    event_name: 'screen view MainActivity',
                    currency: 'USD',
                    event_data: { name: 'MainActivity', automatic: true },
                    app_name: 'LeanPlumIntegrationAndroid',
                    app_short_string: '1.0',
                    locale: 'en-US',
                    os_version: '8.1.0',
                    screen_dpi: 420,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 8',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  adTrackingEnabled: true,
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '5094f5704b9cf2b3',
                  data: {
                    app_tracking_transparency: { att: false },
                    usertime: 1584003903421,
                    app_version: '1',
                    device_ver: '',
                    device_ids: { idfa: '', idfv: '', adid: '', android_id: '' },
                    device_ua:
                      'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
                    event_name: 'screen view MainActivity',
                    currency: 'USD',
                    event_data: { name: 'MainActivity', automatic: true },
                    app_name: 'LeanPlumIntegrationAndroid',
                    app_short_string: '1.0',
                    locale: 'en-US',
                    screen_dpi: 420,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 9',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: '', version: '' },
                screen: { density: 2 },
              },
              type: 'screen',
              name: 'Home Screen',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              timestamp: '2019-10-14T09:03:17.562Z',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '00000000000000000000000000',
                  data: {
                    app_tracking_transparency: { att: false },
                    usertime: 1571043797562,
                    app_version: '1.0.0',
                    device_ver: '',
                    device_ids: { idfa: '', idfv: '', adid: '', android_id: '' },
                    device_ua: '',
                    event_name: 'screen view',
                    origination_ip: '1.1.1.1',
                    currency: 'USD',
                    event_data: {},
                    app_name: 'RudderLabs JavaScript SDK',
                    app_short_string: '1.0.0',
                    locale: 'en-US',
                    os_version: '',
                    screen_dpi: 2,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 10',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: 'ios', version: '' },
                device: { attTrackingStatus: 3 },
                screen: { density: 2 },
              },
              type: 'screen',
              name: 'Home Screen',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              timestamp: '2019-10-14T09:03:17.562Z',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '00000000000000000000000000',
                  data: {
                    app_tracking_transparency: { att: true },
                    usertime: 1571043797562,
                    app_version: '1.0.0',
                    device_ver: '',
                    device_ids: {
                      idfa: '',
                      idfv: '00000000000000000000000000',
                      adid: '',
                      android_id: '',
                    },
                    device_ua: '',
                    event_name: 'screen view',
                    origination_ip: '1.1.1.1',
                    currency: 'USD',
                    event_data: {},
                    app_name: 'RudderLabs JavaScript SDK',
                    app_short_string: '1.0.0',
                    locale: 'en-US',
                    os_version: '',
                    screen_dpi: 2,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 11',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: 'tvOS', version: '' },
                screen: { density: 2 },
              },
              type: 'screen',
              name: 'Home Screen',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              timestamp: '2019-10-14T09:03:17.562Z',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '00000000000000000000000000',
                  data: {
                    app_tracking_transparency: { att: false },
                    usertime: 1571043797562,
                    app_version: '1.0.0',
                    device_ver: '',
                    device_ids: {
                      idfa: '',
                      idfv: '00000000000000000000000000',
                      adid: '',
                      android_id: '',
                    },
                    device_ua: '',
                    event_name: 'screen view',
                    origination_ip: '1.1.1.1',
                    currency: 'USD',
                    event_data: {},
                    app_name: 'RudderLabs JavaScript SDK',
                    app_short_string: '1.0.0',
                    locale: 'en-US',
                    os_version: '',
                    screen_dpi: 2,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
  {
    name: 'kochava',
    description: 'Test 12',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                locale: 'en-US',
                ip: '1.1.1.1',
                os: { name: 'android', version: '' },
                screen: { density: 2 },
              },
              type: 'screen',
              name: 'Home Screen',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              timestamp: '2019-10-14T09:03:17.562Z',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              userId: '123456',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
            destination: {
              Config: { apiKey: '<kochava guid goes here>' },
              DestinationDefinition: {
                Config: { cdkV2Enabled: true },
                DisplayName: 'Kochava',
                ID: '1WTpBSTiL3iAUHUdW7rHT4sawgU',
                Name: 'KOCHAVA',
              },
              Enabled: true,
              ID: '1WTpIHpH7NTBgjeiUPW1kCUgZGI',
              Name: 'kochava test',
              Transformations: [],
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://control.kochava.com/track/json',
              headers: {},
              params: {},
              body: {
                JSON: {
                  action: 'event',
                  kochava_app_id: '<kochava guid goes here>',
                  kochava_device_id: '00000000000000000000000000',
                  data: {
                    app_tracking_transparency: { att: false },
                    usertime: 1571043797562,
                    app_version: '1.0.0',
                    device_ver: '',
                    device_ids: {
                      idfa: '',
                      idfv: '',
                      adid: '',
                      android_id: '00000000000000000000000000',
                    },
                    device_ua: '',
                    event_name: 'screen view',
                    origination_ip: '1.1.1.1',
                    currency: 'USD',
                    event_data: {},
                    app_name: 'RudderLabs JavaScript SDK',
                    app_short_string: '1.0.0',
                    locale: 'en-US',
                    os_version: '',
                    screen_dpi: 2,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
            metadata: {
              destinationId: 'destId',
              workspaceId: 'wspId',
            },
          },
        ],
      },
    },
  },
];
