export const excludedFieldList = [
  'activity_kind',
  'event',
  'event_name',
  'gps_adid',
  'idfa',
  'idfv',
  'adid',
  'tracker',
  'tracker_name',
  'app_name',
  'ip_address',
  'tracking_enabled',
  'tracker_token',
  'created_at',
];
