const deleteNwData = [
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://api.intercom.io/user_delete_requests',
      data: {
        intercom_user_id: '1',
      },
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer API_KEY',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        type: 'error.list',
        request_id: '0022e6v5qc7m04jeu5pg',
        errors: [
          {
            code: 'unauthorized',
            message: 'Access Token Invalid',
          },
        ],
      },
      status: 400,
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://api.intercom.io/user_delete_requests',
      data: {
        intercom_user_id: '12',
      },
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer API_KEY',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'ok',
      data: {
        id: 12,
      },
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://api.intercom.io/user_delete_requests',
      data: {
        intercom_user_id: '7',
      },
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer API_KEY',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'ok',
      data: {
        id: 7,
      },
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://api.intercom.io/user_delete_requests',
      data: {
        intercom_user_id: '9',
      },
      headers: {
        Accept: 'application/json',
        Authorization: 'Bearer API_KEY',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'ok',
      data: {
        id: 9,
      },
    },
  },
];
export const networkCallsData = [...deleteNwData];
