const deleteNwData = [
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_1',
        },
        webPropertyId: 'UA-123456789-5',
      },
      headers: {
        Authorization: 'Bearer valid_token',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_1',
        },
        webPropertyId: 'UA-123456789-5',
        deletionRequestTime: '2022-11-04T10:39:57.933Z',
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_2',
        },
        webPropertyId: 'UA-123456789-5',
      },
      headers: {
        Authorization: 'Bearer valid_token',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_2',
        },
        webPropertyId: 'UA-123456789-5',
        deletionRequestTime: '2022-11-04T10:39:57.933Z',
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_3',
        },
        webPropertyId: 'UA-123456789-6',
      },
      headers: {
        Authorization: 'Bearer expired_token',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        error: {
          code: 401,
          message:
            'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
          status: 'UNAUTHENTICATED',
        },
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_4',
        },
        webPropertyId: 'UA-123456789-6',
      },
      headers: {
        Authorization: 'Bearer expired_token',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        error: {
          code: 401,
          message:
            'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
          status: 'UNAUTHENTICATED',
        },
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_5',
        },
        webPropertyId: 'UA-123456789-7',
      },
      headers: {
        Authorization: 'Bearer valid_token_1',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_5',
        },
        webPropertyId: 'UA-123456789-7',
        deletionRequestTime: '2022-11-04T10:39:57.933Z',
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_6',
        },
        webPropertyId: 'UA-123456789-7',
      },
      headers: {
        Authorization: 'Bearer valid_token_1',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_6',
        },
        webPropertyId: 'UA-123456789-7',
        deletionRequestTime: '2022-11-04T10:39:57.933Z',
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_7',
        },
        webPropertyId: 'UA-123456789-7',
      },
      headers: {
        Authorization: 'Bearer valid_token_1',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        error: {
          errors: [
            {
              domain: 'global',
              reason: 'invalidParameter',
              message: '[dummy response] The parameter used to query is not correct',
            },
          ],
          code: 403,
          message: '[dummy response] The parameter used to query is not correct',
        },
      },
      status: 403,
      statusText: 'Bad Request',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_8',
        },
        webPropertyId: 'UA-123456789-7',
      },
      headers: {
        Authorization: 'Bearer valid_token_1',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_8',
        },
        webPropertyId: 'UA-123456789-7',
        deletionRequestTime: '2022-11-04T10:39:57.933Z',
      },
      status: 200,
      statusText: 'OK',
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://www.googleapis.com/analytics/v3/userDeletion/userDeletionRequests:upsert',
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_9',
        },
        webPropertyId: 'UA-123456789-7',
      },
      headers: {
        Authorization: 'Bearer valid_token_1',
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        kind: 'analytics#userDeletionRequest',
        id: {
          type: 'USER_ID',
          userId: 'test_user_9',
        },
        webPropertyId: 'UA-123456789-7',
        deletionRequestTime: '2022-11-04T10:39:57.933Z',
      },
      status: 200,
      statusText: 'OK',
    },
  },
];
export const networkCallsData = [...deleteNwData];
