message:
  supportedMessageTypes:
    - identify
    - track
  identify:
    transformation:
      mapperPath: ./mapping/identify.yaml
      postMapper:
        name: 'identifyPostMapper'
      response:
        endpoint: 'https://api2.autopilothq.com/v1/contact'
        method: POST
        format: JSON
        headers:
          Accept: 'application/json'
          autopilotapikey: '{{ destConfig.apiKey }}'
          Content-Type: 'application/json'
        userId: '{{ message.anonymousId }}'

  track:
    transformation:
      mapperPath: ./mapping/track.yaml
      postMapper:
        name: 'trackPostMapper'
      response:
        endpoint: '{{ rudderContext.endpoint }}'
        method: POST
        format: JSON
        headers:
          Accept: 'application/json'
          autopilotapikey: '{{ destConfig.apiKey }}'
          Content-Type: 'application/json'
        userId: '{{ message.anonymousId }}'
