const deleteNwData = [
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://rest.iad-03.braze.com/users/delete',
      data: {
        external_ids: [
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
        ],
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Bearer 1234',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        code: 400,
        message: 'Bad Req',
        status: 'Fail Case',
      },
      status: 400,
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://rest.iad-03.braze.com/users/delete',
      data: {
        external_ids: [
          'test_user_id10',
          'user_sdk2',
          'test_user_id18',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
        ],
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Bearer 1234',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'OK',
      data: {
        deleted: 50,
        message: 'success',
      },
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://rest.iad-03.braze.com/users/delete',
      data: { external_ids: ['test_user_id51'] },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Bearer 1234',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'OK',
      data: {
        ' message': {
          deleted: '1',
          message: 'success',
        },
      },
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://rest.iad-03.braze.com/users/delete',
      data: {
        externalIds: ['test_user_id'],
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Bearer 1234',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'OK',
      data: {
        ' message': {
          deleted: 1,
          message: 'success',
        },
      },
    },
  },
];
export const networkCallsData = [...deleteNwData];
