jobs:
  - jobId: 'job_id_1'
    event:
      context:
        traits:
          page_id: 'page_id'
          form_id: 'form_id'
      type: identify
      anonymousId: 'leadgen_id'
      timestamp: '1970-01-01T00:00:00.000Z'
      messageId: 'page_id-form_id-leadgen_id'
      originalTimestamp: '1970-01-01T00:00:00.000Z'
      sentAt: '1970-01-01T00:00:00.000Z'
      integrations:
        All: true
  - jobId: 'job_id_2'
    event:
      context:
        traits:
          page_id: 'page_id'
          form_id: 'form_id'
      type: identify
      anonymousId: 'leadgen_id'
      timestamp: '1970-01-01T00:00:00.000Z'
      messageId: 'page_id-form_id-leadgen_id'
      originalTimestamp: '1970-01-01T00:00:00.000Z'
      sentAt: '1970-01-01T00:00:00.000Z'
      integrations:
        All: true
source:
  id: 'source_id'
  config:
    internalSecrets:
      accessToken: 'access_token'
  workspaceId: 'workspace_id'
  sourceDefinition:
    name: FACEBOOK_LEAD_ADS_NATIVE
