export const networkCallsData = [
  {
    httpReq: {
      Accept: 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded',
      data: 'apiKey=apikey123&email=test%40rudderstack.com',
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        freeSockets: {},
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxFreeSockets: 256,
        maxSockets: null,
        maxTotalSockets: null,
        options: { keepAlive: true, noDelay: true, path: null },
        protocol: 'http:',
        requests: {},
        scheduling: 'lifo',
        sockets: {},
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        _sessionCache: { list: [], map: {} },
        defaultPort: 443,
        freeSockets: {},
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxCachedSessions: 100,
        maxFreeSockets: 256,
        maxSockets: null,
        maxTotalSockets: null,
        options: { keepAlive: true, noDelay: true, path: null },
        protocol: 'https:',
        requests: {},
        scheduling: 'lifo',
        sockets: {},
        totalSocketCount: 0,
      },
      maxBodyLength: 100000000,
      maxContentLength: 100000000,
      maxRedirects: 5,
      method: 'POST',
      responseEncoding: 'utf8',
      responseType: 'json',
      timeout: 60000,
      url: 'https://canny.io/api/v1/users/retrieve',
      withCredentials: false,
    },
    httpRes: {
      data: {
        data: {
          avatarURL: 'https://canny.io/images/cddfd145056cd4bc04132ee0e7de04ee.png',
          created: '2022-07-15T11:16:32.648Z',
          email: 'test@rudderstack.com',
          id: '52d14c90fff7c80abcd12345',
          isAdmin: true,
          lastActivity: '2022-07-18T14:24:43.632Z',
          name: 'Rudder Test',
          url: 'https://ruderstack.canny.io/admin/users/dummyUser',
          userID: null,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      Accept: 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded',
      data: 'apiKey=apikey123&email=test%40rudderstack.com',
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        freeSockets: {},
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxFreeSockets: 256,
        maxSockets: null,
        maxTotalSockets: null,
        options: { keepAlive: true, noDelay: true, path: null },
        protocol: 'http:',
        requests: {},
        scheduling: 'lifo',
        sockets: {},
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        _sessionCache: { list: [], map: {} },
        defaultPort: 443,
        freeSockets: {},
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxCachedSessions: 100,
        maxFreeSockets: 256,
        maxSockets: null,
        maxTotalSockets: null,
        options: { keepAlive: true, noDelay: true, path: null },
        protocol: 'https:',
        requests: {},
        scheduling: 'lifo',
        sockets: {},
        totalSocketCount: 0,
      },
      maxBodyLength: 100000000,
      maxContentLength: 100000000,
      maxRedirects: 5,
      method: 'POST',
      responseEncoding: 'utf8',
      responseType: 'json',
      timeout: 60000,
      url: 'https://canny.io/api/v1/users/retrieve',
      withCredentials: false,
    },
    httpRes: {
      data: {
        data: {
          avatarURL: 'https://canny.io/images/cddfd145056cd4bc04132ee0e7de04ee.png',
          created: '2022-07-15T11:16:32.648Z',
          email: 'test@rudderstack.com',
          id: '52d14c90fff7c80abcd12345',
          isAdmin: true,
          lastActivity: '2022-07-18T14:24:43.632Z',
          name: 'Rudder Test',
          url: 'https://ruderstack.canny.io/admin/users/dummyUser',
          userID: null,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      Accept: 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded',
      data: 'apiKey=apikey123&email=test%40rudderstack.com',
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        freeSockets: {},
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxFreeSockets: 256,
        maxSockets: null,
        maxTotalSockets: null,
        options: { keepAlive: true, noDelay: true, path: null },
        protocol: 'http:',
        requests: {},
        scheduling: 'lifo',
        sockets: {},
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        _sessionCache: { list: [], map: {} },
        defaultPort: 443,
        freeSockets: {},
        keepAlive: true,
        keepAliveMsecs: 1000,
        maxCachedSessions: 100,
        maxFreeSockets: 256,
        maxSockets: null,
        maxTotalSockets: null,
        options: { keepAlive: true, noDelay: true, path: null },
        protocol: 'https:',
        requests: {},
        scheduling: 'lifo',
        sockets: {},
        totalSocketCount: 0,
      },
      maxBodyLength: 100000000,
      maxContentLength: 100000000,
      maxRedirects: 5,
      method: 'POST',
      responseEncoding: 'utf8',
      responseType: 'json',
      timeout: 60000,
      url: 'https://canny.io/api/v1/users/retrieve',
      withCredentials: false,
    },
    httpRes: {
      data: {
        data: {
          avatarURL: 'https://canny.io/images/cddfd145056cd4bc04132ee0e7de04ee.png',
          created: '2022-07-15T11:16:32.648Z',
          email: 'test@rudderstack.com',
          id: '52d14c90fff7c80abcd12345',
          isAdmin: true,
          lastActivity: '2022-07-18T14:24:43.632Z',
          name: 'Rudder Test',
          url: 'https://ruderstack.canny.io/admin/users/dummyUser',
          userID: null,
        },
      },
      status: 200,
    },
  },
];
