const deleteNwData = [
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://amplitude.com/api/2/deletions/users',
      data: {
        user_ids: [
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
        ],
        requester: 'RudderStack',
        ignore_invalid_id: 'true',
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Basic MTIzNDphYmNk',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      data: {
        code: 403,
        message: 'HTTP 403: Forbidden (Invalid API Key)',
        status: 'Forbidden',
      },
      status: 400,
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://amplitude.com/api/2/deletions/users',
      data: {
        user_ids: [
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
          'user_sdk2',
          'test_user_id',
        ],
        requester: 'RudderStack',
        ignore_invalid_id: 'true',
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Basic MTIzNDphYmNk',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'OK',
      data: {
        ' message': 'Nothing scheduled due to invalid amplitude/user ids for app XXXXX',
      },
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://amplitude.com/api/2/deletions/users',
      data: {
        userIds: ['Batch1'],
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Basic MTIzNDphYmNk',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'OK',
      data: {
        ' message': 'Mocking',
      },
    },
  },
  {
    httpReq: {
      method: 'post',
      timeout: 60000,
      withCredentials: false,
      responseType: 'json',
      responseEncoding: 'utf8',
      maxBodyLength: 100000000,
      maxRedirects: 5,
      httpAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 80,
        protocol: 'http:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
      },
      httpsAgent: {
        _events: {},
        _eventsCount: 2,
        defaultPort: 443,
        protocol: 'https:',
        options: {
          keepAlive: true,
          noDelay: true,
          path: null,
        },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: null,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: null,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {},
          list: [],
        },
      },
      url: 'https://amplitude.com/api/2/deletions/users',
      data: {
        userIds: ['Batch2'],
      },
      headers: {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Basic MTIzNDphYmNk',
      },
      maxContentLength: 100000000,
    },
    httpRes: {
      status: 200,
      statusText: 'OK',
      data: {
        ' message': 'Mocking',
      },
    },
  },
];
export const networkCallsData = [...deleteNwData];
