export const data = [
  {
    name: 'leanplum',
    description: 'Test 0',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 1',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id2',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key__',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key__',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key__',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 2',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id3',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 3',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id3',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'page',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 4',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              name: 'Test Page Name',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id3',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'page',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'Test Page Name',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 5',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id4',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 6',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id5',
              properties: { automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 7',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              integrations: { All: true },
              messageId: 'id6',
              properties: { automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Missing required value from ["properties.name","event"]',
            statTags: {
              destType: 'LEANPLUM',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 8',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.0.0',
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.0.0' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36',
                locale: 'en-US',
                ip: '0.0.0.0',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: {
                  id: 'some_developer_id',
                  createAt: '2019-10-14T09:03:17.562Z',
                  address: { country: 'USA', city: 'NY' },
                  country: 'India',
                  city: 'Delhi',
                },
              },
              type: 'identify',
              messageId: '84e26acc-56a5-4835-8233-591137fca468',
              originalTimestamp: '2019-10-14T09:03:17.562Z',
              anonymousId: '00000000000000000000000000',
              integrations: { All: true },
              sentAt: '2019-10-14T09:03:22.563Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'setUserAttributes' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '00000000000000000000000000',
                  newUserId: 'some_developer_id',
                  userAttributes: {
                    id: 'some_developer_id',
                    createAt: '2019-10-14T09:03:17.562Z',
                    address: { country: 'USA', city: 'NY' },
                    country: 'India',
                    city: 'Delhi',
                  },
                  created: 1571043798,
                  locale: 'en-US',
                  country: 'USA',
                  city: 'NY',
                  time: 1571043798,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '00000000000000000000000000',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 9',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 10',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'MainActivity',
              integrations: { All: true },
              messageId: 'id1',
              properties: { automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'advance' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  state: 'MainActivity',
                  deviceId: '5094f5704b9cf2b3',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 11',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              integrations: { All: true },
              messageId: 'id1',
              properties: { automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'screen',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Missing required value from ["properties.name","event"]',
            statTags: {
              destType: 'LEANPLUM',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 12',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'account: logged out',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'track',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'track' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  event: 'account: logged out',
                  deviceId: '5094f5704b9cf2b3',
                  params: { name: 'MainActivity', automatic: true },
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'leanplum',
    description: 'Test 13',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '5094f5704b9cf2b3',
              channel: 'mobile',
              context: {
                app: {
                  build: '1',
                  name: 'LeanPlumIntegrationAndroid',
                  namespace: 'com.android.SampleLeanPlum',
                  version: '1.0',
                },
                device: {
                  id: '5094f5704b9cf2b3',
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '1.0.1-beta.1' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                os: { name: 'Android', version: '8.1.0' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Kolkata',
                traits: { anonymousId: '5094f5704b9cf2b3' },
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.007)',
              },
              event: 'account: logged out',
              integrations: { All: true },
              messageId: 'id1',
              properties: { name: 'MainActivity', automatic: true, total: 2.45, currency: 'USD' },
              originalTimestamp: '2020-03-12T09:05:03.421Z',
              type: 'track',
              sentAt: '2020-03-12T09:05:13.042Z',
            },
            destination: {
              Config: {
                applicationId: 'leanplum_application_id',
                clientKey: 'leanplum_client_key',
                isDevelop: true,
                useNativeSDK: false,
                sendEvents: false,
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'start' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  deviceId: '5094f5704b9cf2b3',
                  appVersion: '1.0',
                  systemName: 'Android',
                  systemVersion: '8.1.0',
                  deviceName: 'generic_x86',
                  deviceModel: 'Android SDK built for x86',
                  userAttributes: { anonymousId: '5094f5704b9cf2b3' },
                  locale: 'en-US',
                  timezone: 'Asia/Kolkata',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.leanplum.com/api',
              headers: { 'Content-Type': 'application/json' },
              params: { action: 'track' },
              body: {
                JSON: {
                  apiVersion: '1.0.6',
                  appId: 'leanplum_application_id',
                  clientKey: 'leanplum_client_key',
                  userId: '5094f5704b9cf2b3',
                  event: 'account: logged out',
                  deviceId: '5094f5704b9cf2b3',
                  params: { name: 'MainActivity', automatic: true, total: 2.45, currency: 'USD' },
                  value: 2.45,
                  currencyCode: 'USD',
                  time: 1584003903,
                  devMode: true,
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '5094f5704b9cf2b3',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
];
