export const networkCallsData = [
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/organization_fields.json',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        organization_fields: [
          {
            active: true,
            created_at: '2020-03-23T18:14:35Z',
            description: 'email',
            id: 900000015126,
            key: 'email',
            position: 0,
            raw_description: 'email',
            raw_title: 'email',
            regexp_for_validation: null,
            system: false,
            title: 'email',
            type: 'text',
            updated_at: '2020-03-23T18:14:35Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/organization_fields/900000015126.json',
          },
        ],
        previous_page: null,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        organization: {
          domain_names: 'cw124.com',
          external_id: 'group-124',
          name: 'test-org124',
          organization_fields: { email: 'group_email_124@xyz.com', id: 'group-124' },
        },
      },
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/organizations/create_or_update.json',
    },
    httpRes: {
      data: {
        organization: {
          created_at: '2020-03-17T10:21:14Z',
          details: null,
          domain_names: ['cw124.com'],
          external_id: 'group-124',
          group_id: null,
          id: 900001329943,
          name: 'test-org124',
          notes: null,
          organization_fields: { email: 'group_email_124@xyz.com' },
          shared_comments: false,
          shared_tickets: false,
          tags: [],
          updated_at: '2020-03-23T19:33:08Z',
          url: 'https://rudderlabshelp.zendesk.com/api/v2/organizations/900001329943.json',
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=example124@email.com',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        previous_page: null,
        users: [
          {
            active: true,
            alias: null,
            chat_only: false,
            created_at: '2020-03-17T10:21:15Z',
            custom_role_id: null,
            default_group_id: null,
            details: null,
            email: 'example124@email.com',
            external_id: 'abcd-124',
            iana_time_zone: 'America/New_York',
            id: 900113780483,
            last_login_at: null,
            locale: 'en-US',
            locale_id: 1,
            moderator: false,
            name: 'abcd124',
            notes: null,
            only_private_comments: false,
            organization_id: null,
            phone: null,
            photo: null,
            report_csv: false,
            restricted_agent: true,
            role: 'end-user',
            role_type: null,
            shared: false,
            shared_agent: false,
            shared_phone_number: null,
            signature: null,
            suspended: false,
            tags: [],
            ticket_restriction: 'requested',
            time_zone: 'Eastern Time (US & Canada)',
            two_factor_auth_enabled: false,
            updated_at: '2020-03-17T12:16:59Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
            user_fields: { birthday: null },
            verified: true,
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2//users/900113780483/organization_memberships.json',
    },
    httpRes: { error: 'Request failed' },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic cnVkZGVybGFidGVzdDJAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabtest2.zendesk.com/api/v2/users/search.json?query=testemail2@email',
    },
    httpRes: { data: { count: 0, next_page: null, previous_page: null, users: [] }, status: 200 },
  },
  {
    httpReq: {
      data: {
        user: {
          email: 'testemail2@email',
          external_id: '0000000000',
          name: 'John Wick',
          verified: true,
        },
      },
      headers: {
        Authorization: 'Basic cnVkZGVybGFidGVzdDJAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabtest2.zendesk.com/api/v2/users/create_or_update.json',
    },
    httpRes: { data: { user: {} }, status: 200 },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/organization_fields.json',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        organization_fields: [
          {
            active: true,
            created_at: '2020-03-23T18:14:35Z',
            description: 'email',
            id: 900000015126,
            key: 'email',
            position: 0,
            raw_description: 'email',
            raw_title: 'email',
            regexp_for_validation: null,
            system: false,
            title: 'email',
            type: 'text',
            updated_at: '2020-03-23T18:14:35Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/organization_fields/900000015126.json',
          },
        ],
        previous_page: null,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        organization: {
          domain_names: 'cw124.com',
          external_id: 'group-124',
          name: 'test-org124',
          organization_fields: { email: 'group_email_124@xyz.com', id: 'group-124' },
        },
      },
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/organizations/create_or_update.json',
    },
    httpRes: {
      data: {
        organization: {
          created_at: '2020-03-17T10:21:14Z',
          details: null,
          domain_names: ['cw124.com'],
          external_id: 'group-124',
          group_id: null,
          id: 900001329943,
          name: 'test-org124',
          notes: null,
          organization_fields: { email: 'group_email_124@xyz.com' },
          shared_comments: false,
          shared_tickets: false,
          tags: [],
          updated_at: '2020-03-23T19:33:08Z',
          url: 'https://rudderlabshelp.zendesk.com/api/v2/organizations/900001329943.json',
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=example124@email.com',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        previous_page: null,
        users: [
          {
            active: true,
            alias: null,
            chat_only: false,
            created_at: '2020-03-17T10:21:15Z',
            custom_role_id: null,
            default_group_id: null,
            details: null,
            email: 'example124@email.com',
            external_id: 'abcd-124',
            iana_time_zone: 'America/New_York',
            id: 900113780483,
            last_login_at: null,
            locale: 'en-US',
            locale_id: 1,
            moderator: false,
            name: 'abcd124',
            notes: null,
            only_private_comments: false,
            organization_id: null,
            phone: null,
            photo: null,
            report_csv: false,
            restricted_agent: true,
            role: 'end-user',
            role_type: null,
            shared: false,
            shared_agent: false,
            shared_phone_number: null,
            signature: null,
            suspended: false,
            tags: [],
            ticket_restriction: 'requested',
            time_zone: 'Eastern Time (US & Canada)',
            two_factor_auth_enabled: false,
            updated_at: '2020-03-17T12:16:59Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
            user_fields: { birthday: null },
            verified: true,
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2//users/900113780483/organization_memberships.json',
    },
    httpRes: { error: 'Request failed' },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=example124@email.com',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        previous_page: null,
        users: [
          {
            active: true,
            alias: null,
            chat_only: false,
            created_at: '2020-03-17T10:21:15Z',
            custom_role_id: null,
            default_group_id: null,
            details: null,
            email: 'example124@email.com',
            external_id: 'abcd-124',
            iana_time_zone: 'America/New_York',
            id: 900113780483,
            last_login_at: null,
            locale: 'en-US',
            locale_id: 1,
            moderator: false,
            name: 'abcd124',
            notes: null,
            only_private_comments: false,
            organization_id: null,
            phone: null,
            photo: null,
            report_csv: false,
            restricted_agent: true,
            role: 'end-user',
            role_type: null,
            shared: false,
            shared_agent: false,
            shared_phone_number: null,
            signature: null,
            suspended: false,
            tags: [],
            ticket_restriction: 'requested',
            time_zone: 'Eastern Time (US & Canada)',
            two_factor_auth_enabled: false,
            updated_at: '2020-03-17T12:16:59Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
            user_fields: { birthday: null },
            verified: true,
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=example124@email.com',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        previous_page: null,
        users: [
          {
            active: true,
            alias: null,
            chat_only: false,
            created_at: '2020-03-17T10:21:15Z',
            custom_role_id: null,
            default_group_id: null,
            details: null,
            email: 'example124@email.com',
            external_id: 'abcd-124',
            iana_time_zone: 'America/New_York',
            id: 900113780483,
            last_login_at: null,
            locale: 'en-US',
            locale_id: 1,
            moderator: false,
            name: 'abcd124',
            notes: null,
            only_private_comments: false,
            organization_id: null,
            phone: null,
            photo: null,
            report_csv: false,
            restricted_agent: true,
            role: 'end-user',
            role_type: null,
            shared: false,
            shared_agent: false,
            shared_phone_number: null,
            signature: null,
            suspended: false,
            tags: [],
            ticket_restriction: 'requested',
            time_zone: 'Eastern Time (US & Canada)',
            two_factor_auth_enabled: false,
            updated_at: '2020-03-17T12:16:59Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
            user_fields: { birthday: null },
            verified: true,
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/organization_memberships.json',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        organization_memberships: [
          {
            created_at: '2020-03-23T15:56:56Z',
            default: true,
            id: 900004877903,
            organization_id: 900001329943,
            updated_at: '2020-03-23T15:56:56Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/organization_memberships/900004877903.json',
            user_id: 900113780483,
          },
        ],
        previous_page: null,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=example124@email.com',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        previous_page: null,
        users: [
          {
            active: true,
            alias: null,
            chat_only: false,
            created_at: '2020-03-17T10:21:15Z',
            custom_role_id: null,
            default_group_id: null,
            details: null,
            email: 'example124@email.com',
            external_id: 'abcd-124',
            iana_time_zone: 'America/New_York',
            id: 900113780483,
            last_login_at: null,
            locale: 'en-US',
            locale_id: 1,
            moderator: false,
            name: 'abcd124',
            notes: null,
            only_private_comments: false,
            organization_id: null,
            phone: null,
            photo: null,
            report_csv: false,
            restricted_agent: true,
            role: 'end-user',
            role_type: null,
            shared: false,
            shared_agent: false,
            shared_phone_number: null,
            signature: null,
            suspended: false,
            tags: [],
            ticket_restriction: 'requested',
            time_zone: 'Eastern Time (US & Canada)',
            two_factor_auth_enabled: false,
            updated_at: '2020-03-17T12:16:59Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
            user_fields: { birthday: null },
            verified: true,
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/organization_memberships.json',
    },
    httpRes: {
      data: {
        count: 1,
        next_page: null,
        organization_memberships: [
          {
            created_at: '2020-03-23T15:56:56Z',
            default: true,
            id: 900004877903,
            organization_id: 900001329943,
            updated_at: '2020-03-23T15:56:56Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/organization_memberships/900004877903.json',
            user_id: 900113780483,
          },
        ],
        previous_page: null,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        user_field: { active: true, description: 'country', key: 'country', title: 'country' },
      },
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        user_field: { active: true, description: 'country', key: 'country', title: 'country' },
      },
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        user_field: { active: true, description: 'country', key: 'country', title: 'country' },
      },
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=johnwick@example.com',
    },
    httpRes: { error: 'Request failed', status: 200 },
  },
  {
    httpReq: {
      data: {
        user: {
          email: 'johnwick@example.com',
          external_id: '0000000000',
          name: 'John Wick',
          verified: true,
        },
      },
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjM=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
    },
    httpRes: {
      data: {
        user: {
          active: true,
          alias: null,
          chat_only: false,
          created_at: '2020-03-17T10:21:15Z',
          custom_role_id: null,
          default_group_id: null,
          details: null,
          email: 'example124@email.com',
          external_id: 'abcd-124',
          iana_time_zone: 'America/New_York',
          id: 900113780483,
          last_login_at: null,
          locale: 'en-US',
          locale_id: 1,
          moderator: false,
          name: 'abcd124',
          notes: null,
          only_private_comments: false,
          organization_id: 900001329943,
          phone: null,
          photo: null,
          report_csv: false,
          restricted_agent: true,
          role: 'end-user',
          role_type: null,
          shared: false,
          shared_agent: false,
          shared_phone_number: null,
          signature: null,
          suspended: false,
          tags: [],
          ticket_restriction: 'requested',
          time_zone: 'Eastern Time (US & Canada)',
          two_factor_auth_enabled: false,
          updated_at: '2020-03-23T15:56:56Z',
          url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
          user_fields: { birthday: null },
          verified: true,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjM=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=johnwick@example.com',
    },
    httpRes: { error: 'Request failed', status: 200 },
  },
  {
    httpReq: {
      data: {
        user: {
          email: 'johnwick@example.com',
          external_id: '0000000000',
          name: 'John Wick',
          verified: true,
        },
      },
      headers: {
        Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjM=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
    },
    httpRes: {
      data: {
        user: {
          active: true,
          alias: null,
          chat_only: false,
          created_at: '2020-03-17T10:21:15Z',
          custom_role_id: null,
          default_group_id: null,
          details: null,
          email: 'example124@email.com',
          external_id: 'abcd-124',
          iana_time_zone: 'America/New_York',
          id: 900113780483,
          last_login_at: null,
          locale: 'en-US',
          locale_id: 1,
          moderator: false,
          name: 'abcd124',
          notes: null,
          only_private_comments: false,
          organization_id: 900001329943,
          phone: null,
          photo: null,
          report_csv: false,
          restricted_agent: true,
          role: 'end-user',
          role_type: null,
          shared: false,
          shared_agent: false,
          shared_phone_number: null,
          signature: null,
          suspended: false,
          tags: [],
          ticket_restriction: 'requested',
          time_zone: 'Eastern Time (US & Canada)',
          two_factor_auth_enabled: false,
          updated_at: '2020-03-23T15:56:56Z',
          url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483.json',
          user_fields: { birthday: null },
          verified: true,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMi90b2tlbjpteUR1bW15QXBpVG9rZW4y',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://blendohelp.zendesk.com/api/v2/organization_fields.json',
    },
    httpRes: { error: 'Request failed', status: 200 },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields.json',
    },
    httpRes: {
      data: {
        count: 3,
        next_page: null,
        previous_page: null,
        user_fields: [
          {
            active: true,
            created_at: '2020-03-18T08:19:58Z',
            description: 'birthday',
            id: 900000013606,
            key: 'birthday',
            position: 0,
            raw_description: 'birthday',
            raw_title: 'birthday',
            regexp_for_validation: null,
            system: false,
            title: 'birthday',
            type: 'text',
            updated_at: '2020-03-18T08:19:58Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000013606.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'age',
            id: 900000014483,
            key: 'age',
            position: 1,
            raw_description: 'age',
            raw_title: 'age',
            regexp_for_validation: null,
            system: false,
            title: 'age',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000014483.json',
          },
          {
            active: true,
            created_at: '2020-03-23T17:38:44Z',
            description: 'firstname',
            id: 900000015106,
            key: 'firstname',
            position: 2,
            raw_description: 'firstname',
            raw_title: 'firstname',
            regexp_for_validation: null,
            system: false,
            title: 'firstname',
            type: 'text',
            updated_at: '2020-03-23T17:38:44Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/user_fields/900000015106.json',
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/search.json?query=abcd-144',
    },
    httpRes: {
      data: {
        count: 1,
        facets: null,
        next_page: null,
        previous_page: null,
        users: [
          {
            active: true,
            alias: null,
            created_at: '2022-11-24T09:03:54Z',
            custom_role_id: null,
            default_group_id: null,
            details: null,
            email: 'test1000@email.com',
            external_id: 'abcd-144',
            iana_time_zone: 'Asia/Kolkata',
            id: 900113780483,
            last_login_at: null,
            locale: 'en-US',
            locale_id: 1,
            moderator: false,
            name: 'name-1000 user',
            notes: null,
            only_private_comments: false,
            organization_id: null,
            phone: null,
            photo: null,
            report_csv: false,
            restricted_agent: true,
            result_type: 'user',
            role: 'end-user',
            role_type: null,
            shared: false,
            shared_agent: false,
            shared_phone_number: null,
            signature: null,
            suspended: false,
            tags: [],
            ticket_restriction: 'requested',
            time_zone: 'Asia/Kolkata',
            two_factor_auth_enabled: false,
            updated_at: '2022-11-24T09:03:54Z',
            url: 'https://rudderstack6787.zendesk.com/api/v2/users/10865192864273.json',
            user_fields: {},
            verified: true,
          },
        ],
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/identities',
    },
    httpRes: {
      data: {
        count: 2,
        identities: [
          {
            created_at: '2022-11-02T08:03:28Z',
            deliverable_state: 'deliverable',
            id: 7535981118877,
            primary: true,
            type: 'email',
            undeliverable_count: 0,
            updated_at: '2022-11-02T10:23:28Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/7533979645597/identities/7535981118877.json',
            user_id: 900113780483,
            value: 'example119@email.com',
            verified: false,
          },
          {
            created_at: '2022-11-02T04:23:46Z',
            deliverable_state: 'deliverable',
            id: 7534173321117,
            primary: false,
            type: 'email',
            undeliverable_count: 0,
            updated_at: '2022-11-02T10:23:28Z',
            url: 'https://rudderlabshelp.zendesk.com/api/v2/users/7533979645597/identities/7534173321117.json',
            user_id: 900113780483,
            value: 'example115@email.com',
            verified: true,
          },
        ],
        next_page: null,
        previous_page: null,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic cnVkZGVybGFidGVzdDFAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabtest1.zendesk.com/api/v2/users/search.json?query=testemail1@email',
    },
    httpRes: { data: { count: 0, next_page: null, previous_page: null, users: [] }, status: 200 },
  },
  {
    httpReq: {
      data: {
        user: {
          email: 'testemail1@email',
          external_id: '0000000000',
          name: 'John Wick',
          verified: true,
        },
      },
      headers: {
        Authorization: 'Basic cnVkZGVybGFidGVzdDFAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabtest1.zendesk.com/api/v2/users/create_or_update.json',
    },
    httpRes: {
      data: {
        user: {
          active: true,
          alias: null,
          chat_only: false,
          created_at: '2020-03-17T10:21:15Z',
          custom_role_id: null,
          default_group_id: null,
          details: null,
          email: 'testemail1@email',
          external_id: 'exId-123',
          iana_time_zone: 'America/New_York',
          id: 900113780483,
          last_login_at: null,
          locale: 'en-US',
          locale_id: 1,
          moderator: false,
          name: 'John Wick',
          notes: null,
          only_private_comments: false,
          organization_id: 900001329943,
          phone: null,
          photo: null,
          report_csv: false,
          restricted_agent: true,
          role: 'end-user',
          role_type: null,
          shared: false,
          shared_agent: false,
          shared_phone_number: null,
          signature: null,
          suspended: false,
          tags: [],
          ticket_restriction: 'requested',
          time_zone: 'Eastern Time (US & Canada)',
          two_factor_auth_enabled: false,
          updated_at: '2020-03-23T15:56:56Z',
          url: 'https://rudderlabtest1.zendesk.com/api/v2/users/900113780483.json',
          user_fields: { birthday: null },
          verified: true,
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Basic cnVkZGVybGFidGVzdDJAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
        'Content-Type': 'application/json',
      },
      method: 'GET',
      url: 'https://rudderlabtest2.zendesk.com/api/v2/users/search.json?query=testemail2@email',
    },
    httpRes: { data: { count: 0, next_page: null, previous_page: null, users: [] }, status: 200 },
  },
  {
    httpReq: {
      data: {
        user: {
          email: 'testemail2@email',
          external_id: '0000000000',
          name: 'John Wick',
          verified: true,
        },
      },
      headers: {
        Authorization: 'Basic cnVkZGVybGFidGVzdDJAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
        'Content-Type': 'application/json',
      },
      method: 'POST',
      url: 'https://rudderlabtest2.zendesk.com/api/v2/users/create_or_update.json',
    },
    httpRes: { data: { user: {} }, status: 200 },
  },
];
