export const networkCallsData = [
  {
    httpReq: {
      url: 'https://api.aptrinsic.com/v1/users/sample-user-id',
      method: 'GET',
    },
    httpRes: {
      data: {
        aptrinsicId: '347c4c87-98c7-4ca6-a6da-678ed6924c22',
        identifyId: 'sample-user-id',
        type: 'USER',
        gender: 'MALE',
        email: 'user@email.com',
        firstName: 'Sample',
        lastName: 'User',
        lastSeenDate: 0,
        signUpDate: 1624431528295,
        firstVisitDate: 0,
        title: 'engineer',
        phone: '',
        score: 0,
        role: '',
        subscriptionId: '',
        accountId: '',
        numberOfVisits: 1,
        location: {
          countryName: 'USA',
          countryCode: 'US',
          stateName: '',
          stateCode: '',
          city: 'New York',
          street: '',
          postalCode: '',
          continent: '',
          regionName: '',
          timeZone: '',
          coordinates: {
            latitude: 0.0,
            longitude: 0.0,
          },
        },
        propertyKeys: ['AP-XABC-123'],
        createDate: 1624431528295,
        lastModifiedDate: 1624431528295,
        customAttributes: null,
        globalUnsubscribe: false,
        sfdcContactId: '',
        lastVisitedUserAgentData: null,
        id: 'sample-user-id',
        lastInferredLocation: {
          countryName: '',
          countryCode: '',
          stateName: '',
          stateCode: '',
          city: '',
          street: '',
          postalCode: '',
          continent: '',
          regionName: '',
          timeZone: '',
          coordinates: {
            latitude: 0.0,
            longitude: 0.0,
          },
        },
      },
      status: 200,
    },
  },
  {
    httpReq: {
      url: 'https://api.aptrinsic.com/v1/accounts/ecorp-id',
      method: 'GET',
    },
    httpRes: {
      data: {
        id: 'ecorp-id',
        name: 'ECorp',
        trackedSubscriptionId: '',
        sfdcId: '',
        lastSeenDate: 0,
        dunsNumber: '',
        industry: 'software',
        numberOfEmployees: 400,
        sicCode: '',
        website: 'www.ecorp.com',
        naicsCode: '',
        plan: 'premium',
        location: {
          countryName: '',
          countryCode: '',
          stateName: '',
          stateCode: '',
          city: '',
          street: '',
          postalCode: '',
          continent: '',
          regionName: '',
          timeZone: '',
          coordinates: {
            latitude: 0.0,
            longitude: 0.0,
          },
        },
        numberOfUsers: 0,
        propertyKeys: ['AP-XABC-123'],
        createDate: 1624261864923,
        lastModifiedDate: 1624261864923,
        customAttributes: null,
        parentGroupId: '',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      url: 'https://api.aptrinsic.com/v1/accounts/ecorp-id',
      method: 'PUT',
    },
    httpRes: {
      data: {
        id: 'ecorp-id',
        name: 'ECorp',
        trackedSubscriptionId: '',
        sfdcId: '',
        lastSeenDate: 0,
        dunsNumber: '',
        industry: 'software',
        numberOfEmployees: 400,
        sicCode: '',
        website: 'www.ecorp.com',
        naicsCode: '',
        plan: 'premium',
        location: {
          countryName: '',
          countryCode: '',
          stateName: '',
          stateCode: '',
          city: '',
          street: '',
          postalCode: '',
          continent: '',
          regionName: '',
          timeZone: '',
          coordinates: {
            latitude: 0.0,
            longitude: 0.0,
          },
        },
        numberOfUsers: 0,
        propertyKeys: ['AP-XABC-123'],
        createDate: 1624261864923,
        lastModifiedDate: 1624261864923,
        customAttributes: null,
        parentGroupId: '',
      },
      status: 204,
    },
  },
  {
    httpReq: {
      url: 'https://api.aptrinsic.com/v1/users/absent-id',
      method: 'GET',
    },
    httpRes: {
      data: {
        externalapierror: {
          status: 'NOT_FOUND',
          message: 'User was not found for parameters {id=absent-id}',
          debugMessage: null,
          subErrors: null,
        },
      },
      status: 404,
    },
  },
  {
    httpReq: {
      url: 'https://api.aptrinsic.com/v1/users/stanley-kubrick',
      method: 'GET',
    },
    httpRes: {
      data: {
        id: 'ecorp-id',
        name: 'ECorp',
        trackedSubscriptionId: '',
        sfdcId: '',
        lastSeenDate: 0,
        dunsNumber: '',
        industry: 'software',
        numberOfEmployees: 400,
        sicCode: '',
        website: 'www.ecorp.com',
        naicsCode: '',
        plan: 'premium',
        location: {
          countryName: '',
          countryCode: '',
          stateName: '',
          stateCode: '',
          city: '',
          street: '',
          postalCode: '',
          continent: '',
          regionName: '',
          timeZone: '',
          coordinates: {
            latitude: 0.0,
            longitude: 0.0,
          },
        },
        numberOfUsers: 0,
        propertyKeys: ['AP-XABC-123'],
        createDate: 1624261864923,
        lastModifiedDate: 1624261864923,
        customAttributes: null,
        parentGroupId: '',
      },
      status: 200,
    },
  },
  // Axios Error
  {
    httpReq: {
      url: 'https://api.aptrinsic.com/v1/users/myUId',
      headers: { 'X-APTRINSIC-API-KEY': 'sample-api-key', 'Content-Type': 'application/json' },
      method: 'GET',
    },
    httpRes: {
      message: 'Request failed with status code 403',
      name: 'AxiosError',
      stack:
        'AxiosError: Request failed with status code 403\n    at settle (/Users/saisankeerth/rudderstack/rudder-transformer/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/Users/saisankeerth/rudderstack/rudder-transformer/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:529:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)',
      config: {
        headers: {
          Accept: 'application/json, text/plain, */*',
          'Content-Type': 'application/json',
          'X-APTRINSIC-API-KEY': 'sample-api-key',
          'User-Agent': 'axios/1.6.5',
          'Accept-Encoding': 'gzip, compress, deflate, br',
        },
        method: 'get',
        dummy: 'upgrade required', // keyword
        url: 'https://api.aptrinsic.com/v1/users/myUId',
      },
      code: 'FORBIDDEN',
      status: 403,
      data: '\u003c!doctype html\u003e\u003cmeta charset="utf-8"\u003e\u003cmeta name=viewport content="width=device-width, initial-scale=1"\u003e\u003ctitle\u003e403\u003c/title\u003e403 Forbidden',
    },
  },
];
