import { RouterTestData } from '../../../testTypes';
import { authHeader1, authHeaderStaging1, secret1, secretStaging1 } from '../maskedSecrets';

export const data: RouterTestData[] = [
  {
    id: 'accoil-analytics-destination-router-100',
    name: 'accoil_analytics',
    description: 'Router batch request',
    scenario: 'Scenario which tests for a successful batch request',
    successCriteria: 'Router test should pass successfully',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: {
          input: [
            {
              destination: {
                ID: 'default-destination-id',
                Name: 'Default Destination',
                Config: {
                  apiKey: secret1,
                },
                DestinationDefinition: {
                  ID: 'default-dest-def-id',
                  Name: 'Default Destination Definition',
                  DisplayName: 'Default Display Name',
                  Config: {
                    cdkV2Enabled: true,
                  },
                },
                Enabled: true,
                WorkspaceID: 'default-workspace',
                Transformations: [],
                RevisionID: 'default-revision',
                IsProcessorEnabled: true,
                IsConnectionEnabled: true,
              },
              message: {
                userId: 'user-uuid',
                event: 'User Signed Up',
                type: 'track',
                timestamp: '2024-01-23T08:35:17.562Z',
              },
              metadata: {
                sourceId: 'default-source',
                workspaceId: 'default-workspace',
                namespace: 'default-namespace',
                instanceId: 'default-instance',
                sourceType: 'default-source-type',
                sourceCategory: 'default-category',
                trackingPlanId: 'default-tracking-plan',
                trackingPlanVersion: 1,
                sourceTpConfig: {},
                mergedTpConfig: {},
                destinationId: 'default-destination',
                jobRunId: 'default-job-run',
                jobId: 1,
                sourceBatchId: 'default-batch',
                sourceJobId: 'default-source-job',
                sourceJobRunId: 'default-source-job-run',
                sourceTaskId: 'default-task',
                sourceTaskRunId: 'default-task-run',
                recordId: {},
                destinationType: 'default-destination-type',
                messageId: 'default-message-id',
                oauthAccessToken: 'default-token',
                messageIds: ['default-message-id'],
                rudderId: 'default-rudder-id',
                receivedAt: '2024-12-06T12:28:58.577Z',
                eventName: 'default-event',
                eventType: 'default-type',
                sourceDefinitionId: 'default-source-def',
                destinationDefinitionId: 'default-dest-def',
                transformationId: 'default-transform',
                dontBatch: false,
              },
            },
            {
              destination: {
                ID: 'default-destination-id',
                Name: 'Default Destination',
                Config: {
                  apiKey: secret1,
                },
                DestinationDefinition: {
                  ID: 'default-dest-def-id',
                  Name: 'Default Destination Definition',
                  DisplayName: 'Default Display Name',
                  Config: {
                    cdkV2Enabled: true,
                  },
                },
                Enabled: true,
                WorkspaceID: 'default-workspace',
                Transformations: [],
                RevisionID: 'default-revision',
                IsProcessorEnabled: true,
                IsConnectionEnabled: true,
              },
              message: {
                userId: 'user-uuid',
                event: 'User Deleted account',
                type: 'track',
                messageId: '8bc79b03-2a5c-4615-b2da-54c0aaaaaae8',
                timestamp: '2024-01-23T08:35:17.562Z',
              },
              metadata: {
                sourceId: 'default-source',
                workspaceId: 'default-workspace',
                namespace: 'default-namespace',
                instanceId: 'default-instance',
                sourceType: 'default-source-type',
                sourceCategory: 'default-category',
                trackingPlanId: 'default-tracking-plan',
                trackingPlanVersion: 1,
                sourceTpConfig: {},
                mergedTpConfig: {},
                destinationId: 'default-destination',
                jobRunId: 'default-job-run',
                jobId: 2,
                sourceBatchId: 'default-batch',
                sourceJobId: 'default-source-job',
                sourceJobRunId: 'default-source-job-run',
                sourceTaskId: 'default-task',
                sourceTaskRunId: 'default-task-run',
                recordId: {},
                destinationType: 'default-destination-type',
                messageId: 'default-message-id',
                oauthAccessToken: 'default-token',
                messageIds: ['default-message-id'],
                rudderId: 'default-rudder-id',
                receivedAt: '2024-12-06T12:28:58.577Z',
                eventName: 'default-event',
                eventType: 'default-type',
                sourceDefinitionId: 'default-source-def',
                destinationDefinitionId: 'default-dest-def',
                transformationId: 'default-transform',
                dontBatch: false,
              },
            },
            {
              destination: {
                ID: 'default-destination-id',
                Name: 'Default Destination',
                Config: {
                  apiKey: secretStaging1,
                },
                DestinationDefinition: {
                  ID: 'default-dest-def-id',
                  Name: 'Default Destination Definition',
                  DisplayName: 'Default Display Name',
                  Config: {
                    cdkV2Enabled: true,
                  },
                },
                Enabled: true,
                WorkspaceID: 'default-workspace',
                Transformations: [],
                RevisionID: 'default-revision',
                IsProcessorEnabled: true,
                IsConnectionEnabled: true,
              },
              message: {
                userId: 'user-uuid',
                event: 'User Deleted account',
                type: 'track',
                messageId: '8bc79b03-2a5c-4615-b2da-54c0aaaaaae8',
                timestamp: '2024-01-23T08:35:17.562Z',
              },
              metadata: {
                sourceId: 'default-source',
                workspaceId: 'default-workspace',
                namespace: 'default-namespace',
                instanceId: 'default-instance',
                sourceType: 'default-source-type',
                sourceCategory: 'default-category',
                trackingPlanId: 'default-tracking-plan',
                trackingPlanVersion: 1,
                sourceTpConfig: {},
                mergedTpConfig: {},
                destinationId: 'default-destination',
                jobRunId: 'default-job-run',
                jobId: 3,
                sourceBatchId: 'default-batch',
                sourceJobId: 'default-source-job',
                sourceJobRunId: 'default-source-job-run',
                sourceTaskId: 'default-task',
                sourceTaskRunId: 'default-task-run',
                recordId: {},
                destinationType: 'default-destination-type',
                messageId: 'default-message-id',
                oauthAccessToken: 'default-token',
                messageIds: ['default-message-id'],
                rudderId: 'default-rudder-id',
                receivedAt: '2024-12-06T12:28:58.577Z',
                eventName: 'default-event',
                eventType: 'default-type',
                sourceDefinitionId: 'default-source-def',
                destinationDefinitionId: 'default-dest-def',
                transformationId: 'default-transform',
                dontBatch: false,
              },
            },
          ],
          destType: 'accoil_analytics',
        },
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: {
                body: {
                  FORM: {},
                  JSON_ARRAY: {},
                  XML: {},
                  JSON: {
                    userId: 'user-uuid',
                    type: 'track',
                    event: 'User Signed Up',
                    timestamp: '2024-01-23T08:35:17.562Z',
                  },
                },
                endpoint: 'https://in.accoil.com/segment',
                files: {},
                params: {},
                type: 'REST',
                version: '1',
                method: 'POST',
                headers: {
                  Authorization: authHeader1,
                  'Content-Type': 'application/json',
                },
              },
              batched: false,
              metadata: [
                {
                  sourceId: 'default-source',
                  workspaceId: 'default-workspace',
                  namespace: 'default-namespace',
                  instanceId: 'default-instance',
                  sourceType: 'default-source-type',
                  sourceCategory: 'default-category',
                  trackingPlanId: 'default-tracking-plan',
                  trackingPlanVersion: 1,
                  sourceTpConfig: {},
                  mergedTpConfig: {},
                  destinationId: 'default-destination',
                  jobRunId: 'default-job-run',
                  jobId: 1,
                  sourceBatchId: 'default-batch',
                  sourceJobId: 'default-source-job',
                  sourceJobRunId: 'default-source-job-run',
                  sourceTaskId: 'default-task',
                  sourceTaskRunId: 'default-task-run',
                  recordId: {},
                  destinationType: 'default-destination-type',
                  messageId: 'default-message-id',
                  oauthAccessToken: 'default-token',
                  messageIds: ['default-message-id'],
                  rudderId: 'default-rudder-id',
                  receivedAt: '2024-12-06T12:28:58.577Z',
                  eventName: 'default-event',
                  eventType: 'default-type',
                  sourceDefinitionId: 'default-source-def',
                  destinationDefinitionId: 'default-dest-def',
                  transformationId: 'default-transform',
                  dontBatch: false,
                },
              ],
              statusCode: 200,
              destination: {
                ID: 'default-destination-id',
                Name: 'Default Destination',
                Config: {
                  apiKey: secret1,
                },
                DestinationDefinition: {
                  ID: 'default-dest-def-id',
                  Name: 'Default Destination Definition',
                  DisplayName: 'Default Display Name',
                  Config: {
                    cdkV2Enabled: true,
                  },
                },
                Enabled: true,
                WorkspaceID: 'default-workspace',
                Transformations: [],
                RevisionID: 'default-revision',
                IsProcessorEnabled: true,
                IsConnectionEnabled: true,
              },
            },
            {
              batchedRequest: {
                body: {
                  FORM: {},
                  JSON_ARRAY: {},
                  XML: {},
                  JSON: {
                    userId: 'user-uuid',
                    type: 'track',
                    event: 'User Deleted account',
                    timestamp: '2024-01-23T08:35:17.562Z',
                  },
                },
                endpoint: 'https://in.accoil.com/segment',
                files: {},
                params: {},
                type: 'REST',
                version: '1',
                method: 'POST',
                headers: {
                  Authorization: authHeader1,
                  'Content-Type': 'application/json',
                },
              },
              batched: false,
              metadata: [
                {
                  sourceId: 'default-source',
                  workspaceId: 'default-workspace',
                  namespace: 'default-namespace',
                  instanceId: 'default-instance',
                  sourceType: 'default-source-type',
                  sourceCategory: 'default-category',
                  trackingPlanId: 'default-tracking-plan',
                  trackingPlanVersion: 1,
                  sourceTpConfig: {},
                  mergedTpConfig: {},
                  destinationId: 'default-destination',
                  jobRunId: 'default-job-run',
                  jobId: 2,
                  sourceBatchId: 'default-batch',
                  sourceJobId: 'default-source-job',
                  sourceJobRunId: 'default-source-job-run',
                  sourceTaskId: 'default-task',
                  sourceTaskRunId: 'default-task-run',
                  recordId: {},
                  destinationType: 'default-destination-type',
                  messageId: 'default-message-id',
                  oauthAccessToken: 'default-token',
                  messageIds: ['default-message-id'],
                  rudderId: 'default-rudder-id',
                  receivedAt: '2024-12-06T12:28:58.577Z',
                  eventName: 'default-event',
                  eventType: 'default-type',
                  sourceDefinitionId: 'default-source-def',
                  destinationDefinitionId: 'default-dest-def',
                  transformationId: 'default-transform',
                  dontBatch: false,
                },
              ],
              statusCode: 200,
              destination: {
                ID: 'default-destination-id',
                Name: 'Default Destination',
                Config: {
                  apiKey: secret1,
                },
                DestinationDefinition: {
                  ID: 'default-dest-def-id',
                  Name: 'Default Destination Definition',
                  DisplayName: 'Default Display Name',
                  Config: {
                    cdkV2Enabled: true,
                  },
                },
                Enabled: true,
                WorkspaceID: 'default-workspace',
                Transformations: [],
                RevisionID: 'default-revision',
                IsProcessorEnabled: true,
                IsConnectionEnabled: true,
              },
            },
            {
              batchedRequest: {
                body: {
                  FORM: {},
                  JSON_ARRAY: {},
                  XML: {},
                  JSON: {
                    userId: 'user-uuid',
                    type: 'track',
                    event: 'User Deleted account',
                    timestamp: '2024-01-23T08:35:17.562Z',
                  },
                },
                endpoint: 'https://instaging.accoil.com/segment',
                files: {},
                params: {},
                type: 'REST',
                version: '1',
                method: 'POST',
                headers: {
                  Authorization: authHeaderStaging1,
                  'Content-Type': 'application/json',
                },
              },
              batched: false,
              metadata: [
                {
                  sourceId: 'default-source',
                  workspaceId: 'default-workspace',
                  namespace: 'default-namespace',
                  instanceId: 'default-instance',
                  sourceType: 'default-source-type',
                  sourceCategory: 'default-category',
                  trackingPlanId: 'default-tracking-plan',
                  trackingPlanVersion: 1,
                  sourceTpConfig: {},
                  mergedTpConfig: {},
                  destinationId: 'default-destination',
                  jobRunId: 'default-job-run',
                  jobId: 3,
                  sourceBatchId: 'default-batch',
                  sourceJobId: 'default-source-job',
                  sourceJobRunId: 'default-source-job-run',
                  sourceTaskId: 'default-task',
                  sourceTaskRunId: 'default-task-run',
                  recordId: {},
                  destinationType: 'default-destination-type',
                  messageId: 'default-message-id',
                  oauthAccessToken: 'default-token',
                  messageIds: ['default-message-id'],
                  rudderId: 'default-rudder-id',
                  receivedAt: '2024-12-06T12:28:58.577Z',
                  eventName: 'default-event',
                  eventType: 'default-type',
                  sourceDefinitionId: 'default-source-def',
                  destinationDefinitionId: 'default-dest-def',
                  transformationId: 'default-transform',
                  dontBatch: false,
                },
              ],
              statusCode: 200,
              destination: {
                ID: 'default-destination-id',
                Name: 'Default Destination',
                Config: {
                  apiKey: secretStaging1,
                },
                DestinationDefinition: {
                  ID: 'default-dest-def-id',
                  Name: 'Default Destination Definition',
                  DisplayName: 'Default Display Name',
                  Config: {
                    cdkV2Enabled: true,
                  },
                },
                Enabled: true,
                WorkspaceID: 'default-workspace',
                Transformations: [],
                RevisionID: 'default-revision',
                IsProcessorEnabled: true,
                IsConnectionEnabled: true,
              },
            },
          ],
        },
      },
    },
  },
];
