export const data = [
  {
    name: 'candu',
    description: 'Test 0',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'identify',
              sentAt: '2022-01-20T13:39:21.033Z',
              userId: 'user123456001',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: '831f1fa5-de84-4f22-880a-4c3f23fc3f04',
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T13:39:21.032Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              userId: '',
              method: 'POST',
              endpoint: 'https://api.candu.ai/api/eventWebhook',
              headers: {
                Authorization: 'Basic RlhMa0xVRWhHSnl2bVk0',
                'Content-Type': 'application/json',
              },
              params: {},
              body: {
                JSON: {
                  traits: {
                    city: 'Pune',
                    name: 'First User',
                    email: 'firstUser@testmail.com',
                    title: 'VP',
                    gender: 'female',
                  },
                  type: 'identify',
                  userId: 'user123456001',
                  anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
                  messageId: '831f1fa5-de84-4f22-880a-4c3f23fc3f04',
                  context: {
                    source: 'RudderStack',
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 1',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'track',
              event: 'testEventWithoutProp',
              sentAt: '2022-01-20T14:32:51.506Z',
              userId: 'user123456001',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
              properties: {},
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T14:32:51.506Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              userId: '',
              method: 'POST',
              endpoint: 'https://api.candu.ai/api/eventWebhook',
              headers: {
                Authorization: 'Basic RlhMa0xVRWhHSnl2bVk0',
                'Content-Type': 'application/json',
              },
              params: {},
              body: {
                JSON: {
                  type: 'track',
                  event: 'testEventWithoutProp',
                  traits: {
                    city: 'Pune',
                    name: 'First User',
                    email: 'firstUser@testmail.com',
                    title: 'VP',
                    gender: 'female',
                  },
                  properties: {},
                  userId: 'user123456001',
                  anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
                  messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
                  context: {
                    source: 'RudderStack',
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 2',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'track',
              sentAt: '2022-01-20T14:42:59.775Z',
              userId: '',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '127.0.0.1:7307',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {},
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '1877191c-3537-46dc-a35a-e2a4d13ed3f7',
              messageId: 'fea245ef-6150-42c4-84e0-51fa68e71a88',
              properties: {},
              anonymousId: 'd18df757-34aa-4f71-91a8-7f9ef2940963',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T14:42:25.343Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            statusCode: 400,
            error: 'Missing required value from "event"',
            statTags: {
              destType: 'CANDU',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 3',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'page',
              sentAt: '2022-01-20T15:30:57.470Z',
              userId: 'testUser1234',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '127.0.0.1:7307',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 632,
                },
                traits: {},
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: 'aa193f3b-6d42-466f-a781-6a666cfe17c3',
              messageId: 'bf869c14-5f96-4cbc-94b2-3de9252c216b',
              properties: {
                url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                title: 'Document',
                search: '',
                tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                initial_referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                referring_domain: '127.0.0.1:7307',
                initial_referring_domain: '127.0.0.1:7307',
              },
              anonymousId: 'd18df757-34aa-4f71-91a8-7f9ef2940963',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T15:30:57.470Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            statusCode: 400,
            error: '[CANDU]:: Message type page not supported.',
            statTags: {
              destType: 'CANDU',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 4',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: '  ',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'track',
              event: 'testEventWithoutProp',
              sentAt: '2022-01-20T14:32:51.506Z',
              userId: 'user123456001',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
              properties: {},
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T14:32:51.506Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            statusCode: 400,
            error: '[CANDU]:: apiKey cannot be empty.',
            statTags: {
              destType: 'CANDU',
              errorCategory: 'dataValidation',
              errorType: 'configuration',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 5',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              event: 'testEventWithoutProp',
              sentAt: '2022-01-20T14:32:51.506Z',
              userId: 'user123456001',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
              properties: {},
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T14:32:51.506Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            statusCode: 400,
            error: '[CANDU]:: Message Type is not present. Aborting message.',
            statTags: {
              destType: 'CANDU',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 6',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'identify',
              sentAt: '2022-01-20T13:39:21.033Z',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                  userId: 2399229,
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: '831f1fa5-de84-4f22-880a-4c3f23fc3f04',
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T13:39:21.032Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              userId: '',
              method: 'POST',
              endpoint: 'https://api.candu.ai/api/eventWebhook',
              headers: {
                Authorization: 'Basic RlhMa0xVRWhHSnl2bVk0',
                'Content-Type': 'application/json',
              },
              params: {},
              body: {
                JSON: {
                  traits: {
                    city: 'Pune',
                    name: 'First User',
                    email: 'firstUser@testmail.com',
                    title: 'VP',
                    gender: 'female',
                    userId: 2399229,
                  },
                  userId: '2399229',
                  anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
                  messageId: '831f1fa5-de84-4f22-880a-4c3f23fc3f04',
                  type: 'identify',
                  context: {
                    source: 'RudderStack',
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 7',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'track',
              event: 'testEventWithoutProp',
              sentAt: '2022-01-20T14:32:51.506Z',
              userId: 'user123456001',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
              properties: ['1234', '5678', '91011'],
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T14:32:51.506Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              userId: '',
              method: 'POST',
              endpoint: 'https://api.candu.ai/api/eventWebhook',
              headers: {
                Authorization: 'Basic RlhMa0xVRWhHSnl2bVk0',
                'Content-Type': 'application/json',
              },
              params: {},
              body: {
                JSON: {
                  event: 'testEventWithoutProp',
                  traits: {
                    city: 'Pune',
                    name: 'First User',
                    email: 'firstUser@testmail.com',
                    title: 'VP',
                    gender: 'female',
                  },
                  properties: ['1234', '5678', '91011'],
                  userId: 'user123456001',
                  anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
                  messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
                  type: 'track',
                  context: {
                    source: 'RudderStack',
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'candu',
    description: 'Test 8',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              ID: '23uZJcllEOBx8GbZ31qYzoML8Up',
              Name: 'Candu local',
              DestinationDefinition: {
                ID: '23uYPwdkxT7pUNDAiCVNK3aU0sT',
                Name: 'CANDU',
                DisplayName: 'Candu',
                Config: {
                  destConfig: {
                    defaultConfig: ['apiKey'],
                  },
                  excludeKeys: [],
                  includeKeys: [
                    'apiKey',
                    'blackListedEvents',
                    'whiteListedEvents',
                    'oneTrustCookieCategories',
                  ],
                  saveDestinationResponse: true,
                  secretKeys: ['apiKey'],
                  supportedMessageTypes: ['identify', 'track'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                    'flutter',
                    'cordova',
                  ],
                  transformAt: 'router',
                  transformAtV1: 'router',
                },
                ResponseRules: {},
              },
              Config: {
                apiKey: 'FXLkLUEhGJyvmY4',
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            message: {
              type: 'track',
              event: 'testEventWithoutProp',
              sentAt: '2022-01-20T14:32:51.506Z',
              userId: '',
              channel: 'web',
              context: {
                os: {
                  name: '',
                  version: '',
                },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.2.20',
                  namespace: 'com.rudderlabs.javascript',
                },
                page: {
                  url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  path: '/Testing/App_for_LaunchDarkly/ourSdk.html',
                  title: 'Document',
                  search: '',
                  tab_url: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/ourSdk.html',
                  referrer: 'http://127.0.0.1:7307/Testing/App_for_LaunchDarkly/',
                  initial_referrer: '$direct',
                  referring_domain: '127.0.0.1:7307',
                  initial_referring_domain: '',
                },
                locale: 'en-US',
                screen: {
                  width: 1440,
                  height: 900,
                  density: 2,
                  innerWidth: 536,
                  innerHeight: 689,
                },
                traits: {
                  city: 'Pune',
                  name: 'First User',
                  email: 'firstUser@testmail.com',
                  title: 'VP',
                  gender: 'female',
                },
                library: {
                  name: 'RudderLabs JavaScript SDK',
                  version: '1.2.20',
                },
                campaign: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
              },
              rudderId: '553b5522-c575-40a7-8072-9741c5f9a647',
              messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
              properties: [],
              anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
              integrations: {
                All: true,
              },
              originalTimestamp: '2022-01-20T14:32:51.506Z',
            },
          },
        ],
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              userId: '',
              method: 'POST',
              endpoint: 'https://api.candu.ai/api/eventWebhook',
              headers: {
                Authorization: 'Basic RlhMa0xVRWhHSnl2bVk0',
                'Content-Type': 'application/json',
              },
              params: {},
              body: {
                JSON: {
                  event: 'testEventWithoutProp',
                  traits: {
                    city: 'Pune',
                    name: 'First User',
                    email: 'firstUser@testmail.com',
                    title: 'VP',
                    gender: 'female',
                  },
                  properties: [],
                  anonymousId: 'bf412108-0357-4330-b119-7305e767823c',
                  messageId: 'e9f3dfb4-562c-48f4-b0cf-85782dfc9b1e',
                  type: 'track',
                  context: {
                    source: 'RudderStack',
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
];
