import { eventStreamRouterRequest } from './eventStream';
import { rETLAudienceRouterRequest } from './audienceList';
import { rETLBatchingRouterRequest } from './batchingRecord';
import { rETLRecordRouterRequest } from './record';

export const data = [
  {
    name: 'fb_custom_audience',
    description: 'eventStream tests',
    scenario: 'business',
    successCriteria: 'event stream events should be batched correctly',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: eventStreamRouterRequest,
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'DELETE',
                  endpoint: 'https://graph.facebook.com/v20.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v20.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 1,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  userSchema: [
                    'EMAIL',
                    'DOBM',
                    'DOBD',
                    'DOBY',
                    'PHONE',
                    'GEN',
                    'FI',
                    'MADID',
                    'ZIP',
                    'ST',
                    'COUNTRY',
                  ],
                  isHashRequired: false,
                  disableFormat: false,
                  audienceId: 'aud1',
                  isRaw: true,
                  type: 'NA',
                  subType: 'ANYTHING',
                  maxUserCount: '50',
                },
                Enabled: true,
                Transformations: [],
                IsProcessorEnabled: true,
                ID: '123',
                Name: 'fb_custom_audience',
                DestinationDefinition: {
                  ID: '123',
                  Name: 'fb_custom_audience',
                  DisplayName: 'fb_custom_audience',
                  Config: {},
                },
                WorkspaceID: '123',
              },
            },
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'DELETE',
                  endpoint: 'https://graph.facebook.com/v20.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v20.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 2,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  userSchema: [
                    'EMAIL',
                    'DOBM',
                    'DOBD',
                    'DOBY',
                    'PHONE',
                    'GEN',
                    'FI',
                    'MADID',
                    'ZIP',
                    'ST',
                    'COUNTRY',
                  ],
                  isHashRequired: false,
                  disableFormat: false,
                  audienceId: 'aud1',
                  isRaw: true,
                  type: 'NA',
                  subType: 'ANYTHING',
                  maxUserCount: '50',
                },
                Enabled: true,
                Transformations: [],
                IsProcessorEnabled: true,
                ID: '123',
                Name: 'fb_custom_audience',
                DestinationDefinition: {
                  ID: '123',
                  Name: 'fb_custom_audience',
                  DisplayName: 'fb_custom_audience',
                  Config: {},
                },
                WorkspaceID: '123',
              },
            },
          ],
        },
      },
    },
  },
  {
    name: 'fb_custom_audience',
    description: 'rETL record tests',
    scenario: 'business',
    successCriteria: 'all record events should be transformed correctly based on their operation',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: rETLRecordRouterRequest,
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'DELETE',
                  endpoint: 'https://graph.facebook.com/v20.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 1,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 2,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                Name: 'FB_CUSTOM_AUDIENCE',
                Enabled: true,
                WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                DestinationDefinition: {
                  ID: '1aIXqM806xAVm92nx07YwKbRrO9',
                  Name: 'FB_CUSTOM_AUDIENCE',
                  DisplayName: 'FB_CUSTOM_AUDIENCE',
                  Config: {},
                },
                Transformations: [],
                IsConnectionEnabled: true,
                IsProcessorEnabled: true,
              },
            },
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v20.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 3,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                Name: 'FB_CUSTOM_AUDIENCE',
                Enabled: true,
                WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                DestinationDefinition: {
                  ID: '1aIXqM806xAVm92nx07YwKbRrO9',
                  Name: 'FB_CUSTOM_AUDIENCE',
                  DisplayName: 'FB_CUSTOM_AUDIENCE',
                  Config: {},
                },
                Transformations: [],
                IsConnectionEnabled: true,
                IsProcessorEnabled: true,
              },
            },
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v20.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 4,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 5,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 6,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                Name: 'FB_CUSTOM_AUDIENCE',
                Enabled: true,
                WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                DestinationDefinition: {
                  ID: '1aIXqM806xAVm92nx07YwKbRrO9',
                  Name: 'FB_CUSTOM_AUDIENCE',
                  DisplayName: 'FB_CUSTOM_AUDIENCE',
                  Config: {},
                },
                Transformations: [],
                IsConnectionEnabled: true,
                IsProcessorEnabled: true,
              },
            },
            {
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 7,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 400,
              error: 'Invalid action type in record event',
              statTags: {
                errorCategory: 'dataValidation',
                destinationId: 'default-destinationId',
                errorType: 'instrumentation',
                destType: 'FB_CUSTOM_AUDIENCE',
                workspaceId: 'default-workspaceId',
                module: 'destination',
                implementation: 'native',
                feature: 'router',
              },
            },
          ],
        },
      },
    },
  },
  {
    name: 'fb_custom_audience',
    description: 'rETL record batching tests',
    scenario: 'Framework',
    successCriteria: 'All the record events should be batched',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: rETLBatchingRouterRequest,
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v20.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v20.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 1,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 2,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 3,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '2',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                Name: 'FB_CUSTOM_AUDIENCE',
                Enabled: true,
                WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                DestinationDefinition: {
                  Config: {},
                  DisplayName: 'FB_CUSTOM_AUDIENCE',
                  ID: '1aIXqM806xAVm92nx07YwKbRrO9',
                  Name: 'FB_CUSTOM_AUDIENCE',
                },
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                Transformations: [],
                IsConnectionEnabled: true,
                IsProcessorEnabled: true,
              },
            },
          ],
        },
      },
    },
  },
];
