import { getEndPoint } from '../../../../../src/v0/destinations/fb_custom_audience/config';
import { Destination, RouterTransformationRequest } from '../../../../../src/types';
import { generateMetadata } from '../../../testUtils';
import { config } from 'dotenv';

const eventStreamDestination: Destination = {
  Config: {
    accessToken: 'ABC',
    userSchema: [
      'EMAIL',
      'DOBM',
      'DOBD',
      'DOBY',
      'PHONE',
      'GEN',
      'FI',
      'MADID',
      'ZIP',
      'ST',
      'COUNTRY',
    ],
    isHashRequired: false,
    disableFormat: false,
    audienceId: 'aud1',
    isRaw: true,
    type: 'NA',
    subType: 'ANYTHING',
    maxUserCount: '50',
  },
  Enabled: true,
  Transformations: [],
  IsProcessorEnabled: true,
  ID: '123',
  Name: 'fb_custom_audience',
  DestinationDefinition: {
    ID: '123',
    Name: 'fb_custom_audience',
    DisplayName: 'fb_custom_audience',
    Config: {},
  },
  WorkspaceID: '123',
};

const eventStreamRouterRequest: RouterTransformationRequest = {
  input: [
    {
      message: {
        userId: 'user 1',
        anonymousId: 'anon-id-new',
        event: 'event1',
        type: 'audiencelist',
        properties: {
          listData: {
            add: [
              {
                EMAIL: 'shrouti@abc.com',
                DOBM: '2',
                DOBD: '13',
                DOBY: '2013',
                PHONE: '@09432457768',
                GEN: 'f',
                FI: 'Ms.',
                MADID: 'ABC',
                ZIP: 'ZIP ',
                ST: '123abc ',
                COUNTRY: 'IN',
              },
            ],
            remove: [
              {
                EMAIL: 'shrouti@abc.com',
                DOBM: '2',
                DOBD: '13',
                DOBY: '2013',
                PHONE: '@09432457768',
                GEN: 'f',
                FI: 'Ms.',
                MADID: 'ABC',
                ZIP: 'ZIP ',
                ST: '123abc ',
                COUNTRY: 'IN',
              },
            ],
          },
        },
        context: { ip: '14.5.67.21', library: { name: 'http' } },
        timestamp: '2020-02-02T00:23:09.544Z',
      },
      metadata: generateMetadata(1),
      destination: eventStreamDestination,
    },
    {
      message: {
        userId: 'user 1',
        anonymousId: 'anon-id-new',
        event: 'event1',
        type: 'audiencelist',
        properties: {
          listData: {
            add: [
              {
                EMAIL: 'shrouti@abc.com',
                DOBM: '2',
                DOBD: '13',
                DOBY: '2013',
                PHONE: '@09432457768',
                GEN: 'f',
                FI: 'Ms.',
                MADID: 'ABC',
                ZIP: 'ZIP ',
                ST: '123abc ',
                COUNTRY: 'IN',
              },
            ],
            remove: [
              {
                EMAIL: 'shrouti@abc.com',
                DOBM: '2',
                DOBD: '13',
                DOBY: '2013',
                PHONE: '@09432457768',
                GEN: 'f',
                FI: 'Ms.',
                MADID: 'ABC',
                ZIP: 'ZIP ',
                ST: '123abc ',
                COUNTRY: 'IN',
              },
            ],
          },
        },
        context: { ip: '14.5.67.21', library: { name: 'http' } },
        timestamp: '2020-02-02T00:23:09.544Z',
      },
      metadata: generateMetadata(2),
      destination: eventStreamDestination,
      request: { query: {} },
    },
  ],
  destType: 'fb_custom_audience',
};

const rETLDestination: Destination = {
  Config: {
    accessToken: 'ABC',
    disableFormat: false,
    isHashRequired: true,
    isRaw: false,
    maxUserCount: '50',
    oneTrustCookieCategories: [],
    skipVerify: false,
    subType: 'NA',
    type: 'NA',
    userSchema: ['EMAIL'],
  },
  ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
  Name: 'FB_CUSTOM_AUDIENCE',
  Enabled: true,
  WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
  DestinationDefinition: {
    ID: '1aIXqM806xAVm92nx07YwKbRrO9',
    Name: 'FB_CUSTOM_AUDIENCE',
    DisplayName: 'FB_CUSTOM_AUDIENCE',
    Config: {},
  },
  Transformations: [],
  IsConnectionEnabled: true,
  IsProcessorEnabled: true,
};

const rETLRouterRequest: RouterTransformationRequest = {
  input: [
    {
      message: {
        sentAt: '2023-03-30 06:42:55.991938402 +0000 UTC',
        userId: '2MUWghI7u85n91dd1qzGyswpZan-2MUWqbQqvctyfMGqU9QCNadpKNy',
        channel: 'sources',
        messageId: '4d906837-031d-4d34-b97a-62fdf51b4d3a',
        event: 'Add_Audience',
        context: {
          destinationFields: 'EMAIL, FN',
          externalId: [{ type: 'FB_CUSTOM_AUDIENCE-23848494844100489', identifierType: 'EMAIL' }],
          mappedToDestination: 'true',
          sources: {
            job_run_id: 'cgiiurt8um7k7n5dq480',
            task_run_id: 'cgiiurt8um7k7n5dq48g',
            job_id: '2MUWghI7u85n91dd1qzGyswpZan',
            version: '895/merge',
          },
        },
        recordId: '725ad989-6750-4839-b46b-0ddb3b8e5aa2/1/10',
        rudderId: '85c49666-c628-4835-937b-8f1d9ee7a724',
        properties: {
          listData: {
            add: [
              { EMAIL: 'dede@gmail.com', FN: 'vishwa' },
              { EMAIL: 'fchsjjn@gmail.com', FN: 'hskks' },
              { EMAIL: 'fghjnbjk@gmail.com', FN: 'ghfry' },
              { EMAIL: 'gvhjkk@gmail.com', FN: 'hbcwqe' },
              { EMAIL: 'qsdwert@egf.com', FN: 'dsfds' },
              { EMAIL: 'ascscxsaca@com', FN: 'scadscdvcda' },
              { EMAIL: 'abc@gmail.com', FN: 'subscribed' },
              { EMAIL: 'ddwnkl@gmail.com', FN: 'subscribed' },
              { EMAIL: 'subscribed@eewrfrd.com', FN: 'pending' },
              { EMAIL: 'acsdvdf@ddfvf.com', FN: 'pending' },
            ],
          },
        },
        type: 'audienceList',
        anonymousId: '63228b51-394e-4ca2-97a0-427f6187480b',
      },
      destination: rETLDestination,
      metadata: generateMetadata(3),
    },
    {
      message: {
        sentAt: '2023-03-30 06:42:55.991938402 +0000 UTC',
        userId: '2MUWghI7u85n91dd1qzGyswpZan-2MUWqbQqvctyfMGqU9QCNadpKNy',
        channel: 'sources',
        messageId: '4d906837-031d-4d34-b97a-62fdf51b4d3a',
        event: 'Add_Audience',
        context: {
          externalId: [{ type: 'FB_CUSTOM_AUDIENCE-23848494844100489', identifierType: 'EMAIL' }],
          mappedToDestination: 'true',
          sources: {
            job_run_id: 'cgiiurt8um7k7n5dq480',
            task_run_id: 'cgiiurt8um7k7n5dq48g',
            job_id: '2MUWghI7u85n91dd1qzGyswpZan',
            version: '895/merge',
          },
        },
        recordId: '725ad989-6750-4839-b46b-0ddb3b8e5aa2/1/10',
        rudderId: '85c49666-c628-4835-937b-8f1d9ee7a724',
        properties: {
          listData: {
            add: [
              { EMAIL: 'dede@gmail.com', FN: 'vishwa' },
              { EMAIL: 'fchsjjn@gmail.com', FN: 'hskks' },
              { EMAIL: 'fghjnbjk@gmail.com', FN: 'ghfry' },
              { EMAIL: 'gvhjkk@gmail.com', FN: 'hbcwqe' },
              { EMAIL: 'qsdwert@egf.com', FN: 'dsfds' },
              { EMAIL: 'ascscxsaca@com', FN: 'scadscdvcda' },
              { EMAIL: 'abc@gmail.com', FN: 'subscribed' },
              { EMAIL: 'ddwnkl@gmail.com', FN: 'subscribed' },
              { EMAIL: 'subscribed@eewrfrd.com', FN: 'pending' },
              { EMAIL: 'acsdvdf@ddfvf.com', FN: 'pending' },
            ],
          },
        },
        type: 'audienceList',
        anonymousId: '63228b51-394e-4ca2-97a0-427f6187480b',
      },
      destination: rETLDestination,
      metadata: generateMetadata(4),
    },
  ],
  destType: 'fb_custom_audience',
};

export const data = [
  {
    name: 'fb_custom_audience',
    description: 'eventStream tests',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: eventStreamRouterRequest,
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'DELETE',
                  endpoint: 'https://graph.facebook.com/v18.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 1,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  userSchema: [
                    'EMAIL',
                    'DOBM',
                    'DOBD',
                    'DOBY',
                    'PHONE',
                    'GEN',
                    'FI',
                    'MADID',
                    'ZIP',
                    'ST',
                    'COUNTRY',
                  ],
                  isHashRequired: false,
                  disableFormat: false,
                  audienceId: 'aud1',
                  isRaw: true,
                  type: 'NA',
                  subType: 'ANYTHING',
                  maxUserCount: '50',
                },
                Enabled: true,
                Transformations: [],
                IsProcessorEnabled: true,
                ID: '123',
                Name: 'fb_custom_audience',
                DestinationDefinition: {
                  ID: '123',
                  Name: 'fb_custom_audience',
                  DisplayName: 'fb_custom_audience',
                  Config: {},
                },
                WorkspaceID: '123',
              },
            },
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'DELETE',
                  endpoint: 'https://graph.facebook.com/v18.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/aud1/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      is_raw: true,
                      data_source: {
                        sub_type: 'ANYTHING',
                      },
                      schema: [
                        'EMAIL',
                        'DOBM',
                        'DOBD',
                        'DOBY',
                        'PHONE',
                        'GEN',
                        'FI',
                        'MADID',
                        'ZIP',
                        'ST',
                        'COUNTRY',
                      ],
                      data: [
                        [
                          'shrouti@abc.com',
                          '2',
                          '13',
                          '2013',
                          '@09432457768',
                          'f',
                          'Ms.',
                          'ABC',
                          'ZIP ',
                          '123abc ',
                          'IN',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 2,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  userSchema: [
                    'EMAIL',
                    'DOBM',
                    'DOBD',
                    'DOBY',
                    'PHONE',
                    'GEN',
                    'FI',
                    'MADID',
                    'ZIP',
                    'ST',
                    'COUNTRY',
                  ],
                  isHashRequired: false,
                  disableFormat: false,
                  audienceId: 'aud1',
                  isRaw: true,
                  type: 'NA',
                  subType: 'ANYTHING',
                  maxUserCount: '50',
                },
                Enabled: true,
                Transformations: [],
                IsProcessorEnabled: true,
                ID: '123',
                Name: 'fb_custom_audience',
                DestinationDefinition: {
                  ID: '123',
                  Name: 'fb_custom_audience',
                  DisplayName: 'fb_custom_audience',
                  Config: {},
                },
                WorkspaceID: '123',
              },
            },
          ],
        },
      },
    },
  },
  {
    name: 'fb_custom_audience',
    description: 'rETL tests',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: rETLRouterRequest,
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FN'],
                      data: [
                        [
                          '7625cab24612c37df6d2f724721bb38a25095d0295e29b807238ee188b8aca43',
                          'e328a0d90d4b5132b2655cf7079b160040d2c1a83d70d4cad9cf1f69310635b3',
                        ],
                        [
                          'b2b4abadd72190af54305c0d3abf1977fec4935016bb13ff28040d5712318dfd',
                          'f8147eb72c9bb356c362fdb0796b54971ebc983cb60b3cc3ff29582ce2052bad',
                        ],
                        [
                          'c4b007d1c3c9a5d31bd4082237a913e8e0db1767225c2a5ef33be2716df005fa',
                          'd8bb13b95eaed7f9b6a8af276aa6122e8015e0c466c1a84e49ff7c69ad6ac911',
                        ],
                        [
                          '94639be1bd9f17c05820164e9d71ef78558f117a9e8bfab43cf8015e08aa0b27',
                          'b1661f97721dede0f876dcbf603289ee339f641b9c310deba53c76940f472698',
                        ],
                        [
                          '39b456cfb4bb07f9e6bb18698aa173171ca49c731fccc4790e9ecea808d24ae6',
                          '6c882abd6d0aff713cdd6a4a31ee28c9140612fb2627a611f6f9f539bac44f81',
                        ],
                        [
                          '769f73387add781a481ca08300008a08fb2f1816aaed196137efc2e05976d711',
                          '2222cb73346f7a01a1d4d3db28b58fd41045782bb66152b92aade379192544c5',
                        ],
                        [
                          '48ddb93f0b30c475423fe177832912c5bcdce3cc72872f8051627967ef278e08',
                          'abc12f8d666517c35280bf220f5390b1f0ef4bdbbc794ac59c95bba0381bf91b',
                        ],
                        [
                          'da2d431121cd10578fd81f8f80344b06db59ea2d05a7b5d27536c8789ddae8f0',
                          'abc12f8d666517c35280bf220f5390b1f0ef4bdbbc794ac59c95bba0381bf91b',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '62a2fed3d6e08c44835fce71f02210b1ddabfb066e39edf1e6c261988f824dd3',
                        ],
                        [
                          '0c1d1b0ba547a742013366d6fbc8f71dd77f566d94e41ed9f828a74b96928161',
                          '62a2fed3d6e08c44835fce71f02210b1ddabfb066e39edf1e6c261988f824dd3',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 3,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '50',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                Name: 'FB_CUSTOM_AUDIENCE',
                Enabled: true,
                WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                DestinationDefinition: {
                  ID: '1aIXqM806xAVm92nx07YwKbRrO9',
                  Name: 'FB_CUSTOM_AUDIENCE',
                  DisplayName: 'FB_CUSTOM_AUDIENCE',
                  Config: {},
                },
                Transformations: [],
                IsConnectionEnabled: true,
                IsProcessorEnabled: true,
              },
            },
            {
              metadata: [
                {
                  attemptNum: 1,
                  destinationId: 'default-destinationId',
                  dontBatch: false,
                  jobId: 4,
                  secret: {
                    accessToken: 'default-accessToken',
                  },
                  sourceId: 'default-sourceId',
                  userId: 'default-userId',
                  workspaceId: 'default-workspaceId',
                },
              ],
              batched: false,
              statusCode: 400,
              error:
                'context.destinationFields is required property for events mapped to destination ',
              statTags: {
                errorCategory: 'dataValidation',
                errorType: 'instrumentation',
                destType: 'FB_CUSTOM_AUDIENCE',
                destinationId: 'default-destinationId',
                module: 'destination',
                implementation: 'native',
                feature: 'router',
                workspaceId: 'default-workspaceId',
              },
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '50',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                Name: 'FB_CUSTOM_AUDIENCE',
                Enabled: true,
                WorkspaceID: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                DestinationDefinition: {
                  ID: '1aIXqM806xAVm92nx07YwKbRrO9',
                  Name: 'FB_CUSTOM_AUDIENCE',
                  DisplayName: 'FB_CUSTOM_AUDIENCE',
                  Config: {},
                },
                Transformations: [],
                IsConnectionEnabled: true,
                IsProcessorEnabled: true,
              },
            },
          ],
        },
      },
    },
  },
  {
    name: 'fb_custom_audience',
    description: 'rETL record tests',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: {
          input: [
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'insert',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 2,
                userId: 'u1',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'update',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 3,
                userId: 'u2',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'delete',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 4,
                userId: 'u3',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'delete',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 5,
                userId: 'u4',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'update',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 6,
                userId: 'u5',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'update',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 7,
                userId: 'u6',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'lol',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 8,
                userId: 'u7',
              },
            },
          ],
          destType: 'fb_custom_audience',
        },
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'DELETE',
                  endpoint: 'https://graph.facebook.com/v18.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  jobId: 4,
                  userId: 'u3',
                },
                {
                  jobId: 5,
                  userId: 'u4',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
            },
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  jobId: 2,
                  userId: 'u1',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
            },
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  jobId: 3,
                  userId: 'u2',
                },
                {
                  jobId: 6,
                  userId: 'u5',
                },
                {
                  jobId: 7,
                  userId: 'u6',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '3',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
            },
            {
              metadata: [
                {
                  jobId: 8,
                  userId: 'u7',
                },
              ],
              batched: false,
              statusCode: 400,
              error: 'Invalid action type in record event',
              statTags: {
                errorCategory: 'dataValidation',
                errorType: 'instrumentation',
                destType: 'FB_CUSTOM_AUDIENCE',
                module: 'destination',
                implementation: 'native',
                feature: 'router',
              },
            },
          ],
        },
      },
    },
  },
  {
    name: 'fb_custom_audience',
    description: 'rETL record batching tests',
    feature: 'router',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: {
          input: [
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '2',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'insert',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 2,
                userId: 'u1',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '2',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'insert',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 3,
                userId: 'u2',
              },
            },
            {
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '2',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
              message: {
                action: 'insert',
                context: {
                  destinationFields: 'EMAIL, FI',
                  externalId: [
                    {
                      type: 'FB_CUSTOM_AUDIENCE-23848494844100489',
                      identifierType: 'EMAIL',
                    },
                  ],
                  mappedToDestination: 'true',
                  sources: {
                    job_run_id: 'cgiiurt8um7k7n5dq480',
                    task_run_id: 'cgiiurt8um7k7n5dq48g',
                    job_id: '2MUWghI7u85n91dd1qzGyswpZan',
                    version: '895/merge',
                  },
                },
                recordId: '2',
                rudderId: '2',
                fields: {
                  EMAIL: 'subscribed@eewrfrd.com',
                  FI: 'ghui',
                },
                type: 'record',
              },
              metadata: {
                jobId: 4,
                userId: 'u3',
              },
            },
          ],
          destType: 'fb_custom_audience',
        },
      },
    },
    output: {
      response: {
        status: 200,
        body: {
          output: [
            {
              batchedRequest: [
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
                {
                  version: '1',
                  type: 'REST',
                  method: 'POST',
                  endpoint: 'https://graph.facebook.com/v18.0/23848494844100489/users',
                  headers: {},
                  params: {
                    access_token: 'ABC',
                    payload: {
                      schema: ['EMAIL', 'FI'],
                      data: [
                        [
                          'b100c2ec0718fe6b4805b623aeec6710719d042ceea55f5c8135b010ec1c7b36',
                          '1e14a2f476f7611a8b22bc85d14237fdc88aac828737e739416c32c5bce3bd16',
                        ],
                      ],
                    },
                  },
                  body: {
                    JSON: {},
                    JSON_ARRAY: {},
                    XML: {},
                    FORM: {},
                  },
                  files: {},
                },
              ],
              metadata: [
                {
                  jobId: 2,
                  userId: 'u1',
                },
                {
                  jobId: 3,
                  userId: 'u2',
                },
                {
                  jobId: 4,
                  userId: 'u3',
                },
              ],
              batched: true,
              statusCode: 200,
              destination: {
                Config: {
                  accessToken: 'ABC',
                  disableFormat: false,
                  isHashRequired: true,
                  isRaw: false,
                  maxUserCount: '2',
                  oneTrustCookieCategories: [],
                  skipVerify: false,
                  subType: 'NA',
                  type: 'NA',
                  userSchema: ['EMAIL'],
                },
                secretConfig: {},
                ID: '1mMy5cqbtfuaKZv1IhVQKnBdVwe',
                name: 'FB_CUSTOM_AUDIENCE',
                enabled: true,
                workspaceId: '1TSN08muJTZwH8iCDmnnRt1pmLd',
                deleted: false,
                createdAt: '2020-12-30T08:39:32.005Z',
                updatedAt: '2021-02-03T16:22:31.374Z',
                destinationDefinition: {
                  id: '1aIXqM806xAVm92nx07YwKbRrO9',
                  name: 'FB_CUSTOM_AUDIENCE',
                  displayName: 'FB_CUSTOM_AUDIENCE',
                  createdAt: '2020-04-09T09:24:31.794Z',
                  updatedAt: '2021-01-11T11:03:28.103Z',
                },
                transformations: [],
                isConnectionEnabled: true,
                isProcessorEnabled: true,
              },
            },
          ],
        },
      },
    },
  },
];
