// This file contains the test scenarios for the server-side events from the Shopify GraphQL API for
// the v1 transformation flow
import { dummySourceConfig, note_attributes } from '../constants';

export const checkoutEventsTestScenarios = [
  {
    id: 'c001',
    name: 'shopify',
    description: 'Track Call -> Checkout Started event from Pixel app',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              id: 35550298931313,
              token: '84ad78572dae52a8cbea7d55371afe89',
              cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
              email: null,
              gateway: null,
              buyer_accepts_marketing: false,
              buyer_accepts_sms_marketing: false,
              sms_marketing_phone: null,
              created_at: '2024-11-06T02:22:00+00:00',
              updated_at: '2024-11-05T21:22:02-05:00',
              landing_site: '/',
              note: '',
              note_attributes,
              referring_site: '',
              shipping_lines: [],
              shipping_address: [],
              taxes_included: false,
              total_weight: 0,
              currency: 'USD',
              completed_at: null,
              phone: null,
              customer_locale: 'en-US',
              line_items: [
                {
                  key: '41327142600817',
                  fulfillment_service: 'manual',
                  gift_card: false,
                  grams: 0,
                  presentment_title: 'The Collection Snowboard: Hydrogen',
                  presentment_variant_title: '',
                  product_id: 7234590408817,
                  quantity: 1,
                  requires_shipping: true,
                  sku: '',
                  tax_lines: [],
                  taxable: true,
                  title: 'The Collection Snowboard: Hydrogen',
                  variant_id: 41327142600817,
                  variant_title: '',
                  variant_price: '600.00',
                  vendor: 'Hydrogen Vendor',
                  unit_price_measurement: {
                    measured_type: null,
                    quantity_value: null,
                    quantity_unit: null,
                    reference_value: null,
                    reference_unit: null,
                  },
                  compare_at_price: null,
                  line_price: '600.00',
                  price: '600.00',
                  applied_discounts: [],
                  destination_location_id: null,
                  user_id: null,
                  rank: null,
                  origin_location_id: null,
                  properties: {},
                },
              ],
              name: '#35550298931313',
              abandoned_checkout_url:
                'https://pixel-testing-rs.myshopify.com/59026964593/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ/recover?key=0385163be3875d3a2117e982d9cc3517&locale=en-US',
              discount_codes: [],
              tax_lines: [],
              presentment_currency: 'USD',
              source_name: 'web',
              total_line_items_price: '600.00',
              total_tax: '0.00',
              total_discounts: '0.00',
              subtotal_price: '600.00',
              total_price: '600.00',
              total_duties: '0.00',
              device_id: null,
              user_id: null,
              location_id: null,
              source_identifier: null,
              source_url: null,
              source: null,
              closed_at: null,
              query_parameters: {
                topic: ['checkouts_create'],
                version: ['pixel'],
                writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              },
            },
            source: dummySourceConfig,
            query_parameters: {
              topic: ['carts_update'],
              writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              version: ['pixel'],
            },
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    integration: {
                      name: 'SHOPIFY',
                    },
                    topic: 'checkouts_create',
                    cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
                    shopifyDetails: {
                      id: 35550298931313,
                      token: '84ad78572dae52a8cbea7d55371afe89',
                      cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
                      email: null,
                      gateway: null,
                      buyer_accepts_marketing: false,
                      buyer_accepts_sms_marketing: false,
                      sms_marketing_phone: null,
                      created_at: '2024-11-06T02:22:00+00:00',
                      updated_at: '2024-11-05T21:22:02-05:00',
                      landing_site: '/',
                      note: '',
                      note_attributes,
                      referring_site: '',
                      shipping_lines: [],
                      shipping_address: [],
                      taxes_included: false,
                      total_weight: 0,
                      currency: 'USD',
                      completed_at: null,
                      phone: null,
                      customer_locale: 'en-US',
                      line_items: [
                        {
                          key: '41327142600817',
                          fulfillment_service: 'manual',
                          gift_card: false,
                          grams: 0,
                          presentment_title: 'The Collection Snowboard: Hydrogen',
                          presentment_variant_title: '',
                          product_id: 7234590408817,
                          quantity: 1,
                          requires_shipping: true,
                          sku: '',
                          tax_lines: [],
                          taxable: true,
                          title: 'The Collection Snowboard: Hydrogen',
                          variant_id: 41327142600817,
                          variant_title: '',
                          variant_price: '600.00',
                          vendor: 'Hydrogen Vendor',
                          unit_price_measurement: {
                            measured_type: null,
                            quantity_value: null,
                            quantity_unit: null,
                            reference_value: null,
                            reference_unit: null,
                          },
                          compare_at_price: null,
                          line_price: '600.00',
                          price: '600.00',
                          applied_discounts: [],
                          destination_location_id: null,
                          user_id: null,
                          rank: null,
                          origin_location_id: null,
                          properties: {},
                        },
                      ],
                      name: '#35550298931313',
                      abandoned_checkout_url:
                        'https://pixel-testing-rs.myshopify.com/59026964593/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ/recover?key=0385163be3875d3a2117e982d9cc3517&locale=en-US',
                      discount_codes: [],
                      tax_lines: [],
                      presentment_currency: 'USD',
                      source_name: 'web',
                      total_line_items_price: '600.00',
                      total_tax: '0.00',
                      total_discounts: '0.00',
                      subtotal_price: '600.00',
                      total_price: '600.00',
                      total_duties: '0.00',
                      device_id: null,
                      user_id: null,
                      location_id: null,
                      source_identifier: null,
                      source_url: null,
                      source: null,
                      closed_at: null,
                    },
                  },
                  integrations: {
                    SHOPIFY: true,
                  },
                  type: 'track',
                  event: 'Checkout Started',
                  properties: {
                    order_id: 35550298931313,
                    value: '600.00',
                    tax: '0.00',
                    currency: 'USD',
                    products: [
                      {
                        product_id: 7234590408817,
                        price: '600.00',
                        brand: 'Hydrogen Vendor',
                        quantity: 1,
                      },
                    ],
                  },
                  timestamp: '2024-11-06T02:22:02.000Z',
                  traits: {
                    shippingAddress: [],
                  },
                  anonymousId: '50ead33e-d763-4854-b0ab-765859ef05cb',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    id: 'c002',
    name: 'shopify',
    description: 'Track Call -> Checkout Updated event from Pixel app',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              query_parameters: {
                topic: ['checkouts_update'],
                writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
                version: ['pixel'],
              },
              id: 35374569160817,
              token: 'e89d4437003b6b8480f8bc7f8036a659',
              cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2',
              email: 'testuser101@gmail.com',
              created_at: '2024-09-16T03:50:1500:00',
              updated_at: '2024-09-17T03:29:02-04:00',
              note: '',
              note_attributes,
              shipping_address: {
                first_name: 'testuser',
                address1: 'oakwood bridge',
                phone: null,
                city: 'KLF',
                zip: '85003',
                province: 'Arizona',
                country: 'United States',
                last_name: 'dummy',
                address2: 'Hedgetown',
                company: null,
                latitude: null,
                longitude: null,
                name: 'testuser dummy',
                country_code: 'US',
                province_code: 'AZ',
              },
              total_weight: 0,
              currency: 'USD',
              customer_locale: 'en-US',
              line_items: [
                {
                  key: '41327143059569',
                  fulfillment_service: 'manual',
                  gift_card: false,
                  grams: 0,
                  presentment_title: 'The Multi-location Snowboard',
                  presentment_variant_title: '',
                  product_id: 7234590638193,
                  quantity: 1,
                  requires_shipping: true,
                  sku: '',
                  tax_lines: [],
                  taxable: true,
                  title: 'The Multi-location Snowboard',
                  variant_id: 41327143059569,
                  variant_title: '',
                  variant_price: '729.95',
                  vendor: 'pixel-testing-rs',
                  unit_price_measurement: {
                    measured_type: null,
                    quantity_value: null,
                    quantity_unit: null,
                    reference_value: null,
                    reference_unit: null,
                  },
                  compare_at_price: null,
                  line_price: '729.95',
                  price: '729.95',
                  applied_discounts: [],
                  destination_location_id: null,
                  user_id: null,
                  rank: null,
                  origin_location_id: null,
                  properties: {},
                },
              ],
              name: '#35374569160817',
              abandoned_checkout_url:
                'https://pixel-testing-rs.myshopify.com/59026964593/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2/recover?key=8195f56ee0de230b3a0469cc692f3436',
              presentment_currency: 'USD',
              total_tax: '0.00',
              total_discounts: '0.00',
              subtotal_price: '729.95',
              total_price: '736.85',
              total_duties: '0.00',
              customer: {
                id: 7188389789809,
                email: 'testuser101@gmail.com',
                accepts_marketing: false,
                created_at: null,
                updated_at: null,
                first_name: 'testuser',
                last_name: 'dummy',
                orders_count: 0,
                state: 'disabled',
                total_spent: '0.00',
                last_order_id: null,
                note: null,
                verified_email: true,
                multipass_identifier: null,
                tax_exempt: false,
                phone: null,
                tags: '',
                currency: 'USD',
                accepts_marketing_updated_at: null,
                admin_graphql_api_id: 'gid://shopify/Customer/7188389789809',
                default_address: {
                  id: null,
                  customer_id: 7188389789809,
                  first_name: 'testuser',
                  last_name: 'dummy',
                  company: null,
                  address1: 'oakwood bridge',
                  address2: 'Hedgetown',
                  city: 'KLF',
                  province: 'Arizona',
                  country: 'United States',
                  zip: '85003',
                  phone: null,
                  name: 'testuser dummy',
                  province_code: 'AZ',
                  country_code: 'US',
                  country_name: 'United States',
                  default: true,
                },
                last_order_name: null,
                marketing_opt_in_level: null,
              },
            },
            source: dummySourceConfig,
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  anonymousId: '50ead33e-d763-4854-b0ab-765859ef05cb',
                  context: {
                    cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2',
                    integration: {
                      name: 'SHOPIFY',
                    },
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    shopifyDetails: {
                      id: 35374569160817,
                      token: 'e89d4437003b6b8480f8bc7f8036a659',
                      cart_token: 'Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2',
                      email: 'testuser101@gmail.com',
                      created_at: '2024-09-16T03:50:1500:00',
                      updated_at: '2024-09-17T03:29:02-04:00',
                      note: '',
                      note_attributes,
                      shipping_address: {
                        first_name: 'testuser',
                        address1: 'oakwood bridge',
                        phone: null,
                        city: 'KLF',
                        zip: '85003',
                        province: 'Arizona',
                        country: 'United States',
                        last_name: 'dummy',
                        address2: 'Hedgetown',
                        company: null,
                        latitude: null,
                        longitude: null,
                        name: 'testuser dummy',
                        country_code: 'US',
                        province_code: 'AZ',
                      },
                      total_weight: 0,
                      currency: 'USD',
                      customer_locale: 'en-US',
                      line_items: [
                        {
                          key: '41327143059569',
                          fulfillment_service: 'manual',
                          gift_card: false,
                          grams: 0,
                          presentment_title: 'The Multi-location Snowboard',
                          presentment_variant_title: '',
                          product_id: 7234590638193,
                          quantity: 1,
                          requires_shipping: true,
                          sku: '',
                          tax_lines: [],
                          taxable: true,
                          title: 'The Multi-location Snowboard',
                          variant_id: 41327143059569,
                          variant_title: '',
                          variant_price: '729.95',
                          vendor: 'pixel-testing-rs',
                          unit_price_measurement: {
                            measured_type: null,
                            quantity_value: null,
                            quantity_unit: null,
                            reference_value: null,
                            reference_unit: null,
                          },
                          compare_at_price: null,
                          line_price: '729.95',
                          price: '729.95',
                          applied_discounts: [],
                          destination_location_id: null,
                          user_id: null,
                          rank: null,
                          origin_location_id: null,
                          properties: {},
                        },
                      ],
                      name: '#35374569160817',
                      abandoned_checkout_url:
                        'https://pixel-testing-rs.myshopify.com/59026964593/checkouts/ac/Z2NwLXVzLWVhc3QxOjAxSjdXRjdOQjY0NlFFNFdQVEg0MTRFM1E2/recover?key=8195f56ee0de230b3a0469cc692f3436',
                      presentment_currency: 'USD',
                      total_tax: '0.00',
                      total_discounts: '0.00',
                      subtotal_price: '729.95',
                      total_price: '736.85',
                      total_duties: '0.00',
                      customer: {
                        id: 7188389789809,
                        email: 'testuser101@gmail.com',
                        accepts_marketing: false,
                        created_at: null,
                        updated_at: null,
                        first_name: 'testuser',
                        last_name: 'dummy',
                        orders_count: 0,
                        state: 'disabled',
                        total_spent: '0.00',
                        last_order_id: null,
                        note: null,
                        verified_email: true,
                        multipass_identifier: null,
                        tax_exempt: false,
                        phone: null,
                        tags: '',
                        currency: 'USD',
                        accepts_marketing_updated_at: null,
                        admin_graphql_api_id: 'gid://shopify/Customer/7188389789809',
                        default_address: {
                          id: null,
                          customer_id: 7188389789809,
                          first_name: 'testuser',
                          last_name: 'dummy',
                          company: null,
                          address1: 'oakwood bridge',
                          address2: 'Hedgetown',
                          city: 'KLF',
                          province: 'Arizona',
                          country: 'United States',
                          zip: '85003',
                          phone: null,
                          name: 'testuser dummy',
                          province_code: 'AZ',
                          country_code: 'US',
                          country_name: 'United States',
                          default: true,
                        },
                        last_order_name: null,
                        marketing_opt_in_level: null,
                      },
                    },
                    topic: 'checkouts_update',
                  },
                  event: 'Checkout Updated',
                  integrations: {
                    SHOPIFY: true,
                  },
                  properties: {
                    currency: 'USD',
                    order_id: 35374569160817,
                    products: [
                      {
                        brand: 'pixel-testing-rs',
                        price: '729.95',
                        product_id: 7234590638193,
                        quantity: 1,
                      },
                    ],
                    tax: '0.00',
                    value: '736.85',
                  },
                  timestamp: '2024-09-17T07:29:02.000Z',
                  traits: {
                    acceptsMarketing: false,
                    address: {
                      address1: 'oakwood bridge',
                      address2: 'Hedgetown',
                      city: 'KLF',
                      company: null,
                      country: 'United States',
                      country_code: 'US',
                      country_name: 'United States',
                      customer_id: 7188389789809,
                      default: true,
                      first_name: 'testuser',
                      id: null,
                      last_name: 'dummy',
                      name: 'testuser dummy',
                      phone: null,
                      province: 'Arizona',
                      province_code: 'AZ',
                      zip: '85003',
                    },
                    adminGraphqlApiId: 'gid://shopify/Customer/7188389789809',
                    currency: 'USD',
                    email: 'testuser101@gmail.com',
                    firstName: 'testuser',
                    lastName: 'dummy',
                    orderCount: 0,
                    shippingAddress: {
                      address1: 'oakwood bridge',
                      address2: 'Hedgetown',
                      city: 'KLF',
                      company: null,
                      country: 'United States',
                      country_code: 'US',
                      first_name: 'testuser',
                      last_name: 'dummy',
                      latitude: null,
                      longitude: null,
                      name: 'testuser dummy',
                      phone: null,
                      province: 'Arizona',
                      province_code: 'AZ',
                      zip: '85003',
                    },
                    state: 'disabled',
                    tags: '',
                    taxExempt: false,
                    totalSpent: '0.00',
                    verifiedEmail: true,
                  },
                  type: 'track',
                  userId: '7188389789809',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    id: 'c003',
    name: 'shopify',
    description: 'Track Call -> Order Updated event from Pixel app',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              id: 5778367414385,
              admin_graphql_api_id: 'gid://shopify/Order/5778367414385',
              app_id: 580111,
              browser_ip: '139.5.255.205',
              cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
              checkout_id: 35550298931313,
              checkout_token: '84ad78572dae52a8cbea7d55371afe89',
              confirmation_number: 'DPPARQ8UJ',
              contact_email: 'henry@wfls.com',
              created_at: '2024-11-05T21:54:49-05:00',
              currency: 'USD',
              current_subtotal_price: '600.00',
              current_subtotal_price_set: {
                shop_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
              },
              current_total_discounts: '0.00',
              current_total_discounts_set: {
                shop_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
              },
              current_total_price: '600.00',
              current_total_price_set: {
                shop_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
              },
              current_total_tax: '0.00',
              current_total_tax_set: {
                shop_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
              },
              customer_locale: 'en-US',
              discount_codes: [],
              email: 'henry@wfls.com',
              estimated_taxes: false,
              merchant_of_record_app_id: null,
              name: '#1017',
              note: null,
              note_attributes,
              number: 17,
              order_number: 1017,
              order_status_url:
                'https://pixel-testing-rs.myshopify.com/59026964593/orders/676613a0027fc8240e16d67fdc9f5ac8/authenticate?key=a70bbe7ec8abcc46b77e4331e4df8c60',
              original_total_additional_fees_set: null,
              original_total_duties_set: null,
              payment_gateway_names: ['bogus'],
              phone: null,
              presentment_currency: 'USD',
              source_identifier: '4d92cf60cc24a1bd95929e17ead9845f',
              subtotal_price: '600.00',
              subtotal_price_set: {
                shop_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
              },
              tax_lines: [],
              token: '676613a0027fc8240e16d67fdc9f5ac8',
              total_discounts: '0.00',
              total_discounts_set: {
                shop_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
              },
              total_line_items_price: '600.00',
              total_line_items_price_set: {
                shop_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
              },
              total_price: '600.00',
              total_price_set: {
                shop_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '600.00',
                  currency_code: 'USD',
                },
              },
              total_shipping_price_set: {
                shop_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
              },
              total_tax: '0.00',
              total_tax_set: {
                shop_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
                presentment_money: {
                  amount: '0.00',
                  currency_code: 'USD',
                },
              },
              total_weight: 0,
              updated_at: '2024-11-05T21:54:50-05:00',
              user_id: null,
              billing_address: {
                first_name: 'yodi',
                address1: 'Yuma Proving Ground',
                phone: null,
                city: 'Yuma Proving Ground',
                zip: '85365',
                province: 'Arizona',
                country: 'United States',
                last_name: 'waffles',
                address2: 'suite 001',
                company: null,
                latitude: 33.0177811,
                longitude: -114.2525392,
                name: 'yodi waffles',
                country_code: 'US',
                province_code: 'AZ',
              },
              customer: {
                id: 7358220173425,
                email: 'henry@wfls.com',
                created_at: '2024-10-23T16:03:11-04:00',
                updated_at: '2024-11-05T21:54:49-05:00',
                first_name: 'yodi',
                last_name: 'waffles',
                state: 'disabled',
                note: null,
                verified_email: true,
                multipass_identifier: null,
                tax_exempt: false,
                phone: null,
                email_marketing_consent: {
                  state: 'not_subscribed',
                  opt_in_level: 'single_opt_in',
                  consent_updated_at: null,
                },
                sms_marketing_consent: null,
                tags: '',
                currency: 'USD',
                tax_exemptions: [],
                admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
                default_address: {
                  id: 8715246862449,
                  customer_id: 7358220173425,
                  first_name: 'henry',
                  last_name: 'waffles',
                  company: null,
                  address1: 'Yuimaru Kitchen',
                  address2: '6',
                  city: 'Johnson City',
                  province: 'Tennessee',
                  country: 'United States',
                  zip: '37604',
                  phone: null,
                  name: 'henry waffles',
                  province_code: 'TN',
                  country_code: 'US',
                  country_name: 'United States',
                  default: true,
                },
              },
              line_items: [
                {
                  id: 14234727743601,
                  admin_graphql_api_id: 'gid://shopify/LineItem/14234727743601',
                  attributed_staffs: [],
                  current_quantity: 1,
                  fulfillable_quantity: 1,
                  fulfillment_service: 'manual',
                  fulfillment_status: null,
                  gift_card: false,
                  grams: 0,
                  name: 'The Collection Snowboard: Hydrogen',
                  price: '600.00',
                  price_set: {
                    shop_money: {
                      amount: '600.00',
                      currency_code: 'USD',
                    },
                    presentment_money: {
                      amount: '600.00',
                      currency_code: 'USD',
                    },
                  },
                  product_exists: true,
                  product_id: 7234590408817,
                  properties: [],
                  quantity: 1,
                  requires_shipping: true,
                  sku: '',
                  taxable: true,
                  title: 'The Collection Snowboard: Hydrogen',
                  total_discount: '0.00',
                  total_discount_set: {
                    shop_money: {
                      amount: '0.00',
                      currency_code: 'USD',
                    },
                    presentment_money: {
                      amount: '0.00',
                      currency_code: 'USD',
                    },
                  },
                  variant_id: 41327142600817,
                  variant_inventory_management: 'shopify',
                  variant_title: null,
                  vendor: 'Hydrogen Vendor',
                  tax_lines: [],
                  duties: [],
                  discount_allocations: [],
                },
              ],
              payment_terms: null,
              refunds: [],
              shipping_address: {
                first_name: 'henry',
                address1: 'Yuimaru Kitchen',
                phone: null,
                city: 'Johnson City',
                zip: '37604',
                province: 'Tennessee',
                country: 'United States',
                last_name: 'waffles',
                address2: '6',
                company: null,
                latitude: 36.3528845,
                longitude: -82.4006335,
                name: 'henry waffles',
                country_code: 'US',
                province_code: 'TN',
              },
              query_parameters: {
                topic: ['orders_updated'],
                version: ['pixel'],
                writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              },
            },
            source: dummySourceConfig,
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    integration: {
                      name: 'SHOPIFY',
                    },
                    topic: 'orders_updated',
                    cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
                    checkout_token: '84ad78572dae52a8cbea7d55371afe89',
                    shopifyDetails: {
                      id: 5778367414385,
                      admin_graphql_api_id: 'gid://shopify/Order/5778367414385',
                      app_id: 580111,
                      browser_ip: '139.5.255.205',
                      cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
                      checkout_id: 35550298931313,
                      checkout_token: '84ad78572dae52a8cbea7d55371afe89',
                      confirmation_number: 'DPPARQ8UJ',
                      contact_email: 'henry@wfls.com',
                      created_at: '2024-11-05T21:54:49-05:00',
                      currency: 'USD',
                      current_subtotal_price: '600.00',
                      current_subtotal_price_set: {
                        shop_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                      },
                      current_total_discounts: '0.00',
                      current_total_discounts_set: {
                        shop_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                      },
                      current_total_price: '600.00',
                      current_total_price_set: {
                        shop_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                      },
                      current_total_tax: '0.00',
                      current_total_tax_set: {
                        shop_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                      },
                      customer_locale: 'en-US',
                      discount_codes: [],
                      email: 'henry@wfls.com',
                      estimated_taxes: false,
                      merchant_of_record_app_id: null,
                      name: '#1017',
                      note: null,
                      note_attributes,
                      number: 17,
                      order_number: 1017,
                      order_status_url:
                        'https://pixel-testing-rs.myshopify.com/59026964593/orders/676613a0027fc8240e16d67fdc9f5ac8/authenticate?key=a70bbe7ec8abcc46b77e4331e4df8c60',
                      original_total_additional_fees_set: null,
                      original_total_duties_set: null,
                      payment_gateway_names: ['bogus'],
                      phone: null,
                      presentment_currency: 'USD',
                      source_identifier: '4d92cf60cc24a1bd95929e17ead9845f',
                      subtotal_price: '600.00',
                      subtotal_price_set: {
                        shop_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                      },
                      tax_lines: [],
                      token: '676613a0027fc8240e16d67fdc9f5ac8',
                      total_discounts: '0.00',
                      total_discounts_set: {
                        shop_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                      },
                      total_line_items_price: '600.00',
                      total_line_items_price_set: {
                        shop_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                      },
                      total_price: '600.00',
                      total_price_set: {
                        shop_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '600.00',
                          currency_code: 'USD',
                        },
                      },
                      total_shipping_price_set: {
                        shop_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                      },
                      total_tax: '0.00',
                      total_tax_set: {
                        shop_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                        presentment_money: {
                          amount: '0.00',
                          currency_code: 'USD',
                        },
                      },
                      total_weight: 0,
                      updated_at: '2024-11-05T21:54:50-05:00',
                      user_id: null,
                      billing_address: {
                        first_name: 'yodi',
                        address1: 'Yuma Proving Ground',
                        phone: null,
                        city: 'Yuma Proving Ground',
                        zip: '85365',
                        province: 'Arizona',
                        country: 'United States',
                        last_name: 'waffles',
                        address2: 'suite 001',
                        company: null,
                        latitude: 33.0177811,
                        longitude: -114.2525392,
                        name: 'yodi waffles',
                        country_code: 'US',
                        province_code: 'AZ',
                      },
                      customer: {
                        id: 7358220173425,
                        email: 'henry@wfls.com',
                        created_at: '2024-10-23T16:03:11-04:00',
                        updated_at: '2024-11-05T21:54:49-05:00',
                        first_name: 'yodi',
                        last_name: 'waffles',
                        state: 'disabled',
                        note: null,
                        verified_email: true,
                        multipass_identifier: null,
                        tax_exempt: false,
                        phone: null,
                        email_marketing_consent: {
                          state: 'not_subscribed',
                          opt_in_level: 'single_opt_in',
                          consent_updated_at: null,
                        },
                        sms_marketing_consent: null,
                        tags: '',
                        currency: 'USD',
                        tax_exemptions: [],
                        admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
                        default_address: {
                          id: 8715246862449,
                          customer_id: 7358220173425,
                          first_name: 'henry',
                          last_name: 'waffles',
                          company: null,
                          address1: 'Yuimaru Kitchen',
                          address2: '6',
                          city: 'Johnson City',
                          province: 'Tennessee',
                          country: 'United States',
                          zip: '37604',
                          phone: null,
                          name: 'henry waffles',
                          province_code: 'TN',
                          country_code: 'US',
                          country_name: 'United States',
                          default: true,
                        },
                      },
                      line_items: [
                        {
                          id: 14234727743601,
                          admin_graphql_api_id: 'gid://shopify/LineItem/14234727743601',
                          attributed_staffs: [],
                          current_quantity: 1,
                          fulfillable_quantity: 1,
                          fulfillment_service: 'manual',
                          fulfillment_status: null,
                          gift_card: false,
                          grams: 0,
                          name: 'The Collection Snowboard: Hydrogen',
                          price: '600.00',
                          price_set: {
                            shop_money: {
                              amount: '600.00',
                              currency_code: 'USD',
                            },
                            presentment_money: {
                              amount: '600.00',
                              currency_code: 'USD',
                            },
                          },
                          product_exists: true,
                          product_id: 7234590408817,
                          properties: [],
                          quantity: 1,
                          requires_shipping: true,
                          sku: '',
                          taxable: true,
                          title: 'The Collection Snowboard: Hydrogen',
                          total_discount: '0.00',
                          total_discount_set: {
                            shop_money: {
                              amount: '0.00',
                              currency_code: 'USD',
                            },
                            presentment_money: {
                              amount: '0.00',
                              currency_code: 'USD',
                            },
                          },
                          variant_id: 41327142600817,
                          variant_inventory_management: 'shopify',
                          variant_title: null,
                          vendor: 'Hydrogen Vendor',
                          tax_lines: [],
                          duties: [],
                          discount_allocations: [],
                        },
                      ],
                      payment_terms: null,
                      refunds: [],
                      shipping_address: {
                        first_name: 'henry',
                        address1: 'Yuimaru Kitchen',
                        phone: null,
                        city: 'Johnson City',
                        zip: '37604',
                        province: 'Tennessee',
                        country: 'United States',
                        last_name: 'waffles',
                        address2: '6',
                        company: null,
                        latitude: 36.3528845,
                        longitude: -82.4006335,
                        name: 'henry waffles',
                        country_code: 'US',
                        province_code: 'TN',
                      },
                    },
                    order_token: '676613a0027fc8240e16d67fdc9f5ac8',
                  },
                  integrations: {
                    SHOPIFY: true,
                  },
                  type: 'track',
                  event: 'Order Updated',
                  properties: {
                    order_id: 5778367414385,
                    value: '600.00',
                    tax: '0.00',
                    currency: 'USD',
                    products: [
                      {
                        product_id: 7234590408817,
                        title: 'The Collection Snowboard: Hydrogen',
                        price: '600.00',
                        brand: 'Hydrogen Vendor',
                        quantity: 1,
                      },
                    ],
                  },
                  userId: '7358220173425',
                  traits: {
                    email: 'henry@wfls.com',
                    firstName: 'yodi',
                    lastName: 'waffles',
                    address: {
                      id: 8715246862449,
                      customer_id: 7358220173425,
                      first_name: 'henry',
                      last_name: 'waffles',
                      company: null,
                      address1: 'Yuimaru Kitchen',
                      address2: '6',
                      city: 'Johnson City',
                      province: 'Tennessee',
                      country: 'United States',
                      zip: '37604',
                      phone: null,
                      name: 'henry waffles',
                      province_code: 'TN',
                      country_code: 'US',
                      country_name: 'United States',
                      default: true,
                    },
                    state: 'disabled',
                    verifiedEmail: true,
                    taxExempt: false,
                    tags: '',
                    currency: 'USD',
                    taxExemptions: [],
                    adminGraphqlApiId: 'gid://shopify/Customer/7358220173425',
                    shippingAddress: {
                      first_name: 'henry',
                      address1: 'Yuimaru Kitchen',
                      phone: null,
                      city: 'Johnson City',
                      zip: '37604',
                      province: 'Tennessee',
                      country: 'United States',
                      last_name: 'waffles',
                      address2: '6',
                      company: null,
                      latitude: 36.3528845,
                      longitude: -82.4006335,
                      name: 'henry waffles',
                      country_code: 'US',
                      province_code: 'TN',
                    },
                    billingAddress: {
                      first_name: 'yodi',
                      address1: 'Yuma Proving Ground',
                      phone: null,
                      city: 'Yuma Proving Ground',
                      zip: '85365',
                      province: 'Arizona',
                      country: 'United States',
                      last_name: 'waffles',
                      address2: 'suite 001',
                      company: null,
                      latitude: 33.0177811,
                      longitude: -114.2525392,
                      name: 'yodi waffles',
                      country_code: 'US',
                      province_code: 'AZ',
                    },
                  },
                  timestamp: '2024-11-06T02:54:50.000Z',
                  anonymousId: '50ead33e-d763-4854-b0ab-765859ef05cb',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    id: 'c004',
    name: 'shopify',
    description: 'Track Call -> Order Created event from Pixel app',
    module: 'source',
    version: 'v1',
    input: {
      request: {
        body: [
          {
            event: {
              id: 5778367414385,
              admin_graphql_api_id: 'gid://shopify/Order/5778367414385',
              app_id: 580111,
              browser_ip: '139.5.255.205',
              cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
              checkout_id: 35550298931313,
              checkout_token: '84ad78572dae52a8cbea7d55371afe89',
              confirmation_number: 'DPPARQ8UJ',
              contact_email: 'henry@wfls.com',
              created_at: '2024-11-05T21:54:49-05:00',
              currency: 'USD',
              current_subtotal_price: '600.00',
              current_total_discounts: '0.00',
              current_total_price: '600.00',
              current_total_tax: '0.00',
              email: 'henry@wfls.com',
              name: '#1017',
              note_attributes,
              order_number: 1017,
              order_status_url:
                'https://pixel-testing-rs.myshopify.com/59026964593/orders/676613a0027fc8240e16d67fdc9f5ac8/authenticate?key=a70bbe7ec8abcc46b77e4331e4df8c60',
              phone: null,
              presentment_currency: 'USD',
              subtotal_price: '600.00',
              token: '676613a0027fc8240e16d67fdc9f5ac8',
              total_discounts: '0.00',
              total_line_items_price: '600.00',
              total_outstanding: '0.00',
              total_price: '600.00',
              total_tax: '0.00',
              updated_at: '2024-11-05T21:54:50-05:00',
              user_id: null,
              billing_address: {
                first_name: 'yodi',
                address1: 'Yuma Proving Ground',
                phone: null,
                city: 'Yuma Proving Ground',
                zip: '85365',
                province: 'Arizona',
                country: 'United States',
                last_name: 'waffles',
                address2: 'suite 001',
                company: null,
                latitude: 33.0177811,
                longitude: -114.2525392,
                name: 'yodi waffles',
                country_code: 'US',
                province_code: 'AZ',
              },
              customer: {
                id: 7358220173425,
                email: 'henry@wfls.com',
                created_at: '2024-10-23T16:03:11-04:00',
                updated_at: '2024-11-05T21:54:49-05:00',
                first_name: 'yodi',
                last_name: 'waffles',
                state: 'disabled',
                phone: null,
                currency: 'USD',
                tax_exemptions: [],
                admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
                default_address: {
                  id: 8715246862449,
                  customer_id: 7358220173425,
                  first_name: 'henry',
                  last_name: 'waffles',
                  company: null,
                  address1: 'Yuimaru Kitchen',
                  address2: '6',
                  city: 'Johnson City',
                  province: 'Tennessee',
                  country: 'United States',
                  zip: '37604',
                  phone: null,
                  name: 'henry waffles',
                  province_code: 'TN',
                  country_code: 'US',
                  country_name: 'United States',
                  default: true,
                },
              },
              line_items: [
                {
                  id: 14234727743601,
                  current_quantity: 1,
                  fulfillable_quantity: 1,
                  fulfillment_service: 'manual',
                  gift_card: false,
                  grams: 0,
                  name: 'The Collection Snowboard: Hydrogen',
                  price: '600.00',
                  product_id: 7234590408817,
                  quantity: 1,
                  requires_shipping: true,
                  sku: '',
                  taxable: true,
                  title: 'The Collection Snowboard: Hydrogen',
                  total_discount: '0.00',
                  variant_id: 41327142600817,
                  variant_inventory_management: 'shopify',
                  variant_title: null,
                  vendor: 'Hydrogen Vendor',
                },
              ],
              shipping_address: {
                first_name: 'henry',
                address1: 'Yuimaru Kitchen',
                phone: null,
                city: 'Johnson City',
                zip: '37604',
                province: 'Tennessee',
                country: 'United States',
                last_name: 'waffles',
                address2: '6',
                company: null,
                latitude: 36.3528845,
                longitude: -82.4006335,
                name: 'henry waffles',
                country_code: 'US',
                province_code: 'TN',
              },
              query_parameters: {
                topic: ['orders_create'],
                version: ['pixel'],
                writeKey: ['2mw9SN679HngnZkCHT4oSVVBVmb'],
              },
            },
            source: dummySourceConfig,
            query_parameters: {
              topic: ['carts_update'],
              writeKey: ['2mw9SN679HngnXXXHT4oSVVBVmb'],
              version: ['pixel'],
            },
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: {
                      eventOrigin: 'server',
                      name: 'RudderStack Shopify Cloud',
                      version: '2.0.0',
                    },
                    integration: {
                      name: 'SHOPIFY',
                    },
                    topic: 'orders_create',
                    cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
                    checkout_token: '84ad78572dae52a8cbea7d55371afe89',
                    shopifyDetails: {
                      id: 5778367414385,
                      admin_graphql_api_id: 'gid://shopify/Order/5778367414385',
                      app_id: 580111,
                      browser_ip: '139.5.255.205',
                      cart_token: 'Z2NwLXVzLWVhc3QxOjAxSkJaTUVRSjgzNUJUN1BTNjEzRFdRUFFQ',
                      checkout_id: 35550298931313,
                      checkout_token: '84ad78572dae52a8cbea7d55371afe89',
                      confirmation_number: 'DPPARQ8UJ',
                      contact_email: 'henry@wfls.com',
                      created_at: '2024-11-05T21:54:49-05:00',
                      currency: 'USD',
                      current_subtotal_price: '600.00',
                      current_total_discounts: '0.00',
                      current_total_price: '600.00',
                      current_total_tax: '0.00',
                      email: 'henry@wfls.com',
                      name: '#1017',
                      note_attributes,
                      order_number: 1017,
                      order_status_url:
                        'https://pixel-testing-rs.myshopify.com/59026964593/orders/676613a0027fc8240e16d67fdc9f5ac8/authenticate?key=a70bbe7ec8abcc46b77e4331e4df8c60',
                      phone: null,
                      presentment_currency: 'USD',
                      subtotal_price: '600.00',
                      token: '676613a0027fc8240e16d67fdc9f5ac8',
                      total_discounts: '0.00',
                      total_line_items_price: '600.00',
                      total_outstanding: '0.00',
                      total_price: '600.00',
                      total_tax: '0.00',
                      updated_at: '2024-11-05T21:54:50-05:00',
                      user_id: null,
                      billing_address: {
                        first_name: 'yodi',
                        address1: 'Yuma Proving Ground',
                        phone: null,
                        city: 'Yuma Proving Ground',
                        zip: '85365',
                        province: 'Arizona',
                        country: 'United States',
                        last_name: 'waffles',
                        address2: 'suite 001',
                        company: null,
                        latitude: 33.0177811,
                        longitude: -114.2525392,
                        name: 'yodi waffles',
                        country_code: 'US',
                        province_code: 'AZ',
                      },
                      customer: {
                        id: 7358220173425,
                        email: 'henry@wfls.com',
                        created_at: '2024-10-23T16:03:11-04:00',
                        updated_at: '2024-11-05T21:54:49-05:00',
                        first_name: 'yodi',
                        last_name: 'waffles',
                        state: 'disabled',
                        phone: null,
                        currency: 'USD',
                        tax_exemptions: [],
                        admin_graphql_api_id: 'gid://shopify/Customer/7358220173425',
                        default_address: {
                          id: 8715246862449,
                          customer_id: 7358220173425,
                          first_name: 'henry',
                          last_name: 'waffles',
                          company: null,
                          address1: 'Yuimaru Kitchen',
                          address2: '6',
                          city: 'Johnson City',
                          province: 'Tennessee',
                          country: 'United States',
                          zip: '37604',
                          phone: null,
                          name: 'henry waffles',
                          province_code: 'TN',
                          country_code: 'US',
                          country_name: 'United States',
                          default: true,
                        },
                      },
                      line_items: [
                        {
                          id: 14234727743601,
                          current_quantity: 1,
                          fulfillable_quantity: 1,
                          fulfillment_service: 'manual',
                          gift_card: false,
                          grams: 0,
                          name: 'The Collection Snowboard: Hydrogen',
                          price: '600.00',
                          product_id: 7234590408817,
                          quantity: 1,
                          requires_shipping: true,
                          sku: '',
                          taxable: true,
                          title: 'The Collection Snowboard: Hydrogen',
                          total_discount: '0.00',
                          variant_id: 41327142600817,
                          variant_inventory_management: 'shopify',
                          variant_title: null,
                          vendor: 'Hydrogen Vendor',
                        },
                      ],
                      shipping_address: {
                        first_name: 'henry',
                        address1: 'Yuimaru Kitchen',
                        phone: null,
                        city: 'Johnson City',
                        zip: '37604',
                        province: 'Tennessee',
                        country: 'United States',
                        last_name: 'waffles',
                        address2: '6',
                        company: null,
                        latitude: 36.3528845,
                        longitude: -82.4006335,
                        name: 'henry waffles',
                        country_code: 'US',
                        province_code: 'TN',
                      },
                    },
                  },
                  integrations: {
                    SHOPIFY: true,
                  },
                  type: 'track',
                  event: 'Order Created',
                  properties: {
                    order_id: 5778367414385,
                    value: '600.00',
                    tax: '0.00',
                    currency: 'USD',
                    products: [
                      {
                        product_id: 7234590408817,
                        title: 'The Collection Snowboard: Hydrogen',
                        price: '600.00',
                        brand: 'Hydrogen Vendor',
                        quantity: 1,
                      },
                    ],
                  },
                  userId: '7358220173425',
                  traits: {
                    email: 'henry@wfls.com',
                    firstName: 'yodi',
                    lastName: 'waffles',
                    address: {
                      id: 8715246862449,
                      customer_id: 7358220173425,
                      first_name: 'henry',
                      last_name: 'waffles',
                      company: null,
                      address1: 'Yuimaru Kitchen',
                      address2: '6',
                      city: 'Johnson City',
                      province: 'Tennessee',
                      country: 'United States',
                      zip: '37604',
                      phone: null,
                      name: 'henry waffles',
                      province_code: 'TN',
                      country_code: 'US',
                      country_name: 'United States',
                      default: true,
                    },
                    state: 'disabled',
                    currency: 'USD',
                    taxExemptions: [],
                    adminGraphqlApiId: 'gid://shopify/Customer/7358220173425',
                    shippingAddress: {
                      first_name: 'henry',
                      address1: 'Yuimaru Kitchen',
                      phone: null,
                      city: 'Johnson City',
                      zip: '37604',
                      province: 'Tennessee',
                      country: 'United States',
                      last_name: 'waffles',
                      address2: '6',
                      company: null,
                      latitude: 36.3528845,
                      longitude: -82.4006335,
                      name: 'henry waffles',
                      country_code: 'US',
                      province_code: 'TN',
                    },
                    billingAddress: {
                      first_name: 'yodi',
                      address1: 'Yuma Proving Ground',
                      phone: null,
                      city: 'Yuma Proving Ground',
                      zip: '85365',
                      province: 'Arizona',
                      country: 'United States',
                      last_name: 'waffles',
                      address2: 'suite 001',
                      company: null,
                      latitude: 33.0177811,
                      longitude: -114.2525392,
                      name: 'yodi waffles',
                      country_code: 'US',
                      province_code: 'AZ',
                    },
                  },
                  timestamp: '2024-11-06T02:54:50.000Z',
                  anonymousId: '50ead33e-d763-4854-b0ab-765859ef05cb',
                },
              ],
            },
          },
        ],
      },
    },
  },
];
