version: 0.0
os: linux
files:
  - source: scripts/dest-transformer.service
    destination: /etc/systemd/system/
  - source: /
    destination: /home/ubuntu/rudder-transformer
permissions:
  - object: /home/ubuntu/rudder-transformer
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
