version: 0.2
env:
  parameter-store:
    dockerhub_passwd: "/prod/codebuild/dockerhub-password"

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - docker login --username rudderlabs --password $dockerhub_passwd
  build:
    commands:
      - VERSION="$(date '+%d%m%Y.%H%M%S')"
      - ls
      - docker build --build-arg version=${VERSION} -t rudderlabs/rudder-transformer:$VERSION -f Dockerfile .
      - docker run rudderlabs/rudder-transformer:$VERSION npm test
      - echo $?
      - docker tag rudderlabs/rudder-transformer:$VERSION rudderlabs/rudder-transformer:latest
  post_build:
    commands:
      - docker push rudderlabs/rudder-transformer:$VERSION
      - docker push rudderlabs/rudder-transformer:latest
artifacts:
  files:
    - "**/*"
