version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - docker login --username rudderlabs --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - VERSION=$(head -1 .version)
      - ls
      - echo build Docker image on `date`
      - docker build --build-arg version=${VERSION} -t rudderlabs/rudder-transformer:$VERSION -f Dockerfile .
      - docker run rudderlabs/rudder-transformer:$VERSION npm test
      - echo $?
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to docker hub...
      - docker push rudderlabs/rudder-transformer:$VERSION
artifacts:
  files:
    - "**/*"
