export const data = [
  {
    name: 'zendesk',
    description: 'Test 0',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: {},
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              integrations: { All: true },
              messageId: '0bab70e8-bf2f-449a-a19b-ca6e3bfed9b7',
              originalTimestamp: '2020-03-23T18:27:28.98Z',
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51573',
              sentAt: '2020-03-23T18:27:28.981Z',
              timestamp: '2020-03-23T23:57:29.021+05:30',
              type: 'identify',
              userId: 'abcd-124',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Missing required value from "name"',
            statTags: {
              destType: 'ZENDESK',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 1',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.15',
                },
                campaign: {},
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.15' },
                locale: 'en-US',
                os: { name: '', version: '' },
                page: {
                  path: '/home/a/Desktop/pybox/Bingads.html',
                  referrer: '$direct',
                  referring_domain: '',
                  search: '',
                  title: 'Rudder Test',
                  url: 'file:///home/a/Desktop/pybox/Bingads.html',
                },
                screen: { density: 1 },
                traits: { country: 'UK', name: 'John Wick', userId: 'abcd-124' },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              event: 'Rudderlabs Track me',
              integrations: { All: true },
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              originalTimestamp: '2021-03-25T14:36:47.695Z',
              properties: {
                category: 'category',
                label: 'label',
                userId: 'abcd-124',
                value: 'value',
              },
              receivedAt: '2021-03-25T20:06:47.701+05:30',
              request_ip: '[::1]',
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              sentAt: '2021-03-25T14:36:47.695Z',
              timestamp: '2021-03-25T20:06:47.701+05:30',
              type: 'track',
              userId: '0000000000',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 47,
              destinationType: 'ZENDESK',
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              messageIds: null,
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              receivedAt: '2021-03-25T20:06:47.701+05:30',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              DestinationDefinition: {
                ID: '1pvRK5OiIrZkhCbFISQY5e55hX1',
                Name: 'ZENDESK',
                DisplayName: 'Zendesk',
                Config: {
                  destConfig: {
                    defaultConfig: [
                      'email',
                      'apiToken',
                      'domain',
                      'createUsersAsVerified',
                      'sendGroupCallsWithoutUserId',
                      'removeUsersFromOrganization',
                    ],
                  },
                  excludeKeys: [],
                  includeKeys: [],
                  routerTransform: false,
                  secretKeys: ['apiToken'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                  ],
                },
                ResponseRules: {},
              },
              Config: {
                apiToken: 'myDummyApiToken3',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'test@rudder.com',
                removeUsersFromOrganization: false,
                sendGroupCallsWithoutUserId: false,
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            libraries: [],
            request: { query: {} },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'email not found in traits.',
            statTags: {
              destType: 'ZENDESK',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 47,
              destinationType: 'ZENDESK',
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              messageIds: null,
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              receivedAt: '2021-03-25T20:06:47.701+05:30',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 2',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: { email: 'example124@email.com', name: 'abcd124' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              integrations: { All: true },
              messageId: '0bab70e8-bf2f-449a-a19b-ca6e3bfed9b7',
              originalTimestamp: '2020-03-23T18:27:28.98Z',
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51573',
              sentAt: '2020-03-23T18:27:28.981Z',
              timestamp: '2020-03-23T23:57:29.021+05:30',
              type: 'identify',
              userId: 'abcd-124',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'example124@email.com',
                    name: 'abcd124',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124' },
                    verified: true,
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 3',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: { email: 'example124@email.com', name: 'abcd124' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              groupId: 'group-124',
              integrations: { All: true },
              messageId: '2d54ba80-ce5f-4bcb-b1d7-7587e7a865fc',
              originalTimestamp: '2020-03-23T18:27:28.983Z',
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51574',
              sentAt: '2020-03-23T18:27:28.983Z',
              timestamp: '2020-03-23T23:57:29.022+05:30',
              traits: {
                domainNames: 'cw124.com',
                email: 'group_email_124@xyz.com',
                name: 'test-org124',
              },
              type: 'group',
              userId: 'abcd-124',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/organization_memberships.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: {
                JSON: {
                  organization_membership: { user_id: 900113780483, organization_id: 900001329943 },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 4',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
                sourceName: 'abc',
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: { email: 'example124@email.com', name: 'abcd124' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              event: 'test-track-event124',
              integrations: { All: true },
              messageId: '1c272800-d4f2-4fe6-af81-6429b7cb029f',
              originalTimestamp: '2020-03-23T18:27:28.984Z',
              properties: { test_prop: 'test_prop_value_124' },
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51575',
              sentAt: '2020-03-23T18:27:28.985Z',
              timestamp: '2020-03-23T23:57:29.021+05:30',
              type: 'track',
              userId: 'abcd-124',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/events',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: {
                JSON: {
                  event: {
                    description: 'test-track-event124',
                    type: 'test-track-event124',
                    source: 'abc',
                    properties: { test_prop: 'test_prop_value_124' },
                  },
                  profile: {
                    type: 'test-track-event124',
                    source: 'abc',
                    identifiers: [{ type: 'email', value: 'example124@email.com' }],
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 5',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              type: 'identify',
              sentAt: '2020-03-17T12:16:56.003Z',
              userId: 'abcd-124',
              channel: 'web',
              context: {
                ip: '0.0.0.0',
                os: { name: '', version: '' },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.1.0-beta.2',
                  namespace: 'com.rudderlabs.javascript',
                },
                locale: 'en-GB',
                screen: { density: 2 },
                traits: {
                  name: 'abcd124',
                  email: 'example124@email.com',
                  company: { id: 900001329943, name: 'test', remove: true },
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
              },
              messageId: 'd26b4de7-8bb5-4554-91aa-c80b8b2182e0',
              anonymousId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
              integrations: { All: true },
              originalTimestamp: '2020-03-17T12:16:56.002Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'DELETE',
              endpoint:
                'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/organization_memberships/900004877903.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: { JSON: {}, XML: {}, JSON_ARRAY: {}, FORM: {} },
              files: {},
              userId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'example124@email.com',
                    name: 'abcd124',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124' },
                    verified: true,
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 6',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              type: 'identify',
              sentAt: '2020-03-17T12:16:56.003Z',
              userId: 'abcd-124',
              channel: 'web',
              context: {
                ip: '0.0.0.0',
                os: { name: '', version: '' },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.1.0-beta.2',
                  namespace: 'com.rudderlabs.javascript',
                },
                locale: 'en-GB',
                screen: { density: 2 },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
              },
              traits: {
                name: 'abcd124',
                email: 'example124@email.com',
                company: { id: 900001329943, name: 'test', remove: true },
              },
              messageId: 'd26b4de7-8bb5-4554-91aa-c80b8b2182e0',
              anonymousId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
              integrations: { All: true },
              originalTimestamp: '2020-03-17T12:16:56.002Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'DELETE',
              endpoint:
                'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/organization_memberships/900004877903.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: { JSON: {}, XML: {}, JSON_ARRAY: {}, FORM: {} },
              files: {},
              userId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'example124@email.com',
                    name: 'abcd124',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124' },
                    verified: true,
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 7',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.15',
                },
                campaign: {},
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.15' },
                locale: 'en-US',
                os: { name: '', version: '' },
                page: {
                  path: '/home/a/Desktop/pybox/Bingads.html',
                  referrer: '$direct',
                  referring_domain: '',
                  search: '',
                  title: 'Rudder Test',
                  url: 'file:///home/a/Desktop/pybox/Bingads.html',
                },
                screen: { density: 1 },
                traits: {
                  country: 'UK',
                  email: 'johnwick@example.com',
                  name: 'John Wick',
                  userId: 'abcd-124',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              integrations: { All: true },
              messageId: '32ccd509-25c3-4d12-9d0d-14ff73580e6c',
              originalTimestamp: '2021-03-25T10:08:21.734Z',
              receivedAt: '2021-03-25T15:38:21.751+05:30',
              request_ip: '[::1]',
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              sentAt: '2021-03-25T10:08:21.734Z',
              timestamp: '2021-03-25T15:38:21.751+05:30',
              type: 'identify',
              userId: '12345678',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 23,
              destinationType: 'ZENDESK',
              messageId: '32ccd509-25c3-4d12-9d0d-14ff73580e6c',
              messageIds: null,
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              receivedAt: '2021-03-25T15:38:21.751+05:30',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              DestinationDefinition: {
                ID: '1pvRK5OiIrZkhCbFISQY5e55hX1',
                Name: 'ZENDESK',
                DisplayName: 'Zendesk',
                Config: {
                  destConfig: {
                    defaultConfig: [
                      'email',
                      'apiToken',
                      'domain',
                      'createUsersAsVerified',
                      'sendGroupCallsWithoutUserId',
                      'removeUsersFromOrganization',
                    ],
                  },
                  excludeKeys: [],
                  includeKeys: [],
                  routerTransform: false,
                  secretKeys: ['apiToken'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                  ],
                },
                ResponseRules: {},
              },
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: false,
                domain: 'rudderlabshelp',
                email: 'test@rudder.com',
                removeUsersFromOrganization: false,
                sendGroupCallsWithoutUserId: false,
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            libraries: [],
            request: { query: {} },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
                'X-Zendesk-Marketplace-App-Id': '263241',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'johnwick@example.com',
                    name: 'John Wick',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124', country: 'UK' },
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '223b5f40-9543-4456-a7aa-945c43048185',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 23,
              destinationType: 'ZENDESK',
              messageId: '32ccd509-25c3-4d12-9d0d-14ff73580e6c',
              messageIds: null,
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              receivedAt: '2021-03-25T15:38:21.751+05:30',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 8',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.15',
                },
                campaign: {},
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.15' },
                locale: 'en-US',
                os: { name: '', version: '' },
                page: {
                  path: '/home/a/Desktop/pybox/Bingads.html',
                  referrer: '$direct',
                  referring_domain: '',
                  search: '',
                  title: 'Rudder Test',
                  url: 'file:///home/a/Desktop/pybox/Bingads.html',
                },
                screen: { density: 1 },
                traits: {
                  company: { id: 900001329943, remove: true },
                  country: 'UK',
                  email: 'johnwick@example.com',
                  name: 'John Wick',
                  userId: 'abcd-124',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              integrations: { All: true },
              messageId: '4070994c-1a63-493d-9dc4-889d45c01b1c',
              originalTimestamp: '2021-03-25T10:27:05.355Z',
              receivedAt: '2021-03-25T15:57:05.369+05:30',
              request_ip: '[::1]',
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              sentAt: '2021-03-25T10:27:05.355Z',
              timestamp: '2021-03-25T15:57:05.369+05:30',
              type: 'identify',
              userId: '12345678',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 31,
              destinationType: 'ZENDESK',
              messageId: '4070994c-1a63-493d-9dc4-889d45c01b1c',
              messageIds: null,
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              receivedAt: '2021-03-25T15:57:05.369+05:30',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              DestinationDefinition: {
                ID: '1pvRK5OiIrZkhCbFISQY5e55hX1',
                Name: 'ZENDESK',
                DisplayName: 'Zendesk',
                Config: {
                  destConfig: {
                    defaultConfig: [
                      'email',
                      'apiToken',
                      'domain',
                      'createUsersAsVerified',
                      'sendGroupCallsWithoutUserId',
                      'removeUsersFromOrganization',
                    ],
                  },
                  excludeKeys: [],
                  includeKeys: [],
                  routerTransform: false,
                  secretKeys: ['apiToken'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                  ],
                },
                ResponseRules: {},
              },
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: false,
                domain: 'rudderlabshelp',
                email: 'test@rudder.com',
                removeUsersFromOrganization: false,
                sendGroupCallsWithoutUserId: false,
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            libraries: [],
            request: { query: {} },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
                'X-Zendesk-Marketplace-App-Id': '263241',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'johnwick@example.com',
                    name: 'John Wick',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124', country: 'UK' },
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '223b5f40-9543-4456-a7aa-945c43048185',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 31,
              destinationType: 'ZENDESK',
              messageId: '4070994c-1a63-493d-9dc4-889d45c01b1c',
              messageIds: null,
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              receivedAt: '2021-03-25T15:57:05.369+05:30',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 9',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.15',
                },
                campaign: {},
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.15' },
                locale: 'en-US',
                os: { name: '', version: '' },
                page: {
                  path: '/home/a/Desktop/pybox/Bingads.html',
                  referrer: '$direct',
                  referring_domain: '',
                  search: '',
                  title: 'Rudder Test',
                  url: 'file:///home/a/Desktop/pybox/Bingads.html',
                },
                screen: { density: 1 },
                traits: {
                  company: { id: 900001329943, remove: true },
                  country: 'UK',
                  email: 'johnwick@example.com',
                  name: 'John Wick',
                  userId: 'abcd-124',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              integrations: { All: true },
              messageId: 'dd72a843-f865-4f7e-80eb-1f859e84e48c',
              originalTimestamp: '2021-03-25T12:48:42.188Z',
              receivedAt: '2021-03-25T18:18:42.193+05:30',
              request_ip: '[::1]',
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              sentAt: '2021-03-25T12:48:42.188Z',
              timestamp: '2021-03-25T18:18:42.193+05:30',
              type: 'identify',
              userId: '12345678',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 38,
              destinationType: 'ZENDESK',
              messageId: 'dd72a843-f865-4f7e-80eb-1f859e84e48c',
              messageIds: null,
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              receivedAt: '2021-03-25T18:18:42.193+05:30',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              DestinationDefinition: {
                ID: '1pvRK5OiIrZkhCbFISQY5e55hX1',
                Name: 'ZENDESK',
                DisplayName: 'Zendesk',
                Config: {
                  destConfig: {
                    defaultConfig: [
                      'email',
                      'apiToken',
                      'domain',
                      'createUsersAsVerified',
                      'sendGroupCallsWithoutUserId',
                      'removeUsersFromOrganization',
                    ],
                  },
                  excludeKeys: [],
                  includeKeys: [],
                  routerTransform: false,
                  secretKeys: ['apiToken'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                  ],
                },
                ResponseRules: {},
              },
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'test@rudder.com',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            libraries: [],
            request: { query: {} },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjQ=',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
                'X-Zendesk-Marketplace-App-Id': '263241',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'johnwick@example.com',
                    name: 'John Wick',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124', country: 'UK' },
                    verified: true,
                  },
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: '223b5f40-9543-4456-a7aa-945c43048185',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 38,
              destinationType: 'ZENDESK',
              messageId: 'dd72a843-f865-4f7e-80eb-1f859e84e48c',
              messageIds: null,
              rudderId: '32cea78b-a0d6-41de-9d23-201c49bd80b7',
              receivedAt: '2021-03-25T18:18:42.193+05:30',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 10',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.15',
                },
                campaign: {},
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.15' },
                locale: 'en-US',
                os: { name: '', version: '' },
                page: {
                  path: '/home/a/Desktop/pybox/Bingads.html',
                  referrer: '$direct',
                  referring_domain: '',
                  search: '',
                  title: 'Rudder Test',
                  url: 'file:///home/a/Desktop/pybox/Bingads.html',
                },
                screen: { density: 1 },
                traits: {
                  country: 'UK',
                  email: 'johnwick@example.com',
                  name: 'John Wick',
                  userId: 'abcd-124',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              event: 'Rudderlabs Track me',
              integrations: { All: true },
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              originalTimestamp: '2021-03-25T14:36:47.695Z',
              properties: {
                category: 'category',
                label: 'label',
                userId: 'abcd-124',
                value: 'value',
              },
              receivedAt: '2021-03-25T20:06:47.701+05:30',
              request_ip: '[::1]',
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              sentAt: '2021-03-25T14:36:47.695Z',
              timestamp: '2021-03-25T20:06:47.701+05:30',
              type: 'track',
              userId: '0000000000',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 47,
              destinationType: 'ZENDESK',
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              messageIds: null,
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              receivedAt: '2021-03-25T20:06:47.701+05:30',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              DestinationDefinition: {
                ID: '1pvRK5OiIrZkhCbFISQY5e55hX1',
                Name: 'ZENDESK',
                DisplayName: 'Zendesk',
                Config: {
                  destConfig: {
                    defaultConfig: [
                      'email',
                      'apiToken',
                      'domain',
                      'createUsersAsVerified',
                      'sendGroupCallsWithoutUserId',
                      'removeUsersFromOrganization',
                    ],
                  },
                  excludeKeys: [],
                  includeKeys: [],
                  routerTransform: false,
                  secretKeys: ['apiToken'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                  ],
                },
                ResponseRules: {},
              },
              Config: {
                apiToken: 'myDummyApiToken3',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'test@rudder.com',
                removeUsersFromOrganization: false,
                sendGroupCallsWithoutUserId: false,
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            libraries: [],
            request: { query: {} },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                FORM: {},
                JSON: {
                  event: {
                    description: 'Rudderlabs Track me',
                    properties: {
                      category: 'category',
                      label: 'label',
                      userId: 'abcd-124',
                      value: 'value',
                    },
                    source: 'Rudder',
                    type: 'Rudderlabs Track me',
                  },
                  profile: {
                    identifiers: [{ type: 'email', value: 'example124@email.com' }],
                    source: 'Rudder',
                    type: 'Rudderlabs Track me',
                  },
                },
                XML: {},
                JSON_ARRAY: {},
              },
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/events',
              files: {},
              headers: {
                Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjM=',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              method: 'POST',
              params: {},
              type: 'REST',
              userId: '223b5f40-9543-4456-a7aa-945c43048185',
              version: '1',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 47,
              destinationType: 'ZENDESK',
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              messageIds: null,
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              receivedAt: '2021-03-25T20:06:47.701+05:30',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 11',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.15',
                },
                campaign: {},
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.15' },
                locale: 'en-US',
                os: { name: '', version: '' },
                page: {
                  path: '/home/a/Desktop/pybox/Bingads.html',
                  referrer: '$direct',
                  referring_domain: '',
                  search: '',
                  title: 'Rudder Test',
                  url: 'file:///home/a/Desktop/pybox/Bingads.html',
                },
                screen: { density: 1 },
                traits: {
                  country: 'UK',
                  email: 'johnwick@example.com',
                  name: 'John Wick',
                  userId: 'abcd-124',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              event: 'Rudderlabs Track me',
              integrations: { All: true },
              messageId: '611a63fc-acb5-4a76-b4c3-e9cba27ca554',
              originalTimestamp: '2021-03-25T14:50:39.716Z',
              properties: {
                category: 'category',
                label: 'label',
                userId: 'abcd-124',
                value: 'value',
              },
              receivedAt: '2021-03-25T20:20:39.740+05:30',
              request_ip: '[::1]',
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              sentAt: '2021-03-25T14:50:39.717Z',
              timestamp: '2021-03-25T20:20:39.739+05:30',
              type: 'track',
              userId: '0000000000',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 48,
              destinationType: 'ZENDESK',
              messageId: '611a63fc-acb5-4a76-b4c3-e9cba27ca554',
              messageIds: null,
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              receivedAt: '2021-03-25T20:20:39.740+05:30',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              DestinationDefinition: {
                ID: '1pvRK5OiIrZkhCbFISQY5e55hX1',
                Name: 'ZENDESK',
                DisplayName: 'Zendesk',
                Config: {
                  destConfig: {
                    defaultConfig: [
                      'email',
                      'apiToken',
                      'domain',
                      'createUsersAsVerified',
                      'sendGroupCallsWithoutUserId',
                      'removeUsersFromOrganization',
                    ],
                  },
                  excludeKeys: [],
                  includeKeys: [],
                  routerTransform: false,
                  secretKeys: ['apiToken'],
                  supportedSourceTypes: [
                    'android',
                    'ios',
                    'web',
                    'unity',
                    'amp',
                    'cloud',
                    'reactnative',
                  ],
                },
                ResponseRules: {},
              },
              Config: {
                apiToken: 'myDummyApiToken3',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'test@rudder.com',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              Enabled: true,
              Transformations: [],
              IsProcessorEnabled: true,
            },
            libraries: [],
            request: { query: {} },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                FORM: {},
                JSON: {
                  event: {
                    description: 'Rudderlabs Track me',
                    properties: {
                      category: 'category',
                      label: 'label',
                      userId: 'abcd-124',
                      value: 'value',
                    },
                    source: 'Rudder',
                    type: 'Rudderlabs Track me',
                  },
                  profile: {
                    identifiers: [{ type: 'email', value: 'example124@email.com' }],
                    source: 'Rudder',
                    type: 'Rudderlabs Track me',
                  },
                },
                XML: {},
                JSON_ARRAY: {},
              },
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/events',
              files: {},
              headers: {
                Authorization: 'Basic dGVzdEBydWRkZXIuY29tL3Rva2VuOm15RHVtbXlBcGlUb2tlbjM=',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              method: 'POST',
              params: {},
              type: 'REST',
              userId: '223b5f40-9543-4456-a7aa-945c43048185',
              version: '1',
            },
            metadata: {
              sourceId: '1pvRRLH8kBCH6c88kNAQjRmhb8Z',
              destinationId: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              jobId: 48,
              destinationType: 'ZENDESK',
              messageId: '611a63fc-acb5-4a76-b4c3-e9cba27ca554',
              messageIds: null,
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              receivedAt: '2021-03-25T20:20:39.740+05:30',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 12',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken2',
                createUsersAsVerified: true,
                domain: 'blendohelp',
                email: 'myDummyUserName2',
                password: 'myDummyPwd2',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: false,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: { email: 'example1245@email.com', name: 'abcd1245' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              groupId: 'group-124',
              integrations: { All: true },
              messageId: '2d54ba80-ce5f-4bcb-b1d7-7587e7a865fc',
              originalTimestamp: '2020-03-23T18:27:28.983Z',
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51574',
              sentAt: '2020-03-23T18:27:28.983Z',
              timestamp: '2020-03-23T23:57:29.022+05:30',
              traits: {
                domainNames: 'cw124.com',
                email: 'group_email_124@xyz.com',
                name: 'group-124',
              },
              type: 'group',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'UserId is a mandatory field for group',
            statTags: {
              destType: 'ZENDESK',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 13',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken2',
                createUsersAsVerified: true,
                domain: 'blendohelp',
                email: 'myDummyUserName2',
                password: 'myDummyPwd2',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: { email: 'example1245@email.com', name: 'abcd1245' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              groupId: 'group-124',
              integrations: { All: true },
              messageId: '2d54ba80-ce5f-4bcb-b1d7-7587e7a865fc',
              originalTimestamp: '2020-03-23T18:27:28.983Z',
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51574',
              sentAt: '2020-03-23T18:27:28.983Z',
              timestamp: '2020-03-23T23:57:29.022+05:30',
              traits: {
                domainNames: 'cw124.com',
                email: 'group_email_124@xyz.com',
                name: 'group-124',
              },
              type: 'page',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Event type page is not supported',
            statTags: {
              destType: 'ZENDESK',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 14',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken2',
                createUsersAsVerified: true,
                domain: 'blendohelp',
                email: 'myDummyUserName2',
                password: 'myDummyPwd2',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              anonymousId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                traits: { email: 'example1245@email.com', name: 'abcd1245' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              groupId: 'group-124',
              integrations: { All: true },
              messageId: '2d54ba80-ce5f-4bcb-b1d7-7587e7a865fc',
              originalTimestamp: '2020-03-23T18:27:28.983Z',
              receivedAt: '2020-03-23T23:57:29.022+05:30',
              request_ip: '[::1]:51574',
              sentAt: '2020-03-23T18:27:28.983Z',
              timestamp: '2020-03-23T23:57:29.022+05:30',
              traits: {
                domainNames: 'cw124.com',
                email: 'group_email_124@xyz.com',
                name: 'group-124',
              },
              type: 'group',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://blendohelp.zendesk.com/api/v2/organizations/create_or_update.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMi90b2tlbjpteUR1bW15QXBpVG9rZW4y',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
                'X-Zendesk-Marketplace-App-Id': '263241',
              },
              params: {},
              body: {
                JSON: {
                  organization: {
                    name: 'group-124',
                    domain_names: 'cw124.com',
                    external_id: 'group-124',
                    organization_fields: { id: 'group-124', email: 'group_email_124@xyz.com' },
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '297b0750-934b-4411-b66c-9b418cdbc0c9',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 15',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              type: 'identify',
              sentAt: '2020-03-17T12:16:56.003Z',
              userId: 'abcd-124',
              channel: 'web',
              context: {
                ip: '0.0.0.0',
                os: { name: '', version: '' },
                app: {
                  name: 'RudderLabs JavaScript SDK',
                  build: '1.0.0',
                  version: '1.1.0-beta.2',
                  namespace: 'com.rudderlabs.javascript',
                },
                locale: 'en-GB',
                screen: { density: 2 },
                traits: {
                  name: 'abcd124',
                  company: { id: 900001329943, name: 'test', remove: true },
                },
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36',
              },
              messageId: 'd26b4de7-8bb5-4554-91aa-c80b8b2182e0',
              anonymousId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
              integrations: { All: true },
              originalTimestamp: '2020-03-17T12:16:56.002Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
                'X-Zendesk-Marketplace-App-Id': '263241',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    name: 'abcd124',
                    external_id: 'abcd-124',
                    user_fields: { id: 'abcd-124' },
                    verified: true,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: 'ba1bb99c-a979-45dc-93f0-7b0f2343ad4a',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 16',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiToken: 'myDummyApiToken4',
                createUsersAsVerified: true,
                domain: 'rudderlabshelp',
                email: 'myDummyUserName1',
                password: 'myDummyPwd1',
                removeUsersFromOrganization: true,
                sendGroupCallsWithoutUserId: true,
                searchByExternalId: true,
              },
              DestinationDefinition: {
                DisplayName: 'Zendesk',
                ID: '1YknZ1ENqB8UurJQJE2VrEA61tr',
                Name: 'ZENDESK',
              },
              Enabled: true,
              ID: 'xxxxxxxxxxxxxxxxxxxxxxxO51P',
              Name: 'zendesk',
              Transformations: [],
            },
            message: {
              channel: 'web',
              context: {
                app: {
                  build: '1.0.0',
                  name: 'RudderLabs JavaScript SDK',
                  namespace: 'com.rudderlabs.javascript',
                  version: '1.1.0-beta.2',
                },
                ip: '0.0.0.0',
                library: { name: 'RudderLabs JavaScript SDK', version: '1.1.0-beta.2' },
                locale: 'en-GB',
                os: { name: '', version: '' },
                screen: { density: 2 },
                userAgent:
                  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
              },
              integrations: { All: true },
              messageId: '0bab70e8-bf2f-449a-a19b-ca6e3bfed9b7',
              request_ip: '[::1]:51573',
              type: 'identify',
              userId: 'abcd-144',
              traits: { email: 'example124@email.com', name: 'name_abcd144' },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                FORM: {},
                JSON: { identity: { type: 'email', value: 'example124@email.com' } },
                JSON_ARRAY: {},
              },
              type: 'REST',
              files: {},
              method: 'PUT',
              params: {},
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              version: '1',
              endpoint:
                'https://rudderlabshelp.zendesk.com/api/v2/users/900113780483/identities/7535981118877',
              userId: '',
            },
            statusCode: 200,
          },
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://rudderlabshelp.zendesk.com/api/v2/users/create_or_update.json',
              headers: {
                Authorization: 'Basic bXlEdW1teVVzZXJOYW1lMS90b2tlbjpteUR1bW15QXBpVG9rZW40',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
                'X-Zendesk-Marketplace-App-Id': '263241',
              },
              params: {},
              body: {
                JSON: {
                  user: {
                    email: 'example124@email.com',
                    name: 'name_abcd144',
                    external_id: 'abcd-144',
                    user_fields: { id: 'abcd-144' },
                    verified: true,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 17',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                traits: {
                  country: 'UK',
                  name: 'John Wick',
                  userId: 'exId-123',
                  email: 'testemail1@email',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              event: 'Order completed',
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              originalTimestamp: '2021-03-25T14:36:47.695Z',
              properties: {
                category: 'category',
                label: 'label',
                userId: 'exId-123',
                value: 'value',
              },
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              type: 'track',
              userId: '0000000000',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              Config: {
                apiToken: 'dummyApiToken',
                createUsersAsVerified: true,
                domain: 'rudderlabtest1',
                email: 'rudderlabtest1@email.com',
                removeUsersFromOrganization: false,
                sendGroupCallsWithoutUserId: false,
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                FORM: {},
                JSON: {
                  event: {
                    description: 'Order completed',
                    properties: {
                      category: 'category',
                      label: 'label',
                      userId: 'exId-123',
                      value: 'value',
                    },
                    source: 'Rudder',
                    type: 'Order completed',
                  },
                  profile: {
                    identifiers: [{ type: 'email', value: 'testemail1@email' }],
                    source: 'Rudder',
                    type: 'Order completed',
                  },
                },
                JSON_ARRAY: {},
                XML: {},
              },
              endpoint: 'https://rudderlabtest1.zendesk.com/api/v2/users/900113780483/events',
              files: {},
              headers: {
                Authorization: 'Basic cnVkZGVybGFidGVzdDFAZW1haWwuY29tL3Rva2VuOmR1bW15QXBpVG9rZW4=',
                'Content-Type': 'application/json',
                'X-Zendesk-Marketplace-App-Id': '263241',
                'X-Zendesk-Marketplace-Name': 'RudderStack',
                'X-Zendesk-Marketplace-Organization-Id': '3339',
              },
              method: 'POST',
              params: {},
              type: 'REST',
              userId: '223b5f40-9543-4456-a7aa-945c43048185',
              version: '1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'zendesk',
    description: 'Test 18',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: '223b5f40-9543-4456-a7aa-945c43048185',
              channel: 'web',
              context: {
                traits: {
                  country: 'UK',
                  name: 'John Wick',
                  userId: 'exId-123',
                  email: 'testemail2@email',
                },
                userAgent:
                  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
              },
              event: 'Order completed',
              messageId: '017f5227-ead3-4b7d-9794-1465022327be',
              originalTimestamp: '2021-03-25T14:36:47.695Z',
              properties: {
                category: 'category',
                label: 'label',
                userId: 'exId-123',
                value: 'value',
              },
              rudderId: 'd1b1b23f-c855-4b86-bad7-091f7bbe99fe',
              type: 'track',
              userId: '0000000000',
            },
            destination: {
              ID: 'xxxXXXXXXXXXXXxxxxxxxxxorpz',
              Name: 'Zendesk',
              Config: {
                apiToken: 'dummyApiToken',
                createUsersAsVerified: true,
                domain: 'rudderlabtest2',
                email: 'rudderlabtest2@email.com',
                removeUsersFromOrganization: false,
                sendGroupCallsWithoutUserId: false,
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error:
              "Failed to fetch user with email: testemail2@email due to Couldn't find user: John Wick",
            statTags: {
              destType: 'ZENDESK',
              errorCategory: 'network',
              errorType: 'aborted',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
];
