export const networkCallsData = [
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users-by-id/user@123/',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [
          { id: 21, member_since: '2022-09-12T12:40:30.548068Z', name: 'parkings group' },
          { id: 19, member_since: '2022-09-12T12:37:58.522773Z', name: 'rudder constructors' },
        ],
        created_at: '2022-09-06T11:52:48.828444Z',
        custom_id: 'user@123',
        email: null,
        first_seen: '2022-09-06T11:52:48.812722Z',
        gender: 'unknown',
        gravatar_url: null,
        id: 52,
        last_seen: '2022-09-06T12:35:17.230000Z',
        lists: [],
        name: null,
        notifications: true,
        page_views: 2,
        phone_number: '2345678901',
        score: 0,
        status: 'visitor',
        tags: [],
        unsubscribed: false,
        updated_at: '2022-09-12T03:19:33.356280Z',
        user_key: 'ngze13ffndcv',
        web_push_subscription: false,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/companies-by-id/group@795/',
    },
    httpRes: {
      data: {
        address: '6th floor,california,usa',
        category: null,
        city: null,
        companyowner: 'secret',
        country: 'usa',
        created_at: '2022-09-12T12:40:30.548068Z',
        custom_id: 'group@795',
        description: null,
        email: 'business@rudderstack.com',
        employees: [52],
        founded: '15 aug, 1947',
        id: 21,
        isprivatefunded: 'no',
        isprofitable: 'no',
        name: 'rudder ventures',
        phone_numbers: null,
        postal_code: null,
        region: null,
        size: null,
        tags: [],
        updated_at: '2022-09-13T11:23:09.481891Z',
        user_custom_id: 'user@123',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        address: '6th StSan FranciscoCA94103USAtestuser',
        city: 'San Francisco',
        custom_id: 'group@795',
        email: 'business@rudderstack.com',
        name: 'rudder ventures',
        postal_code: '94103',
        user_custom_id: 'user@123',
      },
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'PUT',

      url: 'https://commander.user.com/api/public/companies/21/',
    },
    httpRes: {
      data: {
        address: 'San FranciscoUSA94103CA6th St',
        city: 'San Francisco',
        companyowner: 'secret',
        country: 'usa',
        created_at: '2022-09-12T12:40:30.548068Z',
        custom_id: 'group@795',
        description: null,
        email: 'business@rudderstack.com',
        employees: [52],
        founded: '15 aug, 1947',
        id: 21,
        isprivatefunded: 'no',
        isprofitable: 'no',
        name: 'rudder ventures',
        phone_numbers: null,
        postal_code: null,
        region: null,
        size: null,
        tags: [],
        updated_at: '2022-09-13T11:47:31.748497Z',
        user_custom_id: 'user@123',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users/search/?email=test@rudderstack.com',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [],
        country: 'india',
        created_at: '2022-09-13T06:16:25.576355Z',
        custom_id: 'test@12',
        email: 'test@rudderstack.com',
        gender: 'male',
        google_url: 'www.google.com',
        id: 59,
        lists: [],
        name: 'test rudderstack',
        notifications: true,
        phone_number: '9225467887',
        score: 0,
        status: 'user',
        tags: [{ id: 5, name: 'productuser' }],
        unsubscribed: false,
        updated_at: '2022-09-13T06:16:25.576376Z',
        user_key: 'ctlfkj37dbag',
        web_push_subscription: false,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users/search/?key=lel1c5u1wuk8',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [],
        created_at: '2022-09-05T07:21:39.171977Z',
        email: 'rahulverma@test.com',
        gender: 'unknown',
        gravatar_url: null,
        id: 27,
        lists: [],
        name: 'rahul verma',
        notifications: true,
        phone_number: '+919432239876',
        score: 0,
        status: 'visitor',
        tags: [
          { id: 1, name: 'updated' },
          { id: 2, name: 'verified' },
        ],
        unsubscribed: false,
        updated_at: '2022-09-05T07:21:39.171990Z',
        user_key: 'lel1c5u1wuk8',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users/search/?email=test@rudderstack.com',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [],
        country: 'india',
        created_at: '2022-09-13T06:16:25.576355Z',
        custom_id: 'test@12',
        email: 'test@rudderstack.com',
        gender: 'male',
        google_url: 'www.google.com',
        id: 59,
        lists: [],
        name: 'test rudderstack',
        notifications: true,
        phone_number: '9225467887',
        score: 0,
        status: 'user',
        tags: [{ id: 5, name: 'productuser' }],
        unsubscribed: false,
        updated_at: '2022-09-13T06:16:25.576376Z',
        user_key: 'ctlfkj37dbag',
        web_push_subscription: false,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users-by-id/43/',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [],
        created_at: '2022-09-05T11:04:45.547861Z',
        custom_id: '43',
        email: null,
        first_seen: '2022-09-05T11:04:45.535122Z',
        gender: 'unknown',
        gravatar_url: null,
        id: 44,
        last_seen: null,
        lists: [],
        name: null,
        page_views: 0,
        score: 0,
        status: 'visitor',
        tags: [],
        unsubscribed: false,
        updated_at: '2022-09-05T11:04:45.547876Z',
        user_key: 'rpl0vjwysmc0',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users-by-id/43/',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [],
        created_at: '2022-09-05T11:04:45.547861Z',
        custom_id: '43',
        email: null,
        first_seen: '2022-09-05T11:04:45.535122Z',
        gender: 'unknown',
        gravatar_url: null,
        id: 44,
        last_seen: null,
        lists: [],
        name: null,
        page_views: 0,
        score: 0,
        status: 'visitor',
        tags: [],
        unsubscribed: false,
        updated_at: '2022-09-05T11:04:45.547876Z',
        user_key: 'rpl0vjwysmc0',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/users-by-id/user@123/',
    },
    httpRes: {
      data: {
        browser_language: null,
        companies: [
          { id: 21, member_since: '2022-09-12T12:40:30.548068Z', name: 'parkings group' },
          { id: 19, member_since: '2022-09-12T12:37:58.522773Z', name: 'rudder constructors' },
        ],
        created_at: '2022-09-06T11:52:48.828444Z',
        custom_id: 'user@123',
        email: null,
        first_seen: '2022-09-06T11:52:48.812722Z',
        gender: 'unknown',
        gravatar_url: null,
        id: 52,
        last_seen: '2022-09-06T12:35:17.230000Z',
        lists: [],
        name: null,
        notifications: true,
        page_views: 2,
        phone_number: '2345678901',
        score: 0,
        status: 'visitor',
        tags: [],
        unsubscribed: false,
        updated_at: '2022-09-12T03:19:33.356280Z',
        user_key: 'ngze13ffndcv',
        web_push_subscription: false,
      },
      status: 200,
    },
  },
  {
    httpReq: {
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'GET',

      url: 'https://commander.user.com/api/public/companies-by-id/group@795/',
    },
    httpRes: {
      data: {
        address: '6th floor,california,usa',
        category: null,
        city: null,
        companyowner: 'secret',
        country: 'usa',
        created_at: '2022-09-12T12:40:30.548068Z',
        custom_id: 'group@795',
        description: null,
        email: 'business@rudderstack.com',
        employees: [52],
        founded: '15 aug, 1947',
        id: 21,
        isprivatefunded: 'no',
        isprofitable: 'no',
        name: 'rudder ventures',
        phone_numbers: null,
        postal_code: null,
        region: null,
        size: null,
        tags: [],
        updated_at: '2022-09-13T11:23:09.481891Z',
        user_custom_id: 'user@123',
      },
      status: 200,
    },
  },
  {
    httpReq: {
      data: {
        address: '6th StSan FranciscoCA94103USAtestuser',
        city: 'San Francisco',
        custom_id: 'group@795',
        email: 'business@rudderstack.com',
        name: 'rudder ventures',
        postal_code: '94103',
        user_custom_id: 'user@123',
      },
      headers: {
        Authorization: 'Token dummyApiKey',
        'Content-Type': 'application/json',
      },

      method: 'PUT',

      url: 'https://commander.user.com/api/public/companies/21/',
    },
    httpRes: {
      data: {
        address: 'San FranciscoUSA94103CA6th St',
        city: 'San Francisco',
        companyowner: 'secret',
        country: 'usa',
        created_at: '2022-09-12T12:40:30.548068Z',
        custom_id: 'group@795',
        description: null,
        email: 'business@rudderstack.com',
        employees: [52],
        founded: '15 aug, 1947',
        id: 21,
        isprivatefunded: 'no',
        isprofitable: 'no',
        name: 'rudder ventures',
        phone_numbers: null,
        postal_code: null,
        region: null,
        size: null,
        tags: [],
        updated_at: '2022-09-13T11:47:31.748497Z',
        user_custom_id: 'user@123',
      },
      status: 200,
    },
  },
];
