/**
 * Transformer-owned list of destination types that are considered "CDK v2 family".
 */
export const cdkV2DestinationsMap: Record<string, true> = {
  ACCOIL_ANALYTICS: true,
  ALGOLIA: true,
  AUTOPILOT: true,
  BINGADS_AUDIENCE: true,
  BLOOMREACH: true,
  BLOOMREACH_CATALOG: true,
  BLUECORE: true,
  CLICKSEND: true,
  CORDIAL: true,
  DCM_FLOODLIGHT: true,
  DYNAMIC_YIELD: true,
  ELOQUA: true,
  EMARSYS: true,
  FULLSTORY: true,
  GLADLY: true,
  HEAP: true,
  HTTP: true,
  INTERCOM: true,
  KLAVIYO_BULK_UPLOAD: true,
  KOALA: true,
  KOCHAVA: true,
  KODDI: true,
  LAUNCHDARKLY_AUDIENCE: true,
  LINKEDIN_ADS: true,
  LINKEDIN_AUDIENCE: true,
  LOOPS: true,
  LYTICS: true,
  MOVABLE_INK: true,
  NEW_RELIC: true,
  NINETAILED: true,
  OPTIMIZELY_FULLSTACK: true,
  ORTTO: true,
  PINTEREST_TAG: true,
  RAKUTEN: true,
  REDDIT: true,
  SMARTLY: true,
  SPRIG: true,
  STATSIG: true,
  THE_TRADE_DESK: true,
  THE_TRADE_DESK_REAL_TIME_CONVERSIONS: true,
  TIKTOK_AUDIENCE: true,
  USERLIST: true,
  USERPILOT: true,
  VARIANCE: true,
  VITALLY: true,
  WEBHOOK: true,
  WEBHOOK_V2: true,
  WUNDERKIND: true,
  YANDEX_METRICA_OFFLINE_EVENTS: true,
  ZAPIER: true,
  ZOHO: true,
};
