export const data = [
  {
    name: 'webengage',
    description: 'Test 0',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              originalTimestamp: '2022-05-13T12:51:01.470Z',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Missing required value from "event"',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 1',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder123',
                  eventName: 'Order Completed',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 2',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder123',
                  eventName: 'Order Completed',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 3',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder123',
                  eventName: 'Order Completed',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 4',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder123',
                  eventName: 'Order Completed',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                  eventTime: '2021-09-01T15:46:51+0000',
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 5',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                FORM: {},
                JSON: {
                  userId: 'rudder123',
                  eventData: {
                    tax: 1,
                    name: 'home',
                    total: 20,
                    coupon: 'ImagePro',
                    revenue: 15,
                    category: 'Games',
                    currency: 'USD',
                    discount: 1.5,
                    order_id: '1234',
                    products: {
                      sku: 'G-32',
                      url: 'https://www.website.com/product/path',
                      name: 'Monopoly',
                      price: 14,
                      category: 'Games',
                      quantity: 1,
                      image_url: 'https://www.website.com/product/path.jpg',
                      is_restore: true,
                      introductory_price: '350',
                      presented_offering_identifier: '123erd',
                    },
                    shipping: 22,
                    product_id: '123',
                    affiliation: 'Apple Store',
                    checkout_id: '12345',
                    fetch_token: 'dummyFetchToken',
                  },
                  eventName: 'Order Completed',
                  eventTime: '2021-09-01T15:46:51+0000',
                },
                JSON_ARRAY: {},
              },
              type: 'REST',
              files: {},
              method: 'POST',
              params: {},
              headers: {
                Authorization: 'Bearer dummyApiKey',
                'Content-Type': 'application/json',
              },
              version: '1',
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 6',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              originalTimestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                FORM: {},
                JSON: {
                  userId: 'rudder123',
                  eventData: {
                    tax: 1,
                    name: 'home',
                    total: 20,
                    coupon: 'ImagePro',
                    revenue: 15,
                    category: 'Games',
                    currency: 'USD',
                    discount: 1.5,
                    order_id: '1234',
                    products: {
                      sku: 'G-32',
                      url: 'https://www.website.com/product/path',
                      name: 'Monopoly',
                      price: 14,
                      category: 'Games',
                      quantity: 1,
                      image_url: 'https://www.website.com/product/path.jpg',
                      is_restore: true,
                      introductory_price: '350',
                      presented_offering_identifier: '123erd',
                    },
                    shipping: 22,
                    product_id: '123',
                    affiliation: 'Apple Store',
                    checkout_id: '12345',
                    fetch_token: 'dummyFetchToken',
                  },
                  eventName: 'Order Completed',
                  eventTime: '2021-09-01T15:46:51+0000',
                },
                JSON_ARRAY: {},
              },
              type: 'REST',
              files: {},
              method: 'POST',
              params: {},
              headers: {
                Authorization: 'Bearer dummyApiKey',
                'Content-Type': 'application/json',
              },
              version: '1',
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 7',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'screen',
              userId: 'rudder123',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                FORM: {},
                JSON: {
                  userId: 'rudder123',
                  eventData: {
                    tax: 1,
                    name: 'home',
                    total: 20,
                    coupon: 'ImagePro',
                    revenue: 15,
                    category: 'Games',
                    currency: 'USD',
                    discount: 1.5,
                    order_id: '1234',
                    products: {
                      sku: 'G-32',
                      url: 'https://www.website.com/product/path',
                      name: 'Monopoly',
                      price: 14,
                      category: 'Games',
                      quantity: 1,
                      image_url: 'https://www.website.com/product/path.jpg',
                      is_restore: true,
                      introductory_price: '350',
                      presented_offering_identifier: '123erd',
                    },
                    shipping: 22,
                    product_id: '123',
                    affiliation: 'Apple Store',
                    checkout_id: '12345',
                    fetch_token: 'dummyFetchToken',
                  },
                  eventName: 'Viewed Games home screen',
                  eventTime: '2021-09-01T15:46:51+0000',
                },
                JSON_ARRAY: {},
              },
              type: 'REST',
              files: {},
              method: 'POST',
              params: {},
              headers: {
                Authorization: 'Bearer dummyApiKey',
                'Content-Type': 'application/json',
              },
              version: '1',
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 8',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'page',
              userId: 'rudder123',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder123',
                  eventName: 'Viewed Games home page',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                  eventTime: '2021-09-01T15:46:51+0000',
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 9',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'page',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Either one of userId or anonymousId is mandatory',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 10',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'master',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Event type master is not supported',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 11',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Event type is required',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 12',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'standard',
              },
            },
            message: {
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Event type is required',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 13',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'standard',
              },
            },
            message: {
              type: 'page',
              userId: 'rudder1232',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
              timestamp: '2021-09-01T15:46:51.000Z',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder1232',
                  eventName: 'Viewed Games home page',
                  eventTime: '2021-09-01T15:46:51+0000',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 14',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'standard',
              },
            },
            message: {
              type: 'page',
              userId: 'rudder1232',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder1232',
                  eventName: 'Viewed Games home page',
                  eventData: {
                    name: 'home',
                    category: 'Games',
                    checkout_id: '12345',
                    order_id: '1234',
                    affiliation: 'Apple Store',
                    total: 20,
                    revenue: 15,
                    shipping: 22,
                    tax: 1,
                    discount: 1.5,
                    coupon: 'ImagePro',
                    currency: 'USD',
                    fetch_token: 'dummyFetchToken',
                    product_id: '123',
                    products: {
                      sku: 'G-32',
                      name: 'Monopoly',
                      price: 14,
                      quantity: 1,
                      category: 'Games',
                      url: 'https://www.website.com/product/path',
                      image_url: 'https://www.website.com/product/path.jpg',
                      introductory_price: '350',
                      is_restore: true,
                      presented_offering_identifier: '123erd',
                    },
                  },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.webengage.com/v1/accounts/3bjsjdbh7/events',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 15',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              userId: 'rudder1236',
              channel: 'web',
              context: {
                ip: '14.5.67.21',
                app: {
                  build: '1',
                  name: 'RudderAndroidClient',
                  namespace: 'com.rudderstack.demo.android',
                  version: '1.0',
                },
                device: {
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  advertisingId: '1234sadf23',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '0.1.4' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                campaign: {
                  source: 'google',
                  medium: 'medium',
                  term: 'keyword',
                  content: 'some content',
                },
                os: { name: 'Android', version: '9' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Mumbai',
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for x86 Build/PSR1.180720.075)',
              },
              type: 'identify',
              traits: {
                birthday: '2022-05-13T12:51:01.470Z',
                email: 'chandan@companyname.com',
                name: 'James Doe',
                phone: '9876543210',
                firstname: 'James',
                lastname: 'Doe',
                age: '12',
                gender: 'F',
                country: 'INDIA',
                state: 'WB',
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                FORM: {},
                JSON: {
                  email: 'chandan@companyname.com',
                  phone: '9876543210',
                  userId: 'rudder1236',
                  lastName: 'Doe',
                  firstName: 'James',
                  gender: 'female',
                  birthDate: '2022-05-13T12:51:01+0000',
                  country: 'INDIA',
                  attributes: { age: '12', state: 'WB' },
                },
                JSON_ARRAY: {},
              },
              type: 'REST',
              files: {},
              method: 'POST',
              params: {},
              headers: {
                Authorization: 'Bearer dummyApiKey',
                'Content-Type': 'application/json',
              },
              version: '1',
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/users',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 16',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              userId: 'rudder1236',
              channel: 'web',
              context: {
                ip: '14.5.67.21',
                app: {
                  build: '1',
                  name: 'RudderAndroidClient',
                  namespace: 'com.rudderstack.demo.android',
                  version: '1.0',
                },
                device: {
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  advertisingId: '1234sadf23',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '0.1.4' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                campaign: {
                  source: 'google',
                  medium: 'medium',
                  term: 'keyword',
                  content: 'some content',
                },
                os: { name: 'Android', version: '9' },
                screen: { density: 420, height: 1794, width: 1080 },
                traits: {
                  email: 'chandan@companyname.com',
                  name: 'James Doe',
                  phone: '9876543210',
                  firstname: 'James',
                  lastname: 'Doe',
                  age: '12',
                  country: 'INDIA',
                  gender: 'MALE',
                  state: 'WB',
                },
                timezone: 'Asia/Mumbai',
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for x86 Build/PSR1.180720.075)',
              },
              type: 'identify',
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder1236',
                  firstName: 'James',
                  lastName: 'Doe',
                  email: 'chandan@companyname.com',
                  phone: '9876543210',
                  country: 'INDIA',
                  gender: 'male',
                  attributes: { age: '12', state: 'WB' },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/users',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 17',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              userId: 'rudder1235',
              channel: 'web',
              context: {
                ip: '14.5.67.21',
                app: {
                  build: '1',
                  name: 'RudderAndroidClient',
                  namespace: 'com.rudderstack.demo.android',
                  version: '1.0',
                },
                device: {
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  advertisingId: '1234sadf23',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '0.1.4' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                campaign: {
                  source: 'google',
                  medium: 'medium',
                  term: 'keyword',
                  content: 'some content',
                },
                os: { name: 'Android', version: '9' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Mumbai',
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for x86 Build/PSR1.180720.075)',
              },
              type: 'identify',
              traits: {
                email: 'chandan@companyname.com',
                name: 'James Doe',
                phone: '9876543210',
                firstname: 'James',
                lastname: 'Doe',
                age: '12',
                country: 'INDIA',
                state: 'WB',
                company: 'Alphabet Inc.',
                city: 'Amritsar',
                region: 'AB Colony',
                locality: 'IST',
                postalCode: '713390',
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer dummyApiKey',
              },
              params: {},
              body: {
                JSON: {
                  userId: 'rudder1235',
                  firstName: 'James',
                  lastName: 'Doe',
                  email: 'chandan@companyname.com',
                  phone: '9876543210',
                  postalCode: '713390',
                  country: 'INDIA',
                  city: 'Amritsar',
                  locality: 'IST',
                  region: 'AB Colony',
                  attributes: { age: '12', state: 'WB' },
                },
                JSON_ARRAY: {},
                XML: {},
                FORM: {},
              },
              files: {},
              endpoint: 'https://api.in.webengage.com/v1/accounts/3bjsjdbh7/users',
              userId: '',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 18',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              event: 'Order Completed',
              originalTimestamp: '202205-13T12:51:01.470Z',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Timestamp must be ISO format (YYYY-MM-DD)',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 19',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              type: 'track',
              userId: 'rudder123',
              originalTimestamp: '2022-05-13T12:51:01.470Z',
              properties: {
                name: 'home',
                category: 'Games',
                checkout_id: '12345',
                order_id: '1234',
                affiliation: 'Apple Store',
                total: 20,
                revenue: 15,
                shipping: 22,
                tax: 1,
                discount: 1.5,
                coupon: 'ImagePro',
                currency: 'USD',
                fetch_token: 'dummyFetchToken',
                product_id: '123',
                products: {
                  sku: 'G-32',
                  name: 'Monopoly',
                  price: 14,
                  quantity: 1,
                  category: 'Games',
                  url: 'https://www.website.com/product/path',
                  image_url: 'https://www.website.com/product/path.jpg',
                  introductory_price: '350',
                  is_restore: true,
                  presented_offering_identifier: '123erd',
                },
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Missing required value from "event"',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'webengage',
    description: 'Test 20',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            destination: {
              Config: {
                apiKey: 'dummyApiKey',
                licenseCode: '3bjsjdbh7',
                dataCenter: 'ind',
              },
            },
            message: {
              userId: 'rudder1236',
              channel: 'web',
              context: {
                ip: '14.5.67.21',
                app: {
                  build: '1',
                  name: 'RudderAndroidClient',
                  namespace: 'com.rudderstack.demo.android',
                  version: '1.0',
                },
                device: {
                  manufacturer: 'Google',
                  model: 'Android SDK built for x86',
                  name: 'generic_x86',
                  type: 'android',
                  advertisingId: '1234sadf23',
                },
                library: { name: 'com.rudderstack.android.sdk.core', version: '0.1.4' },
                locale: 'en-US',
                network: { carrier: 'Android', bluetooth: false, cellular: true, wifi: true },
                campaign: {
                  source: 'google',
                  medium: 'medium',
                  term: 'keyword',
                  content: 'some content',
                },
                os: { name: 'Android', version: '9' },
                screen: { density: 420, height: 1794, width: 1080 },
                timezone: 'Asia/Mumbai',
                userAgent:
                  'Dalvik/2.1.0 (Linux; U; Android 9; Android SDK built for x86 Build/PSR1.180720.075)',
              },
              type: 'identify',
              traits: {
                birthday: '202205-13T12:51:01.470Z',
                email: 'chandan@companyname.com',
                name: 'James Doe',
                phone: '9876543210',
                firstname: 'James',
                lastname: 'Doe',
                age: '12',
                gender: 'F',
                country: 'INDIA',
                state: 'WB',
              },
            },
          },
        ],
        method: 'POST',
      },
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'birthday must be in this (YYYY-MM-DD) format',
            statTags: {
              destType: 'WEBENGAGE',
              errorCategory: 'dataValidation',
              errorType: 'instrumentation',
              feature: 'processor',
              implementation: 'native',
              module: 'destination',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
];
