export const data = [
  {
    name: 'gainsightpx',
    description: 'Identify Call',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'SIGN_UP',
                  eventId: '1283c08b-f290-4bc4-9deb-75c7867d69ee',
                  propertyKey: 'AP-EOXPSEZGC5LA-2-1',
                  date: 1665582808376,
                  sessionId: 'AP-EOXPSEZGC5LA-2-1665582441084-16821368',
                  globalContext: {},
                  userType: 'USER',
                },
                configId: '32f07727-d231-4c9d-881e-fb50b80bad63',
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'identify',
                  traits: {
                    type: 'USER',
                    gender: 'EMPTY_GENDER',
                    email: 'userEmail@address.com',
                    firstName: 'test',
                    lastName: 'rudderlabs',
                    title: 'Mr.',
                    score: 0,
                    globalUnsubscribe: false,
                    accountId: 'IBM',
                    numberOfVisits: 1,
                    propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                    id: 'New!',
                    country: 'India',
                    account: {
                      id: 'IBM',
                      name: 'International Business Machine',
                      numberOfEmployees: 0,
                      numberOfUsers: 0,
                    },
                  },
                  userId: 'New!',
                  createdAt: '2022-10-12T13:53:11.753Z',
                  originalTimestamp: '2022-10-12T13:53:11.753Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Custom Track Call ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'CUSTOM',
                  eventId: 'df58cbd6-2736-4f8a-ad26-6049eac2e150',
                  propertyKey: 'AP-EOXPSEZGC5LA-2-1',
                  date: 1665656881448,
                  sessionId: 'AP-EOXPSEZGC5LA-2-1665656622955-48127533',
                  globalContext: {},
                  userType: 'USER',
                  eventName: 'Product Clicked',
                  attributes: {
                    'Audience Size': 5000,
                    name: 'TESTing TRACK CALL FIRST',
                    'Launched date': 1520532660000,
                    Launched: true,
                  },
                  url: 'http://127.0.0.1:5501/GPXTEST2.html',
                  referrer: '',
                  remoteHost: '122.161.66.140',
                },
                configId: '32f07727-d231-4c9d-881e-fb50b80bad63',
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    ip: '122.161.66.140',
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-EOXPSEZGC5LA-2-1',
                    'Audience Size': 5000,
                    name: 'TESTing TRACK CALL FIRST',
                    'Launched date': 1520532660000,
                    Launched: true,
                    ip: '122.161.66.140',
                    url: 'http://127.0.0.1:5501/GPXTEST2.html',
                  },
                  userId: 'New!',
                  category: 'CUSTOM',
                  event: 'Product Clicked',
                  sentAt: '2022-10-13T10:28:01.448Z',
                  originalTimestamp: '2022-10-13T10:28:01.448Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Feedback Track Call ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'FEEDBACK',
                  eventId: 'd007bd76-decb-4a77-8456-d84fb15c6a83',
                  propertyKey: 'AP-E9VUBBLZ6BIS-2-1',
                  date: 1665415753621,
                  sessionId: 'AP-E9VUBBLZ6BIS-2-1665415678379-45445457',
                  globalContext: null,
                  userType: 'USER',
                  subject: 'feedback title',
                  category: 'Labels test',
                  description: 'feedback body',
                  labels: ['492120f5-3573-11ec-bef0-42010a800545'],
                  remoteHost: '122.161.66.140',
                  source: 'Knowledge Center Bot',
                },
                configId: '32f07727-d231-4c9d-881e-fb50b80bad63',
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                    ip: '122.161.66.140',
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-E9VUBBLZ6BIS-2-1',
                    feedback: {
                      labels: ['492120f5-3573-11ec-bef0-42010a800545'],
                      description: 'feedback body',
                      subject: 'feedback title',
                      source: 'Knowledge Center Bot',
                    },
                    ip: '122.161.66.140',
                  },
                  userId: 'New!',
                  category: 'FEEDBACK',
                  event: 'Labels test',
                  sentAt: '2022-10-10T15:29:13.621Z',
                  originalTimestamp: '2022-10-10T15:29:13.621Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Feature Match Track Call ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'FEATURE_MATCH',
                  eventId:
                    'ae1e5538-1736-4088-86d1-e90a10ffe901-05951b40-944f-4052-9a4a-51c74683f658',
                  propertyKey: 'AP-8MF5LPSWUBFW-2-1',
                  date: 1665582808376,
                  sessionId: 'AP-8MF5LPSWUBFW-2-1601303023809-98881162',
                  globalContext: { role: 'Admin' },
                  userType: 'USER',
                  featureId: '05951b40-944f-4052-9a4a-51c74683f658',
                  featureName: 'Charts',
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-8MF5LPSWUBFW-2-1',
                    globalContext: { role: 'Admin' },
                    featureId: '05951b40-944f-4052-9a4a-51c74683f658',
                  },
                  userId: 'New!',
                  category: 'FEATURE_MATCH',
                  event: 'Charts',
                  sentAt: '2022-10-12T13:53:28.376Z',
                  originalTimestamp: '2022-10-12T13:53:28.376Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Segment Match Track Call and no userId and yes anonymousId as event.sessionId',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'SEGMENT',
                  eventId: 'ddb9ca94-beb1-449c-bdcd-b53190f8e784',
                  propertyKey: 'AP-8MF5LPSWUBFW-2-1',
                  date: 1665582808376,
                  sessionId: 'AP-8MF5LPSWUBFW-2-1601303023809-98881162',
                  globalContext: { role: 'Admin' },
                  userType: 'USER',
                  segmentId: 'e3ab2e48-24f9-4602-ab92-b9f1f4343845',
                  segmentName: 'Linux User',
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  anonymousId: 'AP-8MF5LPSWUBFW-2-1601303023809-98881162',
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-8MF5LPSWUBFW-2-1',
                    globalContext: { role: 'Admin' },
                    segmentId: 'e3ab2e48-24f9-4602-ab92-b9f1f4343845',
                  },
                  category: 'SEGMENT',
                  event: 'Linux User',
                  sentAt: '2022-10-12T13:53:28.376Z',
                  originalTimestamp: '2022-10-12T13:53:28.376Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'No Match Track Call ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                event: {
                  eventType: 'Unavailable',
                  eventId: 'ddb9ca94-beb1-449c-bdcd-b53190f8e784',
                  propertyKey: 'AP-8MF5LPSWUBFW-2-1',
                  date: 1601303075964,
                  sessionId: 'AP-8MF5LPSWUBFW-2-1601303023809-98881162',
                  globalContext: { role: 'Admin' },
                  userType: 'USER',
                  segmentId: 'e3ab2e48-24f9-4602-ab92-b9f1f4343845',
                  segmentName: 'Linux User',
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            error: 'Event type Unavailable not supported',
            statTags: {
              destinationId: 'Non determinable',
              errorCategory: 'transformation',
              implementation: 'native',
              module: 'source',
              srcType: 'gainsightpx',
              workspaceId: 'Non determinable',
            },
            statusCode: 400,
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Survey Track Call -> Multi Question Survey ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'SURVEY',
                  eventId: 'c9883e3b-05d4-4f96-8b9c-e2ce10430493',
                  propertyKey: 'AP-N6SV00EVMR1E-2-1',
                  date: 1601303075964,
                  sessionId: 'AP-N6SV00EVMR1E-2-1605265939566-23853426',
                  globalContext: { role: 'Admin' },
                  userType: 'EMPTY_USER_TYPE',
                  contentType: 'IN_APP_MULTIPLE_QUESTION_SURVEY',
                  engagementId: 'e5362226-75da-4ef6-999a-823727e3d7a7',
                  engagementName: 'Quarterly Survey',
                  surveyType: 'Multi Question',
                  interaction: 'SINGLE_STEP_SURVEY_RESPONDED',
                  score: 0,
                  activation: 'Auto',
                  executionId: '1ad2d383-d1fa-425d-84f0-2a531e17a5d9',
                  executionDate: 1605265939965,
                  questionType: 'Multi choice',
                  questionId: 'de9e6bf1-351c-46ec-907d-c985bd420c2b',
                  questionHtml:
                    '<div class=px-multi-survey-question>Favorite travel destinations</div>',
                  questionText: 'Favorite travel destinations',
                  answers: [
                    {
                      answerId: '563e2103-2906-4088-869f-bcccd185f288',
                      answerHtml: '<div class=px-multi-survey-answer>Europe</div>',
                      answerText: 'Europe',
                    },
                  ],
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-N6SV00EVMR1E-2-1',
                    globalContext: { role: 'Admin' },
                    engagementId: 'e5362226-75da-4ef6-999a-823727e3d7a7',
                    contentType: 'IN_APP_MULTIPLE_QUESTION_SURVEY',
                    surveyType: 'Multi Question',
                    interaction: 'SINGLE_STEP_SURVEY_RESPONDED',
                    survey: {
                      activation: 'Auto',
                      questionType: 'Multi choice',
                      score: 0,
                      questionId: 'de9e6bf1-351c-46ec-907d-c985bd420c2b',
                      questionHtml:
                        '<div class=px-multi-survey-question>Favorite travel destinations</div>',
                      questionText: 'Favorite travel destinations',
                      answers: [
                        {
                          answerId: '563e2103-2906-4088-869f-bcccd185f288',
                          answerHtml: '<div class=px-multi-survey-answer>Europe</div>',
                          answerText: 'Europe',
                        },
                      ],
                    },
                  },
                  userId: 'New!',
                  category: 'SURVEY',
                  event: 'Quarterly Survey',
                  sentAt: '2020-09-28T14:24:35.964Z',
                  originalTimestamp: '2020-09-28T14:24:35.964Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Survey Track Call -> NPS ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'SURVEY',
                  eventId: 'c9883e3b-05d4-4f96-8b9c-e2ce10430493',
                  propertyKey: 'AP-N6SV00EVMR1E-2-1',
                  date: 1601303075964,
                  sessionId: 'AP-N6SV00EVMR1E-2-1605265939566-23853426',
                  globalContext: { role: 'Admin' },
                  userType: 'EMPTY_USER_TYPE',
                  contentType: 'IN_APP_MULTIPLE_QUESTION_SURVEY',
                  engagementId: 'e5362226-75da-4ef6-999a-823727e3d7a7',
                  engagementName: 'Quarterly Survey',
                  surveyType: 'Multi Question',
                  interaction: 'SINGLE_STEP_SURVEY_RESPONDED',
                  score: 0,
                  scoreType: null,
                  stepNumber: null,
                  userInput: 'I like new features',
                  activation: 'Auto',
                  executionId: '1ad2d383-d1fa-425d-84f0-2a531e17a5d9',
                  executionDate: 1605265939965,
                  questionType: 'Open text question',
                  questionHtml:
                    '<div class="px-survey-title">\n' +
                    '    <div>\n' +
                    '        How was your experience?\n' +
                    '     </div>\n' +
                    '</div>\n',
                  questionText: 'How was your experience?',
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-N6SV00EVMR1E-2-1',
                    globalContext: { role: 'Admin' },
                    engagementId: 'e5362226-75da-4ef6-999a-823727e3d7a7',
                    contentType: 'IN_APP_MULTIPLE_QUESTION_SURVEY',
                    surveyType: 'Multi Question',
                    interaction: 'SINGLE_STEP_SURVEY_RESPONDED',
                    survey: {
                      activation: 'Auto',
                      userInput: 'I like new features',
                      questionType: 'Open text question',
                      score: 0,
                      questionHtml:
                        '<div class="px-survey-title">\n' +
                        '    <div>\n' +
                        '        How was your experience?\n' +
                        '     </div>\n' +
                        '</div>\n',
                      questionText: 'How was your experience?',
                    },
                  },
                  userId: 'New!',
                  category: 'SURVEY',
                  event: 'Quarterly Survey',
                  sentAt: '2020-09-28T14:24:35.964Z',
                  originalTimestamp: '2020-09-28T14:24:35.964Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'Engagement Track Call ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'ENGAGEMENT',
                  eventId: '6494e73a-976b-4ee5-b8a8-de9effff7e80',
                  propertyKey: 'AP-N6SV00EVMR1E-2-1',
                  date: 1605262539389,
                  sessionId: 'AP-N6SV00EVMR1E-2-1605262502068-24197555',
                  globalContext: { role: 'Admin' },
                  userType: 'EMPTY_USER_TYPE',
                  contentType: 'IN_APP_DIALOG',
                  engagementId: '83c30d4e-88c3-4054-a0fa-33451a6ea7fc',
                  engagementType: 'Dialog',
                  engagementName: 'Release Announcement',
                  interaction: 'VIEWED',
                  stepNumber: 1,
                  activation: 'Auto',
                  executionId: 'b633945f-d4a5-404a-ae39-5ced5b542240',
                  executionDate: 1605262539389,
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-N6SV00EVMR1E-2-1',
                    engagementId: '83c30d4e-88c3-4054-a0fa-33451a6ea7fc',
                    contentType: 'IN_APP_DIALOG',
                    engagementType: 'Dialog',
                    interaction: 'VIEWED',
                    globalContext: { role: 'Admin' },
                    engagement: { stepNumber: 1, activation: 'Auto' },
                  },
                  userId: 'New!',
                  category: 'ENGAGEMENT',
                  event: 'Release Announcement',
                  sentAt: '2020-11-13T10:15:39.389Z',
                  originalTimestamp: '2020-11-13T10:15:39.389Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
  {
    name: 'gainsightpx',
    description: 'SegmentIO S2S Track Call ',
    module: 'source',
    version: 'v2',
    input: {
      request: {
        body: [
          {
            request: {
              body: JSON.stringify({
                user: {
                  aptrinsicId: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                  identifyId: 'New!',
                  type: 'USER',
                  gender: 'EMPTY_GENDER',
                  email: 'userEmail@address.com',
                  firstName: 'test',
                  lastName: 'rudderlabs',
                  lastSeenDate: 1665582808669,
                  signUpDate: 1665582791753,
                  firstVisitDate: 1665582791753,
                  title: 'Mr.',
                  phone: '',
                  score: 0,
                  role: '',
                  subscriptionId: '',
                  accountId: 'IBM',
                  numberOfVisits: 1,
                  location: {
                    countryName: 'India',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665582808376,
                  lastModifiedDate: 1665582808717,
                  customAttributes: null,
                  globalUnsubscribe: false,
                  sfdcContactId: '',
                  lastVisitedUserAgentData: null,
                  id: 'New!',
                  lastInferredLocation: null,
                },
                account: {
                  id: 'IBM',
                  name: 'International Business Machine',
                  trackedSubscriptionId: '',
                  sfdcId: '',
                  lastSeenDate: 1665582808669,
                  dunsNumber: '',
                  industry: '',
                  numberOfEmployees: 0,
                  sicCode: '',
                  website: '',
                  naicsCode: '',
                  plan: '',
                  location: {
                    countryName: '',
                    countryCode: '',
                    stateName: '',
                    stateCode: '',
                    city: '',
                    street: '',
                    postalCode: '',
                    continent: '',
                    regionName: '',
                    timeZone: '',
                    coordinates: { latitude: 0, longitude: 0 },
                  },
                  numberOfUsers: 0,
                  propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                  createDate: 1665578567565,
                  lastModifiedDate: 1665582808669,
                  customAttributes: null,
                  parentGroupId: '',
                },
                event: {
                  eventType: 'SEGMENT_IO',
                  eventId: 'ajs-next-69810a17571dc115ccead5281cc3fb7d',
                  propertyKey: 'AP-EOXPSEZGC5LA-2-1',
                  date: 1666687235178,
                  sessionId: '31a524fa-1490-48db-9600-adfb1fa95333',
                  globalContext: {},
                  userType: 'USER',
                  segmentIOEvent: {
                    pxPropertyKey: 'AP-EOXPSEZGC5LA-2',
                    type: 'group',
                    userId: '1001',
                    anonymousId: 'a4303a13-eb10-46d8-8935-d787daf1cfbd',
                    context: {
                      ip: '122.161.67.121',
                      library: { name: 'analytics.js', version: 'next-1.45.0' },
                      locale: 'en-GB',
                      userAgent:
                        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
                      page: {
                        path: '/abc.html',
                        title: 'Engage Testing',
                        url: 'http://127.0.0.1:5501/abc.html',
                      },
                    },
                    messageId: 'ajs-next-69810a17571dc115ccead5281cc3fb7d',
                    receivedAt: '2022-10-25T08:40:35.184Z',
                    sentAt: '2022-10-25T08:40:34.809Z',
                    timestamp: '2022-10-25T08:40:35.178Z',
                    traits: { name: 'International Business Machine' },
                    version: 2,
                    channel: 'client',
                    groupId: 'IBM',
                  },
                },
              }),
            },
            source: {},
          },
        ],
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              batch: [
                {
                  context: {
                    library: { name: 'unknown', version: 'unknown' },
                    integration: { name: 'GAINSIGHTPX' },
                    traits: {
                      type: 'USER',
                      gender: 'EMPTY_GENDER',
                      email: 'userEmail@address.com',
                      firstName: 'test',
                      lastName: 'rudderlabs',
                      title: 'Mr.',
                      globalUnsubscribe: false,
                      accountId: 'IBM',
                      numberOfVisits: 1,
                      propertyKeys: ['AP-EOXPSEZGC5LA-2-1'],
                      score: 0,
                      id: 'New!',
                      country: 'India',
                      account: {
                        numberOfEmployees: 0,
                        numberOfUsers: 0,
                        id: 'IBM',
                        name: 'International Business Machine',
                      },
                    },
                    externalId: [
                      {
                        type: 'gainsightpxAptrinsicId',
                        id: 'cab9c469-8602-4933-acdb-68338fbb9ab1',
                      },
                    ],
                  },
                  integrations: { GAINSIGHTPX: false },
                  type: 'track',
                  properties: {
                    propertyKey: 'AP-EOXPSEZGC5LA-2-1',
                    pxPropertyKey: 'AP-EOXPSEZGC5LA-2',
                    type: 'group',
                    userId: '1001',
                    anonymousId: 'a4303a13-eb10-46d8-8935-d787daf1cfbd',
                    context: {
                      ip: '122.161.67.121',
                      library: { name: 'analytics.js', version: 'next-1.45.0' },
                      locale: 'en-GB',
                      userAgent:
                        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
                      page: {
                        path: '/abc.html',
                        title: 'Engage Testing',
                        url: 'http://127.0.0.1:5501/abc.html',
                      },
                    },
                    messageId: 'ajs-next-69810a17571dc115ccead5281cc3fb7d',
                    receivedAt: '2022-10-25T08:40:35.184Z',
                    sentAt: '2022-10-25T08:40:34.809Z',
                    timestamp: '2022-10-25T08:40:35.178Z',
                    traits: { name: 'International Business Machine' },
                    version: 2,
                    channel: 'client',
                    groupId: 'IBM',
                  },
                  userId: 'New!',
                  category: 'SEGMENT_IO',
                  event: 'SegmentIO Cloud Server',
                  sentAt: '2022-10-25T08:40:35.178Z',
                  originalTimestamp: '2022-10-25T08:40:35.178Z',
                },
              ],
            },
          },
        ],
      },
    },
  },
];
