export const data = [
  {
    name: 'webhook',
    description: 'Test 0',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              user_properties: {
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                fb_profile: '0',
                game_fps: 30,
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: false,
                level: 6,
                lifetime_gem_balance: 0,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
              },
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                headers: [
                  { from: '', to: '' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  user_properties: {
                    total_payments: 0,
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    level: 6,
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    coin_balance: 9466052,
                    player_total_shields: 0,
                    isLowEndDevice: false,
                    game_fps: 30,
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    graphicsQuality: 'HD',
                    current_module_name: 'CasinoGameModule',
                    player_total_battles: 0,
                    lifetime_gem_balance: 0,
                    gem_balance: 0,
                    fb_profile: '0',
                    start_date: '2019-08-01',
                    versionSessionCount: 2,
                    game_name: 'FireEagleSlots',
                  },
                  integrations: { All: true },
                  event: 'spin_result',
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      model: 'Redmi 6',
                      manufacturer: 'Xiaomi',
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      name: 'xiaomi',
                    },
                    traits: {
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                    },
                    os: { version: '8.1.0', name: 'android' },
                    network: { carrier: 'Banglalink' },
                  },
                  type: 'track',
                  properties: {
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    jackpot_win_type: 'Silver',
                    coin_balance: 9466052,
                    bet_level: 1,
                    ishighroller: 'False',
                    tournament_id: 'T1561970819',
                    battle_id: 'N/A',
                    bet_amount: 9,
                    fb_profile: '0',
                    player_total_shields: 0,
                    is_turbo: 'False',
                    player_total_battles: 0,
                    bet_multiplier: 1,
                    start_date: '2019-08-01',
                    versionSessionCount: 2,
                    graphicsQuality: 'HD',
                    is_auto_spin: 'False',
                    days_in_game: 0,
                    additional_bet_index: 0,
                    isLowEndDevice: 'False',
                    game_fps: 30,
                    extra_param: 'N/A',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    current_module_name: 'CasinoGameModule',
                    game_id: 'fireEagleBase',
                    featureGameType: 'N/A',
                    gem_balance: 0,
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    total_payments: 0,
                    level: 6,
                    win_amount: 0,
                    no_of_spin: 1,
                    game_name: 'FireEagleSlots',
                    jackpot_win_amount: 90,
                    lifetime_gem_balance: 0,
                    isf: 'False',
                  },
                },
                FORM: {},
              },
              files: {},
              endpoint: 'http://6b0e6a60.ngrok.io',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { 'content-type': 'application/json', test2: 'value2' },
              version: '1',
              params: {},
              type: 'REST',
              method: 'POST',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 1',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              user_properties: {
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                fb_profile: '0',
                game_fps: 30,
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: false,
                level: 6,
                lifetime_gem_balance: 0,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
              },
            },
            destination: { Config: { webhookUrl: 'https://6b0e6a60.ngrok.io/n' } },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  user_properties: {
                    total_payments: 0,
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    level: 6,
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    coin_balance: 9466052,
                    player_total_shields: 0,
                    isLowEndDevice: false,
                    game_fps: 30,
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    graphicsQuality: 'HD',
                    current_module_name: 'CasinoGameModule',
                    player_total_battles: 0,
                    lifetime_gem_balance: 0,
                    gem_balance: 0,
                    fb_profile: '0',
                    start_date: '2019-08-01',
                    versionSessionCount: 2,
                    game_name: 'FireEagleSlots',
                  },
                  integrations: { All: true },
                  event: 'spin_result',
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      model: 'Redmi 6',
                      manufacturer: 'Xiaomi',
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      name: 'xiaomi',
                    },
                    traits: {
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                    },
                    os: { version: '8.1.0', name: 'android' },
                    network: { carrier: 'Banglalink' },
                  },
                  type: 'track',
                  properties: {
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    jackpot_win_type: 'Silver',
                    coin_balance: 9466052,
                    bet_level: 1,
                    ishighroller: 'False',
                    tournament_id: 'T1561970819',
                    battle_id: 'N/A',
                    bet_amount: 9,
                    fb_profile: '0',
                    player_total_shields: 0,
                    is_turbo: 'False',
                    player_total_battles: 0,
                    bet_multiplier: 1,
                    start_date: '2019-08-01',
                    versionSessionCount: 2,
                    graphicsQuality: 'HD',
                    is_auto_spin: 'False',
                    days_in_game: 0,
                    additional_bet_index: 0,
                    isLowEndDevice: 'False',
                    game_fps: 30,
                    extra_param: 'N/A',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    current_module_name: 'CasinoGameModule',
                    game_id: 'fireEagleBase',
                    featureGameType: 'N/A',
                    gem_balance: 0,
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    total_payments: 0,
                    level: 6,
                    win_amount: 0,
                    no_of_spin: 1,
                    game_name: 'FireEagleSlots',
                    jackpot_win_amount: 90,
                    lifetime_gem_balance: 0,
                    isf: 'False',
                  },
                },
                FORM: {},
              },
              files: {},
              endpoint: 'https://6b0e6a60.ngrok.io/n',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { 'content-type': 'application/json' },
              version: '1',
              params: {},
              type: 'REST',
              method: 'POST',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 2',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              user_properties: {
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                fb_profile: '0',
                game_fps: 30,
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: false,
                level: 6,
                lifetime_gem_balance: 0,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
              },
            },
            destination: { Config: { webhookUrl: 'https://6b0e6a60.' } },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  user_properties: {
                    total_payments: 0,
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    level: 6,
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    coin_balance: 9466052,
                    player_total_shields: 0,
                    isLowEndDevice: false,
                    game_fps: 30,
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    graphicsQuality: 'HD',
                    current_module_name: 'CasinoGameModule',
                    player_total_battles: 0,
                    lifetime_gem_balance: 0,
                    gem_balance: 0,
                    fb_profile: '0',
                    start_date: '2019-08-01',
                    versionSessionCount: 2,
                    game_name: 'FireEagleSlots',
                  },
                  integrations: { All: true },
                  event: 'spin_result',
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      model: 'Redmi 6',
                      manufacturer: 'Xiaomi',
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      name: 'xiaomi',
                    },
                    traits: {
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                    },
                    os: { version: '8.1.0', name: 'android' },
                    network: { carrier: 'Banglalink' },
                  },
                  type: 'track',
                  properties: {
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    jackpot_win_type: 'Silver',
                    coin_balance: 9466052,
                    bet_level: 1,
                    ishighroller: 'False',
                    tournament_id: 'T1561970819',
                    battle_id: 'N/A',
                    bet_amount: 9,
                    fb_profile: '0',
                    player_total_shields: 0,
                    is_turbo: 'False',
                    player_total_battles: 0,
                    bet_multiplier: 1,
                    start_date: '2019-08-01',
                    versionSessionCount: 2,
                    graphicsQuality: 'HD',
                    is_auto_spin: 'False',
                    days_in_game: 0,
                    additional_bet_index: 0,
                    isLowEndDevice: 'False',
                    game_fps: 30,
                    extra_param: 'N/A',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    current_module_name: 'CasinoGameModule',
                    game_id: 'fireEagleBase',
                    featureGameType: 'N/A',
                    gem_balance: 0,
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    total_payments: 0,
                    level: 6,
                    win_amount: 0,
                    no_of_spin: 1,
                    game_name: 'FireEagleSlots',
                    jackpot_win_amount: 90,
                    lifetime_gem_balance: 0,
                    isf: 'False',
                  },
                },
                FORM: {},
              },
              files: {},
              endpoint: 'https://6b0e6a60.',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { 'content-type': 'application/json' },
              version: '1',
              params: {},
              type: 'REST',
              method: 'POST',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 3',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: { k1: 'v1', k2: { k3: 'c3', k4: { k5: 'c5' } } },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
            },
            destination: {
              Config: {
                webhookUrl: 'https://6b0e6a60.',
                webhookMethod: 'GET',
                headers: [{ from: 'X-customHeader', to: 'customHeaderVal' }],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'GET',
              endpoint: 'https://6b0e6a60.',
              headers: { 'x-customheader': 'customHeaderVal' },
              params: { k1: 'v1', 'k2.k3': 'c3', 'k2.k4.k5': 'c5' },
              body: { JSON: {}, XML: {}, JSON_ARRAY: {}, FORM: {} },
              files: {},
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 4',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: { k1: 'v1', k2: { k3: 'c3', k4: { k5: 'c5' } } },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
            },
            destination: { Config: { webhookUrl: 'https://6b0e6a60.', webhookMethod: 'GET' } },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'GET',
              endpoint: 'https://6b0e6a60.',
              headers: {},
              params: { k1: 'v1', 'k2.k3': 'c3', 'k2.k4.k5': 'c5' },
              body: { JSON: {}, XML: {}, JSON_ARRAY: {}, FORM: {} },
              files: {},
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 5',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              request_ip: '127.0.0.1',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                header: [
                  { from: 'test1', to: 'value1' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'http://6b0e6a60.ngrok.io',
              headers: { 'content-type': 'application/json' },
              params: {},
              body: {
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                    ip: '127.0.0.1',
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    bet_amount: 9,
                    bet_level: 1,
                    bet_multiplier: 1,
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    days_in_game: 0,
                    extra_param: 'N/A',
                    fb_profile: '0',
                    featureGameType: 'N/A',
                    game_fps: 30,
                    game_id: 'fireEagleBase',
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: 'False',
                    is_auto_spin: 'False',
                    is_turbo: 'False',
                    isf: 'False',
                    ishighroller: 'False',
                    jackpot_win_amount: 90,
                    jackpot_win_type: 'Silver',
                    level: 6,
                    lifetime_gem_balance: 0,
                    no_of_spin: 1,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    tournament_id: 'T1561970819',
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                  request_ip: '127.0.0.1',
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 6',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              request_ip: '127.0.0.1',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                headers: [
                  { from: 'Content-Type', to: 'application/xml' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'http://6b0e6a60.ngrok.io',
              headers: { 'content-type': 'application/xml', test2: 'value2' },
              params: {},
              body: {
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                    ip: '127.0.0.1',
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    bet_amount: 9,
                    bet_level: 1,
                    bet_multiplier: 1,
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    days_in_game: 0,
                    extra_param: 'N/A',
                    fb_profile: '0',
                    featureGameType: 'N/A',
                    game_fps: 30,
                    game_id: 'fireEagleBase',
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: 'False',
                    is_auto_spin: 'False',
                    is_turbo: 'False',
                    isf: 'False',
                    ishighroller: 'False',
                    jackpot_win_amount: 90,
                    jackpot_win_type: 'Silver',
                    level: 6,
                    lifetime_gem_balance: 0,
                    no_of_spin: 1,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    tournament_id: 'T1561970819',
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                  request_ip: '127.0.0.1',
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 7',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                headers: [
                  { from: 'Content-Type', to: 'application/xml' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              version: '1',
              type: 'REST',
              method: 'POST',
              endpoint: 'http://6b0e6a60.ngrok.io',
              headers: { 'content-type': 'application/xml', test2: 'value2' },
              params: {},
              body: {
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    bet_amount: 9,
                    bet_level: 1,
                    bet_multiplier: 1,
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    days_in_game: 0,
                    extra_param: 'N/A',
                    fb_profile: '0',
                    featureGameType: 'N/A',
                    game_fps: 30,
                    game_id: 'fireEagleBase',
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: 'False',
                    is_auto_spin: 'False',
                    is_turbo: 'False',
                    isf: 'False',
                    ishighroller: 'False',
                    jackpot_win_amount: 90,
                    jackpot_win_type: 'Silver',
                    level: 6,
                    lifetime_gem_balance: 0,
                    no_of_spin: 1,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    tournament_id: 'T1561970819',
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                },
                XML: {},
                JSON_ARRAY: {},
                FORM: {},
              },
              files: {},
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 8',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                featureGameType: 'N/A',
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              header: {
                dynamic_header_key_string: 'dynamic_header_value_string',
                dynamic_header_key_num: 10,
                dynamic_header_key_object: { k1: 'v1' },
              },
              appendPath: '/product/search?string=value',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                headers: [
                  { from: '', to: '' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    featureGameType: 'N/A',
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                },
                FORM: {},
              },
              files: {},
              endpoint: 'http://6b0e6a60.ngrok.io/product/search?string=value',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: {
                'content-type': 'application/json',
                test2: 'value2',
                dynamic_header_key_string: 'dynamic_header_value_string',
              },
              version: '1',
              params: {},
              type: 'REST',
              method: 'POST',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 9',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                featureGameType: 'N/A',
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              fullPath: 'https://www.google.com',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                headers: [
                  { from: '', to: '' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    featureGameType: 'N/A',
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                },
                FORM: {},
              },
              files: {},
              endpoint: 'https://www.google.com',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { 'content-type': 'application/json', test2: 'value2' },
              version: '1',
              params: {},
              type: 'REST',
              method: 'POST',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 10',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                featureGameType: 'N/A',
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              fullPath: 'https://www.google.com/',
              appendPath: '?searchTerms=cats',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                headers: [
                  { from: '', to: '' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    featureGameType: 'N/A',
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                },
                FORM: {},
              },
              files: {},
              endpoint: 'https://www.google.com/?searchTerms=cats',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { 'content-type': 'application/json', test2: 'value2' },
              version: '1',
              params: {},
              type: 'REST',
              method: 'POST',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 11',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                featureGameType: 'N/A',
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              fullPath: 'https://www.google.com/',
              appendPath: '?searchTerms=cats',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                webhookMethod: 'PUT',
                headers: [
                  { from: '', to: '' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                XML: {},
                JSON_ARRAY: {},
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    featureGameType: 'N/A',
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                },
                FORM: {},
              },
              files: {},
              endpoint: 'https://www.google.com/?searchTerms=cats',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { 'content-type': 'application/json', test2: 'value2' },
              version: '1',
              params: {},
              type: 'REST',
              method: 'PUT',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 12',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                featureGameType: 'N/A',
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              fullPath: 'https://www.google.com/',
              appendPath: '?searchTerms=cats',
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                webhookMethod: 'DELETE',
                headers: [
                  { from: '', to: '' },
                  { from: 'test2', to: 'value2' },
                ],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: { XML: {}, JSON_ARRAY: {}, JSON: {}, FORM: {} },
              files: {},
              endpoint: 'https://www.google.com/?searchTerms=cats',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              headers: { test2: 'value2' },
              version: '1',
              params: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                featureGameType: 'N/A',
                win_amount: 0,
              },
              type: 'REST',
              method: 'DELETE',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 13',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              user_properties: {
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                fb_profile: '0',
                game_fps: 30,
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: false,
                level: 6,
                lifetime_gem_balance: 0,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
              },
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                webhookMethod: 'POST',
                headers: [{ from: 'test2', to: 'value2' }],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                FORM: {},
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    bet_amount: 9,
                    bet_level: 1,
                    bet_multiplier: 1,
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    days_in_game: 0,
                    extra_param: 'N/A',
                    fb_profile: '0',
                    featureGameType: 'N/A',
                    game_fps: 30,
                    game_id: 'fireEagleBase',
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: 'False',
                    is_auto_spin: 'False',
                    is_turbo: 'False',
                    isf: 'False',
                    ishighroller: 'False',
                    jackpot_win_amount: 90,
                    jackpot_win_type: 'Silver',
                    level: 6,
                    lifetime_gem_balance: 0,
                    no_of_spin: 1,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    tournament_id: 'T1561970819',
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                  user_properties: {
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    fb_profile: '0',
                    game_fps: 30,
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: false,
                    level: 6,
                    lifetime_gem_balance: 0,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
              },
              endpoint: 'http://6b0e6a60.ngrok.io',
              files: {},
              headers: { 'content-type': 'application/json', test2: 'value2' },
              method: 'POST',
              params: {},
              type: 'REST',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              version: '1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
  {
    name: 'webhook',
    description: 'Test 14',
    feature: 'processor',
    module: 'destination',
    version: 'v0',
    input: {
      request: {
        body: [
          {
            message: {
              anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              context: {
                device: {
                  id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                  manufacturer: 'Xiaomi',
                  model: 'Redmi 6',
                  name: 'xiaomi',
                },
                network: { carrier: 'Banglalink' },
                os: { name: 'android', version: '8.1.0' },
                traits: {
                  address: { city: 'Dhaka', country: 'Bangladesh' },
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                },
              },
              event: 'spin_result',
              integrations: { All: true },
              message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
              properties: {
                additional_bet_index: 0,
                battle_id: 'N/A',
                bet_amount: 9,
                bet_level: 1,
                bet_multiplier: 1,
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                days_in_game: 0,
                extra_param: 'N/A',
                fb_profile: '0',
                featureGameType: 'N/A',
                game_fps: 30,
                game_id: 'fireEagleBase',
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: 'False',
                is_auto_spin: 'False',
                is_turbo: 'False',
                isf: 'False',
                ishighroller: 'False',
                jackpot_win_amount: 90,
                jackpot_win_type: 'Silver',
                level: 6,
                lifetime_gem_balance: 0,
                no_of_spin: 1,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                tournament_id: 'T1561970819',
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
                win_amount: 0,
              },
              timestamp: '2019-09-01T15:46:51.693229+05:30',
              type: 'track',
              user_properties: {
                coin_balance: 9466052,
                current_module_name: 'CasinoGameModule',
                fb_profile: '0',
                game_fps: 30,
                game_name: 'FireEagleSlots',
                gem_balance: 0,
                graphicsQuality: 'HD',
                idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                internetReachability: 'ReachableViaLocalAreaNetwork',
                isLowEndDevice: false,
                level: 6,
                lifetime_gem_balance: 0,
                player_total_battles: 0,
                player_total_shields: 0,
                start_date: '2019-08-01',
                total_payments: 0,
                userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                versionSessionCount: 2,
              },
            },
            destination: {
              Config: {
                webhookUrl: 'http://6b0e6a60.ngrok.io',
                webhookMethod: 'PATCH',
                headers: [{ from: 'test2', to: 'value2' }],
              },
            },
          },
        ],
        method: 'POST',
      },
      pathSuffix: '',
    },
    output: {
      response: {
        status: 200,
        body: [
          {
            output: {
              body: {
                FORM: {},
                JSON: {
                  anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                  context: {
                    device: {
                      id: 'df16bffa-5c3d-4fbb-9bce-3bab098129a7R',
                      manufacturer: 'Xiaomi',
                      model: 'Redmi 6',
                      name: 'xiaomi',
                    },
                    network: { carrier: 'Banglalink' },
                    os: { name: 'android', version: '8.1.0' },
                    traits: {
                      address: { city: 'Dhaka', country: 'Bangladesh' },
                      anonymousId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    },
                  },
                  event: 'spin_result',
                  integrations: { All: true },
                  message_id: 'a80f82be-9bdc-4a9f-b2a5-15621ee41df8',
                  properties: {
                    additional_bet_index: 0,
                    battle_id: 'N/A',
                    bet_amount: 9,
                    bet_level: 1,
                    bet_multiplier: 1,
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    days_in_game: 0,
                    extra_param: 'N/A',
                    fb_profile: '0',
                    featureGameType: 'N/A',
                    game_fps: 30,
                    game_id: 'fireEagleBase',
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: 'False',
                    is_auto_spin: 'False',
                    is_turbo: 'False',
                    isf: 'False',
                    ishighroller: 'False',
                    jackpot_win_amount: 90,
                    jackpot_win_type: 'Silver',
                    level: 6,
                    lifetime_gem_balance: 0,
                    no_of_spin: 1,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    tournament_id: 'T1561970819',
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                    win_amount: 0,
                  },
                  timestamp: '2019-09-01T15:46:51.693229+05:30',
                  type: 'track',
                  user_properties: {
                    coin_balance: 9466052,
                    current_module_name: 'CasinoGameModule',
                    fb_profile: '0',
                    game_fps: 30,
                    game_name: 'FireEagleSlots',
                    gem_balance: 0,
                    graphicsQuality: 'HD',
                    idfa: '2bf99787-33d2-4ae2-a76a-c49672f97252',
                    internetReachability: 'ReachableViaLocalAreaNetwork',
                    isLowEndDevice: false,
                    level: 6,
                    lifetime_gem_balance: 0,
                    player_total_battles: 0,
                    player_total_shields: 0,
                    start_date: '2019-08-01',
                    total_payments: 0,
                    userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
                    versionSessionCount: 2,
                  },
                },
                JSON_ARRAY: {},
                XML: {},
              },
              endpoint: 'http://6b0e6a60.ngrok.io',
              files: {},
              headers: { 'content-type': 'application/json', test2: 'value2' },
              method: 'PATCH',
              params: {},
              type: 'REST',
              userId: 'c82cbdff-e5be-4009-ac78-cdeea09ab4b1',
              version: '1',
            },
            statusCode: 200,
          },
        ],
      },
    },
  },
];
