- destKey: dc_rdid
  sourceKeys: context.device.advertisingId
  required: true

- destKey: ord
  sourceKeys:
    - properties.orderId
    - properties.order_id
  required: false

- destKey: qty
  sourceKeys: properties.quantity
  required: false

- destKey: cost
  sourceKeys: properties.revenue
  required: false

- destKey: dc_lat
  sourceKeys: context.device.adTrackingEnabled
  required: false
