name: Build transformer image for pr
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - converted_to_draft
      - ready_for_review
      - synchronize
env:
  REPO_NAME_OLD: rudderlabs/develop-rudder-transformer
  REPO_NAME: rudderstack/develop-rudder-transformer
  DOCKERHUB_USERNAME: rudderlabs

jobs:
  transformer-build:
    name: Build transformer image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${{ github.head_ref }} | tr "/" .)"
        id: extract_branch

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }} npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-platform images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ steps.extract_branch.outputs.branch }}
            ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ steps.extract_branch.outputs.branch }}
            COMMIT_HASH=${{ github.sha }}
  
  user-transformer-build:
    name: Build user transformer image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]ut-$(echo ${{ github.head_ref }} | tr "/" .)"
        id: extract_branch

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-ut-func
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }} npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-platform images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-ut-func
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ steps.extract_branch.outputs.branch }}
            ${{ env.REPO_NAME }}:${{ steps.extract_branch.outputs.branch }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ steps.extract_branch.outputs.branch }}
            COMMIT_HASH=${{ github.sha }}
