on:
  push:
    branches:
      - "master"

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ github.token }}
          pull-request-title-pattern: "chore: release ${version}"
          release-type: node
          package-name: rudder-transformer
          default-branch: ${{ steps.extract_branch.outputs.branch }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"refactor","section":"Miscellaneous","hidden":false},{"type":"test","section":"Miscellaneous","hidden":false},{"type":"doc","section":"Documentation","hidden":false}]'
