# https://github.com/marketplace/actions/jest-coverage-report
name: Generate Code Coverage
on:
  pull_request:
    branches:
      - '*'

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
