name: Rollback

on:
  workflow_dispatch:

jobs:
  create-rollback-pr:
    name: Create PR for Rollback
    runs-on: ubuntu-latest

    # Only allow to be deployed from tags and main branch
    # Only allow specific actors to trigger
    if: (startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/main')) && (github.actor == 'ItsSudip' || github.actor == 'krishna2020' || github.actor == 'saikumarrs') && (github.triggering_actor == 'ItsSudip' || github.triggering_actor == 'krishna2020' || github.triggering_actor == 'saikumarrs')

    steps:
      - name: Get Target Version
        id: target-version
        run: |
          tag_name=${{ github.ref_name }}
          echo "version=${tag_name#v}" >> $GITHUB_OUTPUT
          echo "Target version: $version"

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize Mandatory Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      - name: Clone rudder-devops and Create Branch
        run: |
          git clone https://${{secrets.PAT}}@github.com/rudderlabs/rudder-devops.git
          cd rudder-devops
          git checkout -b shared-transformer-rollback-${{ steps.target-version.outputs.version }}

      - name: Update Helm Charts
        run: |
          cd helm-charts/shared-services/per-az
          yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
          yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.blue-release.yaml
          git add values.blue-release.yaml

          yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.enterprise.yaml
          yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.enterprise.yaml
          git add values.enterprise.yaml

          yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.multi-tenant.yaml
          yq eval -i ".user-transformer.image.tag=\"$VERSION\"" values.enterprise.yaml
          git add values.enterprise.yaml

          cd ../../config-be-rudder-transformer
          yq eval -i ".config-be-rudder-transformer.image.tag=\"$VERSION\"" values.prod.yaml
          yq eval -i ".config-be-user-transformer.image.tag=\"$VERSION\"" values.prod.yaml
          git add values.prod.yaml

      - name: Create Pull Request
        run: |
          git commit -m "rollback the version of shared transformers to $VERSION"
          git push -u origin shared-transformer-rollback-$VERSION
          hub pull-request -m "chore: rollback the version of shared transformers to $VERSION"
