name: Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - converted_to_draft
      - ready_for_review
      - synchronize

jobs:
  run-linters:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Node.js Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:silent

