name: Notify workflow failure

on:
  workflow_call:
    inputs:
      should_notify:
        type: boolean
        default: true
      workflow_url:
        type: string
        required: true
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_INTEGRATION_DEV_CHANNEL_ID:
        required: true

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout repository code (actions/checkout)
    if: ${{ inputs.should_notify }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: notify
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        continue-on-error: true
        env:
          PROJECT_NAME: 'Rudder Transformer'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ secrets.SLACK_INTEGRATION_DEV_CHANNEL_ID }}",
              "text": "*<prod release tests failed>*\nCC: <!subteam^S02AEQL26CT>",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":siren2:  prod release tests - Failed  :siren2:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*<${{inputs.workflow_url}}|failed workflow>*\nCC: <!subteam^S02AEQL26CT>"
                  }
                }
              ]
            }
