import logger from '../logger';
import { SecretPathsManifest } from './types';
// The manifest is a build artifact: generated by test/secret-paths/generate.ts and committed,
// so it ships inside the same image as the transform code it describes.
import manifest from './secretPaths.json';

const loaded = manifest as unknown as SecretPathsManifest;

/** Artifact shape this code understands. Internal: the paths ship inside /features, so a
 * consumer never sees a version and can never hold paths from a different build. */
const SUPPORTED_VERSION = 2;

/**
 * An artifact we cannot vouch for is refused, not served with a log line beside it.
 *
 * Checked at load rather than trusted, so a manifest this build does not understand is caught
 * here instead of going onto /features as though it were genuine. The empty map is the
 * fail-closed answer and needs no special case downstream: by the published contract a destType
 * absent from the map is the same as `null`, so every destination masks everything until this
 * is fixed.
 *
 * Logging and serving it anyway would be the one failure this whole artifact exists to prevent -
 * a manifest that names the wrong fields is worse than no manifest, because the consumer trusts
 * it and shows everything it does not name.
 */
const trustworthy = (): boolean => {
  if (loaded.version !== SUPPORTED_VERSION) {
    logger.error(
      `[secretPaths] manifest is v${loaded.version} but this build serves v${SUPPORTED_VERSION} - masking everything until regenerated`,
    );
    return false;
  }
  // Shape, not just version. A truncated or half-written artifact can parse as JSON and carry the
  // right version while `destinations` is missing or holds a bare string where a list belongs -
  // and an entry of the wrong type is worse than a missing one, because the consumer iterates it.
  const { destinations } = loaded;
  if (typeof destinations !== 'object' || destinations === null || Array.isArray(destinations)) {
    logger.error('[secretPaths] manifest has no destinations map - masking everything');
    return false;
  }
  const malformed = Object.entries(destinations).find(
    ([, paths]) =>
      paths !== null && (!Array.isArray(paths) || paths.some((p) => typeof p !== 'string')),
  );
  if (malformed) {
    logger.error(
      `[secretPaths] manifest entry for ${malformed[0]} is not a list of paths - masking everything`,
    );
    return false;
  }
  return true;
};

/**
 * destType -> paths to mask, or `null` for "mask everything maskable". Embedded in /features.
 *
 * `null` survives JSON serialisation as `null`, so the consumer sees the same three cases the
 * manifest records: a list, `null`, or an absent key - the last two meaning the same thing.
 */
export const secretPaths: Record<string, string[] | null> = trustworthy()
  ? loaded.destinations
  : {};
